### ISSUE TITLE
Realtime: Connection

### ISSUE THREAD

**Issue by yavor87** [ably/ably-dotnet#10]
* [x]   **RTN1** `Connection` connects to the Ably service using a websocket connection. The [ably-js library](https://github.ably.io/ably/ably-js) supports additional transports such as Comet and XHR streaming; however non-browser client libraries typically use only a websocket transport
* [x]   **RTN2** The default host used for realtime websocket connections is `realtime.ably.io`, and the following query string params should be used when opening a new connection:
    * [x]   **RTN2a** `format` should be `msgpack` (default) or `json`
    * [x]   **RTN2b** `echo` should be `true` by default; `false` will prevent messages published by the client being echoed back
* [x]   **RTN3** If connection option `autoConnect` is true, a connection is initiated immediately; otherwise a connection is only initiated following an explicit call to `connect(**.
* [x]   **RTN4** EventEmitter and states:
    * [x]   **RTN4a** Implements `EventEmitter` and emits events for state changes `INITIALIZED`, `CONNECTING`, `CONNECTED`, `DISCONNECTED`, `SUSPENDED`, `CLOSING`, `CLOSED`, `FAILED`
    * [x]   **RTN4b** A new connection will emit the following events in order when connecting: `CONNECTING`, then `CONNECTED`
    * [x]   **RTN4c** A connection will emit the following events when closing the connection: `CLOSING`, then `CLOSED`
    * [x]   **RTN4d** `Connection#state` attribute is the current state of the connection
    * [x]   **RTN4e** A `ConnectionStateChange` object is emitted as the first argument for every connection state change
    * [x]   **RTN4f** Additionally, a `ConnectionStateChange` can be emitted that contains an `errorReason` which contains an `ErrorInfo` object with details of the error that has occurred for the `Connection`.
* [ ]   **RTN5** A test should exist that instances many (50+) clients simultaneously and performs a few basic operations such as attaching to a channel, publishing a message, and expecting all of those messages to arrive on all clients to ensure that there are no concurrency issues with the client library
* [x]   **RTN6** A `Connection` is successful and considered `CONNECTED` once the websocket connection is open and the intial `CONNECTED` `ProtocolMessage` has been received
* [x]   **RTN7** `ACK` and `NACK`:
    * [x]   **RTN7a** All `ProtocolMessage` `Presence` and `Message` objects sent to Ably expect either an `ACK` or `NACK` from Ably to confirm successful receipt and acceptance or failure respectively
    * [x]   **RTN7b** Every `ProtocolMessage` sent must contain a unique serially incrementing `msgSerial` integer value starting at zero. The `msgSerial` along with the `count` for incoming `ACK` and `NACK` `ProtocolMessages` indicates which messages succeeded or failed to be delivered
    * [x]   **RTN7c** If a connection enters the `CLOSED` or `FAILED` state, or if the connection state is lost, and a `ACK` or `NACK` has not yet been received for a message, the client should consider the delivery of those messages as failed
* [x]   **RTN8** `Connection#id` attribute:
    * [x]   **RTN8a** Is `Null` until connected
    * [x]   **RTN8b** Is a unique string provided by Ably. You should have a test to ensure multiple connected clients have unique connection IDs
* [x]   **RTN9** `Connection#key` attribute:
    * [x]   **RTN9a** Is Null until connected
    * [x]   **RTN9b** Is a unique private connection key provided by Ably that is used to reconnect and retain connection state following an unexpected disconnection. You should have a test to ensure multiple connected clients have unique connection keys
* [x]   **RTN10** `Connection#serial` attribute:
    * [x]   **RTN10a** Is set to -1 once `CONNECTED`
    * [x]   **RTN10b** Is always 0 when the first message has been sent and an `ACK` has been received confirming receipt of the message. The `serial` is updated whenever a `ProtocolMessage` is received that contains a `connectionSerial` value. A test should exist that checks that the serial number is not updated when a message is sent, but then increments by one when the `ACK` is received
    * [x]   **RTN10c** The last known `ProtocolMessage` `connectionSerial` is used when restoring connection state
* [x]   **RTN11** `Connection#connect` function:
    * [x]   **RTN11a** Explicitly connects to the Ably service if not already connected.
    * [x]   **RTN11b** An error will be indicated if the state is `CLOSING` as the connection must complete the close request before reconnecting
    * [ ]   **RTN11c** Where the language permits, a callback with a success and failure state can be provided
* [x]   **RTN12** `Connection#close` function:
    * [x]   **RTN12b** Sends a `CLOSE` `ProtocolMessage` to the server, sets the state to `CLOSING` and waits for a `CLOSED` `ProtocolMessage` to be received
    * [x]   **RTN12c** If the `CLOSED` `ProtocolMessage` is not received within the [configured close timeout](https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/connection/connection_manager.rb), the transport will be disconnected and the connection will automatically move to the `CLOSED` state
    * [x]   **RTN12d** If the transport is abruptly closed following a `CLOSE` `ProtocolMessage` being sent, then the connection will automatically move to the `CLOSED` state
* [x]   **RTN13** `Connection#ping` function:
    * [x]   **RTN13a** Will send a `ProtocolMessage` with action `HEARTBEAT` the Ably service when connected and expects a `HEARTBEAT` message in response. If the client library language supports callbacks, then the callback will be called with the response time or error
    * [x]   **RTN13b** Will immediately raise an exception if in the `CLOSED` or `FAILED` state
* [x]   **RTN14** `Connection` opening failures:
    * [x]   **RTN14a** If an API key is invalid, then the connection will enter the `FAILED` state and the `errorReason` will be set on the `Connection` object as well as the emitted `ConnectionStateChange`
    * [ ]   **RTN14b** If a connection request fails because the token has expired, and the token is renewable, then a new token will be created and subsequent requests will be made without changing the state or emitting an error. If the token is not renewable, the connection will transition to the `FAILED` state
    * [x]   **RTN14c** A new connection attempt will fail if not connected within the [configured open timeout](https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/connection/connection_manager.rb).
    * [x]   **RTN14d** If a connection attempt fails for any recoverable reason (i.e. not an authentication failure), the `Connection#state` will change to `DISCONNECTED`, the `Connection#errorReason` will be updated, a `ConnectionStateChange` with the `errorReason` will be emitted, and new connection attempts will periodically be made until the maximum time in that state threshold is reached. The `retryIn` attribute of the `ConnectionStateChange` object will contain the time in milliseconds until the next connection attempt. See [disconnected retry config](https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/connection/connection_manager.rb). Each time a new connection attempt is made the state will change to `CONNECTING` and then to `CONNECTED` if successful, or `DISCONNECTED` if unsuccessful and the [disconnected state threshold](https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/connection/connection_manager.rb) has not been exceeded.
    * [x]   **RTN14e** Once the connection state has been in the `DISCONNECTED` state for more than the [disconnected state threshold](https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/connection/connection_manager.rb), the state will change to `SUSPENDED` and be emitted with the `errorReason`, and the `Connection#errorReason` will be updated. In this state, a new connection attempt will be made periodically as defined in the [suspended state threshold](https://github.com/ably/ably-ruby/blob/master/lib/ably/realtime/connection/connection_manager.rb)
    * [x]   **RTN14f** The connection will remain in the `SUSPENDED` state indefinitely, whilst periodically attempting to reestablish a connection
* [x]   **RTN15** `Connection` failures once `CONNECTED`:
    * [x]   **RTN15a** If a `Connection` transport is disconnected unexpectedly or if a token expires, then the `Connection` manager will immediately attempt to reconnect and restore the connection state. Connection state recovery is provided by the Ably service and ensures that whilst the client is disconnected, all events are queued and channel state is retained on the Ably servers. When a new connection is made with the correct connection recovery key, the client is able to catch up by receiving the queued `ProtocolMessages` from Ably. Connection state is only maintained for a brief period, up to a minute, so if a client is disconnected for a longer period connection state cannot be resumed
    * [x]   **RTN15b** In order for a connection to be resumed and connection state to be recovered, the client library reconnects to the websocket endpoint with two additional querystring params:
        * [x]   **RTN15b1** `resume` is the private connection key assigned to the connection when the first `CONNECTED` `ProtocolMessage` was received
        * [x]   **RTN15b2** `connection_serial` is the most recent `ProtocolMessage#connectionSerial` received from Ably or `Connection#serial` which should be identical
    * [ ]   **RTN15c** When a new connection is made using the `resume` and `connection_serial` params, the client library must consider the resume to have failed if the `CONNECTED` `ProtocolMessage` contains an error or if the `Connection#id` or `Connection#key` has changed. When a `Connection` resume has failed, all channels should be detach with a suitable error reason
    * [ ]   **RTN15d** Client libraries should have test coverage to ensure connection state recovery is working as expected by forciby disconnecting a client and checking that messages published on channels are delivered once the connection is resumed
* [ ]   **RTN16** `Connection` recovery:
    * [ ]   **RTN16a** Connection recovery is similar to the automatic connection resume except that connection state is recovered explicitly because a `recover` key is passed to the Realtime library when instanced. Once a connection is recovered, all channels must be explicitly attached by the developer, and any messages queued to be delivered whilst the client was disconnected will be delivered
    * [ ]   **RTN16b** `Connection#recoveryKey` is an attribute composed of the connection key and latest serial received on the connection
    * [ ]   **RTN16c** `Connection#recoveryKey` is `Null` when a connection is explicitly `CLOSED` as connection state is not retained for connections closed at the request of the client
    * [ ]   **RTN16d** When a connection is successfully recovered, the `Connection#id` and `Connection#key` will be identical to the `id` & `key` of the connection that was recovered
    * [ ]   **RTN16e** If the `recover` option is missing or no longer valid when connecting to Ably, the client will connect anyway, but emit a `ConnectionStateChange` with an `errorReason`, and will additionally set the `Connection#errorReason` with an `ErrorInfo` object describing the failure
* [x]   **RTN17** Host Fallback
    * [x]   **RTN17a** All HTTP requests sent to Ably are fault-tolerant and will fallback to an alternative host if the default host is unreachable, or indicates that it is unserviceable with a 500 to 504 status code. This ensures that a client library is able to work around routing or other problems with the user’s closest datacenter. For example, if a connection attempt to `realtime.ably.io` fails because the default endpoint is unreachable or unserviceable, then the `Connection` manager should check if an internet connection is available by sending a request to our CDN `internet-up.ably-realtime.com/is-the-internet-up.txt` and looking for the text “yes” in the response. If the text “yes” is included in the response, then the the client library can assume it has a viable internet connection and should then automatically retry the connection against all the fallback hosts `[a-e].ably-realtime.com` in attempt to find an alternate healthy datacenter.
    * [x]   **RTN17b** The fallback behaviour only applies to the default `realtime.ably.io` endpoint; if either `host` or `environment` options are set, no fallback host is used.
    * [x]   **RTN17c** See the [default fallback hosts](https://github.com/ably/ably-java/blob/master/src/io/ably/transport/Defaults.java#L7) and the [fallback mechanism implemented in the Java ConnectionManager](https://github.com/ably/ably-java/blob/39f3f0226bd995bd6baffa1df47a0a4957d29c43/src/io/ably/transport/ConnectionManager.java#L428-L455) as an example.
* [ ]   **RTN18** Connection state change side effects:
    * [ ]   **RTN18a** When a connection enters the `DISCONNECTED` state, it will have no effect on the the channel states. Channels in the `ATTACHED` state will queue messages that are sent as soon as the connection is resumed
    * [ ]   **RTN18b** When a connection enters the `SUSPENDED` state, all channels will move to the `DETACHED` state. Channels in the `DETACHED` state should reject publishing of messages
    * [ ]   **RTN18c** When a channel enters the `FAILED` state, all channels will move to the `FAILED` state. Channels in the `FAILED` state should reject publishing of messages

**Comment by mattheworiordan** [comment]
Prioritisation of specs within this issue:

### High priority

* All ACK / NACK tests
* Multiple simultaneous connections
* Connection attributes
* `Connection#connect` + edge cases
* `Connection#close` + edge cases
* Connection opening failures
* Connection failures whilst connected and resuming state
* Connection state change side effects

### Medium priority

* Fallback hosts (needed to honour our 100% uptime guarantee)

### Lower priority

* Connection reoery

**Comment by marto83** [comment]
I'm closing this as it is not up to date with the spec
