### ISSUE TITLE
Unclear reason for error

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#102]
Customer reported this issue:

```
IO.Ably.AblyExceptionReason: Error executing request; Code: 500
Raw
IO.Ably.AblyHttpClient.<Execute>d__13.MoveNext()<c95c433cb01f489cbf383eb0b6a8850d>:0
IO.Ably.AblyRest.<ExecuteRequest>d__31.MoveNext()<c95c433cb01f489cbf383eb0b6a8850d>:0
IO.Ably.AblyRest.<ExecuteRequest>d__31.MoveNext()<c95c433cb01f489cbf383eb0b6a8850d>:0
IO.Ably.AblyRest.<ExecutePaginatedRequest>d__33<T>.MoveNext()<c95c433cb01f489cbf383eb0b6a8850d>:0
AgriSync.Services.AblySignaling.Subscribe()<d936c5c9102f4042be1dde0fd135935e>:0
System.Net.Http.HttpRequestExceptionAn error occurred while sending the request
null
System.Net.WebExceptionError getting response stream (ReadDone1): ReceiveFailure
System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)<24bd9c8f2e3e453bb9b46009c60603ed>:0
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<T, TResult> endFunction, Action<T> endAction, Task<TResult> promise, bool requiresSynchronization)<5745f3a5105e49509cf07723a87a4d8f>:0
System.Net.Http.HttpClientHandler.SendAsync()<6003905b2fe043dc938670cd9f58333b>:0
System.IO.IOExceptionUnable to read data from the transport connection: Connection reset by peer.
 ```

Unfortunately that stack trace does not make it clear what the issue is or what response it got from Ably.

**Comment by marto83** [comment]
it seems the error happens when trying to Authenticate the client and it's requesting a token. 
Most likely the connection dropped and was interrupted during the transmission. 
I had a look at the code and I've missed this error case from the retry logic. I'll add `ReceiveFailure` and publish a new version. 

Can you find out which version of the library is this affecting? 

I'll also add the version information to the error messages.

**Comment by NVentimiglia** [comment]
<package id="ably.io" version="0.8.4.2" targetFramework="monoandroid60" />

**Comment by NVentimiglia** [comment]
[Logs_Nvidia.txt](https://github.com/ably/ably-dotnet/files/1014505/Logs_Nvidia.txt)
[Logs_LG.txt](https://github.com/ably/ably-dotnet/files/1014504/Logs_LG.txt)

**Comment by marto83** [comment]
Thanks @NVentimiglia I'm going to investigate further today. Having logs is very helpful.

**Comment by marto83** [comment]
@NVentimiglia I went through the logs and couldn't see any Ably errors there. I've updated the code and pushed a new version to nuget (0.8.4.3). It will catch that error and retry the http call.

**Comment by mattheworiordan** [comment]
@NVentimiglia did you get a chance to try 0.8.4.3?

**Comment by NVentimiglia** [comment]
@mattheworiordan Ill do some more logging around authentication / poor connectivity and get back to you.

**Comment by mattheworiordan** [comment]
@NVentimiglia in most cases you will receive an error from the API, it would be useful if you log the complete details of that error along with a verbose log of the events leading up to it if possible.  Shout if we can do anything further to help debug this.

**Comment by caseyniemann** [comment]
@mattheworiordan @marto83 @NVentimiglia Post updating getting lots of 500 errors. 
IO.Ably.AblyExceptionReason: This awaiter is already in waiting state.; Code: 500
Raw
  at IO.Ably.Realtime.ChannelAwaiter.Wait (System.Action`2[T1,T2] callback) [0x00014] in <c95c433cb01f489cbf383eb0b6a8850d>:0 
  at IO.Ably.Realtime.RealtimeChannel.Attach (System.Action`2[T1,T2] callback) [0x0001e] in <c95c433cb01f489cbf383eb0b6a8850d>:0 
  at IO.Ably.Realtime.RealtimeChannel.Subscribe (System.Action`1[T] handler) [0x00012] in <c95c433cb01f489cbf383eb0b6a8850d>:0 
  at AgriSync.Services.AblySignaling+<Subscribe>c__async2.MoveNext () [0x00117] in <d936c5c9102f4042be1dde0fd135935e>:0

**Comment by marto83** [comment]
@caseyniemann I'm looking into it. 
Is this an error you can easily reproduce? If so it will be great to run it with debug logging to see the state of the library at that time.

**Comment by marto83** [comment]
@caseyniemann I managed to reproduce the issue. It is caused by multiple threads calling Attach on a single channel. 
I've updated the logic to make sure the first thread initiates the attach and the rest short circuit. 
I've created release 0.8.4.4 and it will show up in nuget shortly.

**Comment by caseyniemann** [comment]
Thanks Martin--we will test

**Comment by caseyniemann** [comment]
We got this in Dev on IOS.  with 8.5.5.  We are now testing 8.5.6.

WebSocket4Net.WebSocket.ClearTimer()
WebSocket4Net.WebSocket.FireClosed()
WebSocket4Net.WebSocket.OnClosed()
WebSocket4Net.WebSocket.client_Error(object sender, ErrorEventArgs e)
SuperSocket.ClientEngine.ClientSession.OnError(Exception e)
SuperSocket.ClientEngine.SslStreamTcpSession.OnDataRead(IAsyncResult result)
System.Net.LazyAsyncResult.Complete(IntPtr userToken)
System.Net.LazyAsyncResult.ProtectedInvokeCallback(object result, IntPtr userToken)
System.Net.LazyAsyncResult.InvokeCallback(object result)
Mono.Net.Security.AsyncProtocolRequest.StartOperation()
Mono.Net.Security.AsyncProtocolRequest.<StartOperation>b__17_0(object _)
System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(object state)
System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, object state, bool preserveSyncCtx)
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue.Dispatch()
ObjCRuntime.Runtime.ThreadPoolDispatcher(Func<TResult> callback)
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by marto83** [comment]
@caseyniemann that's weird. 8.5 doesn't have WebSokect4Net at all. Are you using https://www.nuget.org/packages/ably.io/0.8.5-beta7

**Comment by NVentimiglia** [comment]
@marto83 
0.8.4.6

We do have a new null ref on iOS
https://github.com/ably/ably-dotnet/issues/112
