### ISSUE TITLE
Signed assembly

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#103]
A customer in ticket 1890 has requested a signed version of our .NET assembly.

> I am using integration of Ably in my project which is signed assembly.
> It is throwing error of strong name assembly: Could not load file or assembly 'IO.Ably, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044). I resolved it using ildasm.  But there is same error at its dependencies assembly and it is not resolvable by ildasm.
> Can you provide me signed version of assembly to use in my application?

@marto83 what is involved in a providing a signed assembly for .NET?

**Comment by mattheworiordan** [comment]
@marto83 is this something we can do?

**Comment by marto83** [comment]
I'm traveling today and will get it sorted tonight when I'm back.

**Comment by marto83** [comment]
@mattheworiordan I've published version 0.8.4.5 which is signed. 
I found that one of our dependencies `Nito.AsyncEx` is not signed. So I tried in a sample up and it doesn't seem to be in issue. Can you ask the customer to try and if it doesn't work I'll find a way around it.

**Comment by marto83** [comment]
@mattheworiordan do you know if that's worked for the customer.

**Comment by mattheworiordan** [comment]
> @mattheworiordan do you know if that's worked for the customer.

Have asked the customer again.

**Comment by mattheworiordan** [comment]
From the customer @marto83:

> Now there is error message of Nito.AsyncEx.  
Could not load file or assembly 'Nito.AsyncEx, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)
I tried to update version of Nito.AsyncEx. to resolve it but still it is throwing same error.

**Comment by marto83** [comment]
cool. I suspected it even though I didn't get it myself. I'll get it sorted today and publish a new package.

**Comment by engenb** [comment]
FWIW I just pulled 0.8.4.5 and got the same error @mattheworiordan posted a couple hours ago.  rolling back to 0.8.4.4 resolved the issue.  could an option be to publish a different ably-signed nuget?

**Comment by marto83** [comment]
@mattheworiordan an @engenb I released a new version of the nuget package. I merged 3 of the dependencies so the only external dependency is msgpack.cli which is also signed. 

The new nuget package is version 0.8.4.6. Let me know if that fixes the issue.

**Comment by engenb** [comment]
@marto83 I updated to your new release and I am no longer getting that assembly load exception - thanks!
