### ISSUE TITLE
When a Channel Fails to Resume After Disconnection, a Detached Event isn't Fired

### ISSUE THREAD

**Issue by ddrinka** [ably/ably-dotnet#108]
When I had been experiencing regular disconnects, I found that 1 in 30 or so connections would fail to resume with an error like this: `Unable to recover connection: not found (<SESSION ID>); Code: 80008; HttpStatusCode: (400)BadRequest`

This is an issue itself, but one I'm not able to reproduce often enough to even request support on.

This present issue is that when the connection resume failed, a Channel Detached event was not fired.  I was subscribed to all Connection and Channel updates, and received the Connection update informing me I was reconnected, but never received a Channel Detached update informing me I needed to resubscribe to the channel.

I'm attempting to follow the guidance in https://blog.ably.io/v0-9-of-our-client-libraries-simplifying-channel-lifecycle-management-c727f9060a8b but without the Detached event it doesn't work.

See internal support ticket 1923 for a debug log of this issue.

**Comment by marto83** [comment]
@ddrinka sounds like a bug. I'll try and look into it asap.

**Comment by marto83** [comment]
@ddrinka I found the bug where I wasn't correctly checking when the connection is not successfully resumed. Before I release a new version I'd like to double check with a couple of test cases. 

@mattheworiordan what is the best way to make sure a connection fails to resume.

**Comment by mattheworiordan** [comment]
> @mattheworiordan what is the best way to make sure a connection fails to resume.

You simply reconnect with an invalid `connectionKey`, so force that to change. Don't use an invalid format though, try and use a key that matches the format of a valid key, but simply does not exist.

**Comment by marto83** [comment]
I see - I was close. I tried last night by removing a couple of letters of the key but I must have invalidated it :).

**Comment by marto83** [comment]
@ddrinka I reproduced the bug and confirmed it is fixed. I've pushed beta7 to nuget as well.
