### ISSUE TITLE
RealtimeClient

### ISSUE THREAD

**Issue by yavor87** [ably/ably-dotnet#11]
* [x]   **RTC1** Supports all the same `ClientOptions` as the `RestClient` in addition to:
    * [x]   **RTC1a** `echoMessages` boolean is true by default. If false, it prevents messages originating from this connection being echoed back on the same connection
    * [x]   **RTC1b** `autoConnect` boolean is true by default. If true, as soon as the client library is instanced, it will connect to Ably. If false, the client library will wait for an explicit `Connection#connect` to be called before connecting
    * [x]   **RTC1c** `recover` string, when set, will attempt to recover the connection state of a previous connection
    * [x]   **RTC1d** `realtimeHost` string, when set, will modify the realtime endpoint host used by this client library
    * [x]   **RTC1e** `environment` string, when set, will modify both the REST and realtime endpoint hosts by prefixing the environment to the default endpoint host with a hypen delimiter. For example, a `RealtimeClient` with an `environment` of “sandbox”, would use “sandbox-rest.ably.io” as the `restHost` and `sandbox-realtime.ably.io` as the `realtimeHost`
* [x]   **RTC2** `RealtimeClient#connection` attribute provides access to the underlying `Connection` object
* [x]   **RTC3**`RealtimeClient#channels` attribute provides access to the underlying `Channels` object
* [x]   **RTC4**`RealtimeClient#auth` attribute provides access to the `Auth` object that was instanced with the `ClientOptions` provided in the `RealtimeClient` constructor
* [x]   **RTC5**`RealtimeClient#stats` function:
    * [x]   **RTC5a** Proxy to `RestClient#stats` presented with an async or threaded interface as appropriate
    * [x]   **RTC5b** Accepts all the same params as `RestClient#stats` and provides all the same functionality
* [x]   `RealtimeClient#time` function:
    * [x]   **RTC5c** Proxy to `RestClient#time` presented with an async or threaded interface as appropriate

**Comment by mattheworiordan** [comment]
Prioritisation notes:

* `recover` used to recover a connection from a another client not a priority
* `stats` is nice to have, but lower priority. Assuming you have a generic way of proxying Realtime to REST requests though, this should be very easy, see https://github.com/ably/ably-dotnet/blob/5253602b3cdb13b09fc04b30abbb496ede994b88/src/Ably/RestClient.cs#L475-L478
