### ISSUE TITLE
Unity and IL2CPP build

### ISSUE THREAD

**Issue by jbaessens** [ably/ably-dotnet#1110]
Hi,
It's impossible to use Ably with a IL2CPP build it always crashs at Init with this error : 

NullReferenceException: Object reference not set to an instance of an object.
  at IO.Ably.IoC.get_MobileDevice () [0x00000] in <00000000000000000000000000000000>:0 
  at IO.Ably.AblyRealtime..ctor (IO.Ably.ClientOptions options) [0x00000] in <00000000000000000000000000000000>:0 
  at Ably.Start () [0x00000] in <00000000000000000000000000000000>:0 

It works perfectly well with a Mono backend build. I use Unity 2020.3 currently.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1540) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
@jbaessens Can you try setting managed stripping level to low or disabled. You can check https://docs.unity3d.com/Manual/ManagedCodeStripping.html for more information.

**Comment by jbaessens** [comment]
@sacOO7  thanks for this quick feedback! In IL2CPP you can't disabled it totally and i'm already in Low. it's the default behaviour.

**Comment by sacOO7** [comment]
Actually, I was going through https://github.com/ably/ably-dotnet/issues/751. Seems, there is a bug in the latest version of unity. Can you try setting it to `medium`, it's mentioned to be working for a user.

**Comment by jbaessens** [comment]
It seems to change nothing unfortunatly!

**Comment by jbaessens** [comment]
For information, I had problems with NewtonSoft library conflict so I decided to build the 1.2.7 binaries by myself with a different version of NewtonSoft. So i use these "custom" binaries to be able to launch my app.

**Comment by sacOO7** [comment]
Hi @jbaessens can you use newtonsoft binaries from here https://github.com/sac-fork/ably-unity/tree/main/Assets/Ably/Plugins. We are using it from the project https://github.com/jilleJr/Newtonsoft.Json-for-Unity.  Also, you can try using other DLLS in the folder in case they are missing.

**Comment by jbaessens** [comment]
I think it was my first try but in this case I have conflict with the NewtonSoft includes in Unity. But will have a try again.

**Comment by sacOO7** [comment]
If newtonsoft has conflict, please follow [Disable Assembly Validation Error](https://github.com/ably/ably-dotnet/blob/1cff0316a265aef09bd0bfcce5796d94399a60c5/unity/README.md#disable-assembly-validation-error)

**Comment by jbaessens** [comment]
@sacOO7  this option is available only in editor in the IL2CPP mode ;-)

**Comment by jbaessens** [comment]
@sacOO7  So, I used the project from here : https://github.com/sac-fork/ably-unity/ and  Newtonsoft DLLs v12 from there https://github.com/jilleJr/Newtonsoft.Json-for-Unity.
Project is on Windows Platform Unity 2020.3.13f1 :
build with Mono -> OK !  
Build with IL2CPP -> Null reference on IO.Ably.IoC.get_MobileDevice

**Comment by sacOO7** [comment]
@jbaessens thanks for the information! So, I presume the changes are working for you now. Let me know if you are facing any issues with the code (mostly related to newtonsoft serialiazation/deserialization)

**Comment by sacOO7** [comment]
Thanks for the information! May I know what is the error associated with channels?

**Comment by jbaessens** [comment]
@sacOO7 , Not really an error it juste does nothing.  i have this log when I try to get the channel : 
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Ably:<Connect>b__5_0(ConnectionStateChange)
System.Action`1:Invoke(T)
IO.Ably.<>c__DisplayClass25_1:<Emit>b__3()
UnityEngine.AndroidJavaRunnable:Invoke()
System.AsyncCallback:Invoke(IAsyncResult)
UnityEngine.WorkRequest:Invoke()
UnityEngine.UnitySynchronizationContext:Exec()

And after that I can't send or receive something.

**Comment by sacOO7** [comment]
Hey, where are you exactly creating the connection to the server? Are we sure we are not blocking the main thread and things are running in the background? You can check https://github.com/Cysharp/UniTask library to run code easily in the background.

**Comment by jbaessens** [comment]
Below, you can find my test script. Which is pretty basic and will not block anything?  Have you tried to reproduce on your side? 

`using System.Collections;
using System.Collections.Generic;
using System;

using UnityEngine;
using UnityEngine.UI;

using IO.Ably;
using IO.Ably.Realtime;

public class Ably : MonoBehaviour
{
    AblyRealtime ably;
    public Text errorText;
    public Image image;

    private Color color;
    private string text;

    void Connect()
    {
        text = "";
        color = Color.yellow;

            var options = new ClientOptions();
            options.Key = "apHtmw.imt-cg:ecr65VacPyKQbrtKW3oY93vojzNx6YjSD58o-E7Nfrs";
            // this will disable the library trying to subscribe to network state notifications
            options.AutomaticNetworkStateMonitoring = false;
            // you can also turn on if you need to update the UI directly from channel subscription handlers
            options.CaptureCurrentSynchronizationContext = true;

            ably = new AblyRealtime(options);
            ably.Connection.On(ConnectionEvent.Connected, args =>
            {
                Debug.Log("Connected to Ably!");
                color = Color.green;
                text = "Connected to Ably!";
            });

            var channel = ably.Channels.Get("notifications");
            channel.Subscribe(message =>
            {
                Debug.Log("Received a greeting message in realtime: " + message.Data);
                color = Color.blue;
                text = "Received a greeting message in realtime: " + message.Data;
            }); 

    }

    void Update()
    {
        errorText.text = text;
        image.color = color;

        if (Input.GetKeyDown(KeyCode.RightArrow))
        {
            Connect();
        }
        
        if (Input.GetKeyDown(KeyCode.Space))
        {
            var channel = ably.Channels.Get("notifications");
            channel.Publish("greeting", "hello!");
        }
    }
}
`

**Comment by tomkirbygreen** [comment]
> Below, you can find my test script. Which is pretty basic and will not block anything? Have you tried to reproduce on your side?
> 
> `using System.Collections; using System.Collections.Generic; using System;
> 
> using UnityEngine; using UnityEngine.UI;
> 
> using IO.Ably; using IO.Ably.Realtime;
> 
> public class Ably : MonoBehaviour { AblyRealtime ably; public Text errorText; public Image image;
> 
> ```
> private Color color;
> private string text;
> 
> void Connect()
> {
>     text = "";
>     color = Color.yellow;
> 
>         var options = new ClientOptions();
>         options.Key = "apHtmw.imt-cg:ecr65VacPyKQbrtKW3oY93vojzNx6YjSD58o-E7Nfrs";
>         // this will disable the library trying to subscribe to network state notifications
>         options.AutomaticNetworkStateMonitoring = false;
>         // you can also turn on if you need to update the UI directly from channel subscription handlers
>         options.CaptureCurrentSynchronizationContext = true;
> 
>         ably = new AblyRealtime(options);
>         ably.Connection.On(ConnectionEvent.Connected, args =>
>         {
>             Debug.Log("Connected to Ably!");
>             color = Color.green;
>             text = "Connected to Ably!";
>         });
> 
>         var channel = ably.Channels.Get("notifications");
>         channel.Subscribe(message =>
>         {
>             Debug.Log("Received a greeting message in realtime: " + message.Data);
>             color = Color.blue;
>             text = "Received a greeting message in realtime: " + message.Data;
>         }); 
> 
> }
> 
> void Update()
> {
>     errorText.text = text;
>     image.color = color;
> 
>     if (Input.GetKeyDown(KeyCode.RightArrow))
>     {
>         Connect();
>     }
>     
>     if (Input.GetKeyDown(KeyCode.Space))
>     {
>         var channel = ably.Channels.Get("notifications");
>         channel.Publish("greeting", "hello!");
>     }
> }
> ```
> 
> } `

Many thanks for the sample code. @sacOO7 and I will try and reproduce this locally using your code. I've reached out to @marto83 to see if this is akin to anything he's experienced before.

**Comment by jbaessens** [comment]
@tomkirbygreen Nice, thank you !

**Comment by jbaessens** [comment]
@tomkirbygreen  Visual Studio 2019 , do you want a zip of my project?

**Comment by tomkirbygreen** [comment]
> @tomkirbygreen Visual Studio 2019 , do you want a zip of my project?

2019, Roger that. Yes please re: ZIP.

**Comment by jbaessens** [comment]
This is it in the well named "New scene" scene. :)
[ably-unity-main_IL2CPP.zip](https://github.com/ably/ably-dotnet/files/8014501/ably-unity-main_IL2CPP.zip)

**Comment by tomkirbygreen** [comment]
> This is it in the well named "New scene" scene. :) [ably-unity-main_IL2CPP.zip](https://github.com/ably/ably-dotnet/files/8014501/ably-unity-main_IL2CPP.zip)

Thank you kind sir! @sacOO7 can you make sure you use the attached ZIP please when trying to reproduce this at your end please. I'll do the same.

**Comment by sacOO7** [comment]
Hi @jbaessens, we were able to reproduce the issue from our side. It seems, the issue is caused by `managed code stripping`, although set to `low`, it's stripping some part of the ably reflection code. Can you add `link.xml` file under `Assets` with the following content? We have tested the change and seems to be working for us. It will make sure, no part of `ably.dll` is stripped during IL2CPP build. 

```
<linker>
    <assembly fullname="IO.Ably" preserve="all" />
</linker>
```
We have created an active issue to include it as a part of Unity Package 
https://github.com/ably/ably-dotnet/issues/1113

**Comment by jbaessens** [comment]
Oh nice @sacOO7  Thanks so much !  Just have a test and it works!  Will be able to explore the ably world now !
