### ISSUE TITLE
Update release notes with .NET 6 status

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-dotnet#1116]
Update the `README.md` release notes with the current .NET 6 status.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1592) by [Unito](https://www.unito.io)

**Comment by tomkirbygreen** [comment]
> @tomkirbygreen So what _is_ the current status of .net 6 support? : )
> 
> Just looking through the code it seems its still not supported, but is there plans on that changing soon? I'm considering Ably for a MAUI app

@J-Swift The .NET 6 status currently is that I have successfully run the test suite against RTM .NET 6 parts but can't upgrade the projects until we get proper versioning. Background: currently the Ably libraries have a version number that corresponds to the version of the Ably spec they support. This makes it impossible to safely make changes and still work with package management etc. We are _actively_ working on the versioning thing (basically the .NET library will adopt proper / standard .NET versioning). In the mean time, if you work from source rather than `nuget` you can evolve the project / solution files as needed and should be able to move forward. Please do let me know if you run into issues that you believe correlate with .NET 6.

**Comment by tomkirbygreen** [comment]
Related -> [deprecate `.NET 3.1`](https://github.com/ably/ably-dotnet/issues/1153).

**Comment by sacOO7** [comment]
TODO

- [x] Fix tests
- [x] Fix github workflow
- [x] Add agent headers
- [ ] Update feature spec file.
- [ ] Update build script README, check for other README updates
