### ISSUE TITLE
Investigate CI failure

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-dotnet#1126]
@sacOO7 reports that CI is now routinely failing. As no code has gone in since it was last green this _may_ be down to a change in a dependency.

Reproduce and analyse.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1609) by [Unito](https://www.unito.io)

**Comment by tomkirbygreen** [comment]
Findings thus far, given a new clone of the repo:

.NET Standard builds fine on Mac OS 12.2.1
.NET Standard builds fine on Windows 10 21H2 build 19044.1466
.NET Framework (all release targets) build fine on Windows 10 21H2 build 19044.1466

**Comment by sacOO7** [comment]
I think we can close this issue now, since it's been fixed. Thanks for the PR.

**Comment by tomkirbygreen** [comment]
Now fixed.
