### ISSUE TITLE
Populate message/presencemessage Id, ConnectionId, Timestamp

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-dotnet#113]
Hey @marto83 . Customer reporting that `message.Id` and `message.ConnectionId` are null for messages received over realtime.

Looking at the lib and the spec, it looks like the requirement for how those fields should be populated was only added to the spec after 0.8 — https://github.com/ably/docs/pull/143/commits/f5b579a0c2b35cb4ee58137cf3a1bb24bbcfe51d — which explains why it isn't implemented in the .net lib. But our docs (even the [0.8 docs](https://www.ably.io/documentation/realtime/versions/v0.8/channels-messages#message)) assume it is populated (and most other 0.8 client libs populated it), so I think it was a mistake for me to add it to the 0.9 spec rather than as a clarification to 0.8 -- sorry, my fault.

In any case, it's a pretty simple requirement, and we have a customer who needs it -- any chance it could be implemented in the .net lib? Thanks :)

**Comment by marto83** [comment]
I'll make sure they are set and release a new version some time tomorrow. I'll link it to this issue.

**Comment by SimonWoolf** [comment]
Thanks Martin!

**Comment by ndastur** [comment]
Thank you Guys

**Comment by marto83** [comment]
I still need to release a new nuget package and merge into the branch for 0.8.5. Will update once that's done.

**Comment by marto83** [comment]
@ndastur and @SimonWoolf I just uploaded 0.8.4.6 and 0.8.5-beta8 to nuget that have a fix for this issue.
