### ISSUE TITLE
RealtimePresence possibly broken

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-dotnet#114]
Customer reports that with .NET, using the AblyRealtime client, they only ever see one member present (presumably themselves) even when there are definitely multiple on the channel (as seen from other client libs or the AblyRest client).

Looking at the lib implementation, I thought at first it was because [`waitForSync` isn't implemented yet](https://github.com/ably/ably-dotnet/blob/e76f6c94df952171a38bc84a2f5cfd1ac1a42e6f/src/IO.Ably.Shared/Realtime/Presence.cs#L51), but customer reports that they still only see one member if they add a delay before getting presence.

It's still possible that it's user error of some kind. But hard to be sure, because looking at the specs, there's only one test for GetAsync with the realtime client, and that only checks for a single member (itself), which isn't inconsistent with the report.

So would be nice if we could implement `waitForSync`, and then have a proper presence test where a couple of clients enters, then a different client attaches, gets presence, and sees the first two clients, so we can know for sure if the reported behaviour is a client lib bug or user error.

**Comment by marto83** [comment]
Would you be able to get the customer to enable the debug logging. We can see what happens to the presence messages when they arrive. We've had a few people using it before without issues. I'll double check it and let you know.

If waitForSync is needed I can prioritize it and get it implemented in the next couple of weeks.

**Comment by SimonWoolf** [comment]
Fair enough. I've asked him for a debug log and to post it directly into this issue.

**Comment by jeraldAR** [comment]
Hi @marto83,

This is what I get when trying to get all presence members in our channel. I am developing an application in WPF using Ably.io Latest prerelease 0.8.5-beta7. A workaround to get this working for me is to subscribe to the presence and handle each member that way, but I would rather use the GET method of the presence as expected by getting all users. 

Thanks for the help guys!

```
GetOptions options = new GetOptions();
options.WaitForSync = true;

var presence = await AblyHelper.Instance.channelTeam.Presence.GetAsync(options);
List<PresenceMessage> members = presence.ToList();
```

+		this	{Sneek_Desktop.MainWindow}	Sneek_Desktop.MainWindow
+		options	{IO.Ably.Realtime.GetOptions}	IO.Ably.Realtime.GetOptions
+		presence	{System.Linq.Enumerable.WhereArrayIterator<IO.Ably.PresenceMessage>}	System.Collections.Generic.IEnumerable<IO.Ably.PresenceMessage> {System.Linq.Enumerable.WhereArrayIterator<IO.Ably.PresenceMessage>}
+		members	Count = 1	System.Collections.Generic.List<IO.Ably.PresenceMessage>

**Comment by marto83** [comment]
@jeraldAR I did a test with 2 clients and 250 presence messages. The second client will get incomplete results depending on when it called Presence.GetAsync().

I'm going to get this fixed over the next couple of weeks and keep you updated.

**Comment by jeddawson** [comment]
I've been working around this issue in my implementation for a while, but wanted to provide some feedback here and offer my help in resolving the underlaying issues :)

My use case in a nutshell: I have a console app that is consuming events from an Azure Event Hub. When the events meet certain conditions, we want to let users know about the changes via Ably but only when there are users on the respective channels. My work around is **very naive**, but hopefully it helps reveal the issue.

Before attaching to each channel, I set up a Presence subscription like:

```
channel = AblyRt.Channels.Get(channelName);
channel.Presence.Subscribe((msg) => {
    switch (msg.Action)
    {
        case PresenceAction.Present:
        case PresenceAction.Enter:
            if (ChannelMembers.ContainsKey(msg.MemberKey))
            {
                var user = ChannelMembers[msg.MemberKey];
                if (user.Action == PresenceAction.Present || user.Action == PresenceAction.Enter)
                {
                    //we've already counted this user
                    break;
                }
            }
            var pcount = 1 + (ChannelPresence.ContainsKey(channel.Name) ? ChannelPresence[channel.Name] : 0);
            ChannelPresence[channel.Name] = pcount;
            ChannelMembers[msg.MemberKey] = msg;
            break;
        case PresenceAction.Leave:
            var lcount = (ChannelPresence.ContainsKey(channel.Name) ? ChannelPresence[channel.Name] : 0) - 1;
            ChannelPresence[channel.Name] = lcount >= 0 ? lcount : 0;
            ChannelMembers[msg.MemberKey] = msg;
            break;
        case PresenceAction.Absent:
        case PresenceAction.Update:
        default:
            //nothing to do here
            break;
    }
    Console.WriteLine("Presence action {0} for member {1}", msg.Action, msg.MemberKey);
    CheckPresence(channel).Wait();
});
    
await channel.AttachAsync();
```

`ChanelPresence` and `ChannelMembers` are global concurrent dictionaries:
`private static readonly ConcurrentDictionary<string, int> ChannelPresence = new ConcurrentDictionary<string, int>();
        private static readonly ConcurrentDictionary<string, PresenceMessage> ChannelMembers = new ConcurrentDictionary<string, PresenceMessage>();`

To see how things diverge I added:

```
public static async Task CheckPresence(IRealtimeChannel channel)
{
    var presence = 0;
    ChannelPresence.TryGetValue(channel.Name, out presence);
    var ablyPresence = await channel.Presence.GetAsync();
    var presenceMessages = ablyPresence as PresenceMessage[] ?? ablyPresence.ToArray();
    if(presence != presenceMessages.Count()){
        Console.WriteLine("Mismatch. {0} local. {1} channel.", presence, presenceMessages.Count());
    }
    else
    {
        Console.WriteLine("Matched! {0} users", presence);
    }
}
```

So onto the actually helpful bits:
Connecting to a channel with 0 members, then 1 member enters:
`Matched! 0 users
Presence action Enter for member test-user2:zF2LhPBpIx
Matched! 1 users
Presence action Present for member test-user2:zF2LhPBpIx
Mismatch. 1 local. 0 channel.
`
As you can see, things are good to start then good after the enter action, but as soon as the present action comes in we're out of sync. One member is still present, but `channel.Presence.GetAsync()` is giving us an empty list.

Unsurprisingly, the same issue arrises when attaching to a channel that already has members present:
`Presence action Present for member test-user2:zF2LhPBpIx
Mismatch. 1 local. 0 channel.
`

If you'd like I can take a stab at resolving this and open a PR 👍
