### ISSUE TITLE
Channel didn't attach within the default timeout; Code: 50000, Intermittent

### ISSUE THREAD

**Issue by jeraldAR** [ably/ably-dotnet#115]
Hi,

I notice that at times I get "Channel didn't attach within the default timeout; Code: 50000". This happens when I am trying to get a specific channel and the way I am able to reproduce this is to stop/start debugging my WPF app. I saw that there are others with this problem, but they were back in 2016 and doesn't really have a workaround for this. Any help is appreciated. Workaround maybe to try to get the channel again if statechanges to Failed.

**Comment by mattheworiordan** [comment]
Spoke with customer and advised that they should have a read of https://www.ably.io/documentation/realtime/versions/v0.8/connection#handling-failures and make sure v0.8 of the documentation is selected.  Also, for us to debug the root cause of the failure, we would need verbose logs, see https://support.ably.io/support/solutions/articles/3000063743-guide-information-we-need-to-help-you-diagnose-problems

**Comment by jeraldAR** [comment]
Hi @mattheworiordan,

So I tried the suggestion you offered on handling failures, but now getting a new error dealing with {"Reason: This awaiter is already in waiting state.; Code: 500"} .

This may be similar to https://github.com/ably/ably-dotnet/issues/102 and can always reproduce whenever I try to reattach my channel. I am also trying to get multiple channels at once. What do you think is the best solution to this?

**Comment by mattheworiordan** [comment]
>  but now getting a new error dealing with {"Reason: This awaiter is already in waiting state.; Code: 500"} .

Mmm, that sounds like a bug in the lib.  Please confirm which exact version of the library you are using when receiving this error.

> I am also trying to get multiple channels at once. What do you think is the best solution to this?

Sorry, I am not following you.  If you want to get multiple channels, you can just instance them each separately i.e. 

```
var chan1 = Ably.Channels.Get('chan1');
var chan2 = Ably.Channels.Get('chan2');
```

Am I misunderstanding what you mean?

**Comment by marto83** [comment]
@jeraldAR 

Which version of the library are you using?
I've recently added some fixes in the latest beta to help with Attach failures. So for example, if a channel fails to attach it will move back to Initialising state which means you can continue to publish messages to the channel and they will be queued and sent when it becomes attached. Also reattaching will happen automatically.

For the older versions, you need to make sure that the attach completes successfully. You can either do 
`var result = await channel.AttachAsync();` and then check `result.IsSuccess && result.Value` (in the future newer versions will throw an exception if attach fails). The other option is to pass a callback to `channel.Attach` or to subscribe to `channel.On(ChannelState.Attached, change =>  { /* Do stuff here */});` 

It is also good practice to make sure if the connection is dropped for any reason you reattach all channels when it comes back online. 
```
client.Connection.On(ConnectionState.Connected, delegate
{
    foreach(var c in client.Channels)
        c.Attach();
});
```

Hope this helps

**Comment by jeraldAR** [comment]
Hi @marto83,

I am currently using 0.8.4.7. I can't install the beta9 build due to dependency errors with MsgPack.Cli V0.8.1 and Nito.AsyncEx V4.0.1. 

However, for some reason I am not getting this error anymore.

Also, I did add reattach failsafes on channels as well. So far so good. 

Thanks again @marto83 and @mattheworiordan

**Comment by marto83** [comment]
what is the issue with the Nito.AsyncEx library. I know that MsgPack has an issue with UWP apps.

**Comment by marto83** [comment]
@jeraldAR I updated the packages for Nito.AsyncEx and MsgPack in 0.8.5 beta14. Can you please try it and let me know if you still have the same issue.

**Comment by mattheworiordan** [comment]
@jeraldAR did `0.8.5 beta14` fix the issue?

**Comment by jeraldAR** [comment]
Hey Matt,

Just saw this now. I will give it a try today and will update you in a bit.

**Comment by marto83** [comment]
@jeraldAR beta14 has another issue. Please try 0.8.5 beta 18. It's the current stable build.

**Comment by withakay** [comment]
@jeraldAR Did 0.8.5 beta 18+ resolve your issues?

**Comment by jeraldAR** [comment]
Sorry for the delay. I haven't had much time working on our windows version. Been currently working on iOS. Ill let you know over the weekend.

**Comment by mattheworiordan** [comment]
@jeraldAR any update?
