### ISSUE TITLE
Failure of history API call means channels no longer attach

### ISSUE THREAD

**Issue by ndastur** [ably/ably-dotnet#116]
I have just come across a strange bug. Due to a bug in my own code I was calling the History API with a start Date preceding 01-01-1970 this resulted in an exception which I catch... no problem so far.

But when I get a channel and try Attach. The Attach fails. The error seems to be 
```Unexpected error :Reason: Unable to publish in detached or failed state; Code: 40000; HttpStatusCode: (400)BadRequest; Code: 50000```

**Comment by mattheworiordan** [comment]
Hi @ndastur.  That's odd as I would imagine a history request should have no bearing on the channel state.  

Can you describe the steps to reproduce please?

**Comment by ndastur** [comment]
I know...

1) Start the ably client
2) In ablyRealtime.Connection.On(ConnectionState.Connected, async args => do a call to the history API using a Start parameter DateTime of 1969-01-01
3) The history call will fail
4) Get a channel with a completely different "name". No sure if it's relevant but the names are all in the same namespace. i.e. chat:
5) The AttachAsync fails

**Comment by mattheworiordan** [comment]
Ok, thanks @ndastur. We'll write a test and then get a fix out.

**Comment by marto83** [comment]
@ndastur I got a test to reproduce it. 
by passing the `async state => history call` you pass an async void method which silently fails and takes down the ConnectionManager thread so even though the Attach message comes back there is no one to welcome it. 

It won't be simple to fix. Thanks for finding it.

**Comment by marto83** [comment]
@ndastur That's fixed in the latest beta.

**Comment by ndastur** [comment]
Ty. I'll try it out

**Comment by ndastur** [comment]
Hi @marto83 is the latest beta on NuGet yet. I couldn't find an update

**Comment by marto83** [comment]
it is but nuget thinks it is not the latest. 
Try with this `Install-Package ably.io -Version 0.8.5-beta14 -Pre`

**Comment by ndastur** [comment]
Okay. That might explain why the version I am using is "so" unstable cf what I thought was just 3 issues to sort out... I was on beta 9

**Comment by mattheworiordan** [comment]
@ndastur out of interest, does `0.8.5-beta14 -Pre` fix the issue?

**Comment by ndastur** [comment]
hi @mattheworiordan I haven't been able to test as 0.8.5-beta14 depends on the alpha version of Nito.AsyncEx and so broke my build. I wasn't keen on a refactor of my code to an alpha package and there were too many changes to my code base for it to be a quick test. I have opened an issue to ask why the new version depends on an alpha package

**Comment by marto83** [comment]
@ndastur I'm going to close this. Please feel free to reopen it if this reappears.
