### ISSUE TITLE
AttachAsync() doesn't timeout on connection state changes

### ISSUE THREAD

**Issue by ndastur** [ably/ably-dotnet#117]
If there happens to be a connection state change whilst awaiting a AttachAsync() call the call never times out

**Comment by mattheworiordan** [comment]
@ndastur can you show us an example of how to reproduce this please?

**Comment by ndastur** [comment]
I am not sure what to do in order to reproduce reliable as it requires connection state changes to be forced.
If you can get the ably into a suspended connection state then call AttachAsync.
Get the connection to connect but then disconnect almost immediately.
Allow connection to re-connect
At this point despite a stable connection the channel never goes into an Attached state and the call does not timeout
I have watched this happen due to my poor broadband today ;) But maybe the OSX network conditioner would do the same.

**Comment by mattheworiordan** [comment]
Ok, thanks, that should be enough for us to write a test and reproduce.

**Comment by marto83** [comment]
@ndastur which version are you using

**Comment by ndastur** [comment]
Latest nugent release I think 0.8.4.....

**Comment by marto83** [comment]
@ndastur just FYI. I've managed to replicate the bug and will get it fixed tomorrow. 

I'm working on a fix in 0.8.5. Is it possible for you to upgrade to the latest beta?

**Comment by ndastur** [comment]
Thank you @marto83. I can use the 0.8.5 beta. But do you have a timeline on the stable version of 0.8.5 as we need to release a production ready product at the end of August.

**Comment by marto83** [comment]
@ndastur the main reason for 0.8.5 is to have a .net standard library. For that I had to implement another Websocket transport based on the MS WebSockets library. However, with the help of another client we discovered there is a bug with Xamarin on iOS that stops the new transport to connect so I had to put back the WebSocket4Net transport as well. So now you have a choice between the two. Other than that 0.8.5 has a lot of small fixes around channels attaching and detaching. 

If will be great to try with the new Transport factory but you can continue to use it with the old on by passing the following `ClientOptions`

```
 var options = new ClientOptions();
 options.TransportFactory = new WebSocketTransport.WebSocketTransportFactory();
 var client = new AblyRealtime(options);
```

**Comment by ndastur** [comment]
@marto83 does that mean I should do that for iOS clients or only if I experience a problem??

**Comment by marto83** [comment]
For iOS clients we automatically force it to use the WebSocket4Net client
because of a Xamarin bug.

**Comment by ndastur** [comment]
Thanks @marto83 . In that case presumably, the only way to "try" the new transport is to set a client option on iOS. Is it correct that on Android the new transport is the default? And so the comment above, 2 days ago, only applies to Android?

**Comment by marto83** [comment]
> In that case presumably, the only way to "try" the new transport is to set a client option on iOS.

Yes.

> Is it correct that on Android the new transport is the default?

Yes

So if you are not happy with the new transport on Android you can switch back to the previous one.
I've got 3 more issues to close and will remove the beta label.

**Comment by ndastur** [comment]
@marto83 brilliant news. I'll persevere with 0.8.5 then

**Comment by ndastur** [comment]
@marto83 just to make you aware. Having switched to 0.8.5 beta I am getting a bunch of new crash types reported. I have pasted the HockeyApp summaries below. I hope this helps.

1)
Reason: 
android.runtime.JavaProxyThrowable: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> IO.Ably.AblyException: Reason: The current state [Failed] does not allow messages to be sent.; Code: 500

Location: 
ConnectionManager.Send(IO.Ably.Types.ProtocolMessage message, System.Action`2[T1,T2] callback, IO.Ably.ChannelOptions channelOptions)

2)
Reason: 
android.runtime.JavaProxyThrowable: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.WebSockets.WebSocketException: The WebSocket is in an invalid state ('Closed') for this operation. Valid states are: Open, CloseReceived

Location: 
ClientWebSocket.EnsureWebSocketState(System.Net.WebSockets.WebSocketState[] validStates)

3)
Reason: 
android.runtime.JavaProxyThrowable: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.Sockets.SocketException: Network subsystem is down

Location: 
Socket.Send(System.Byte[] buffer, System.Int32 offset, System.Int32 size, System.Net.Sockets.SocketFlags socketFlags)

**Comment by marto83** [comment]
Thanks Neville,
3 is a valid exception when the connection is down. I need to make sure I
catch it.

2 is a bug and will get it sorted.
1 could be a valid case. It will help if you run ably in debug mode for a
bit to see what happens around the crashes.

Also I'm away from a computer this week but will jump on it next Monday.

**Comment by ndastur** [comment]
@marto83 thank you. Can you post how to set debug mode in the .Net client. Tried 
```,LogLevel = LogLevel.Debug``` in clientoptions but doesn't seem to make any difference to output

**Comment by marto83** [comment]
@ndastur 
When you set the log level you also need to implement a logSink otherwise Ably just writes to Debug messages. 
This is just a class that implements `ILoggerSink`. Once you have that at startup you need to do the following
`IO.Ably.Logger.LoggerSink = new YourLoggerSink();`

I've also updated the latest beta version with more error handling around the websocket layer. Let me know if this resolves the above issues you are having.

**Comment by marto83** [comment]
@ndastur please try the latest beta 0.8.5-beta18. I wrote a test android app to try it out. I'm planning to promote this version to 0.8.5 in a couple of days.

**Comment by ndastur** [comment]
Thank you @marto83 . We'll take a look at this and test

**Comment by withakay** [comment]
@ndastur did 0.8.5-beta18 fix the issues you were having?

**Comment by mattheworiordan** [comment]
@ndastur one final query to see if this is still an issue?  We believe we fixed this some time back.
