### ISSUE TITLE
Unity: Investigate inability to select GitHub as SCM

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-dotnet#1173]
sacOO7 Reports that he's not able to set GitHub as the external SCM when using Unity Cloud Build.

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-2377) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Currently able to configure the Dotnet repo as SCM in unity cloud build configuration. 
So, marking the issue as resolved 👍
