### ISSUE TITLE
Request mac does not match

### ISSUE THREAD

**Issue by arash01** [ably/ably-dotnet#118]
Hi,

When I'm trying to subscribe to a channel, it returns this error: "Request mac does not match"

Authentication is by TokenRequest which is been created by PHP code. It works fine with Javascript but not with Xamarin (Dot net sdk).

Also changing LogLevel = LogLevel.Debug in ClientOptions doesn't print out logs, therefore I can't provide logs at this stage.

My code:

`
try
            {
                var realtime = new AblyRealtime(new ClientOptions
                {
                    LogLevel = LogLevel.Debug,
                    AuthCallback = async (TokenParams arg) => await FetchTokenRequest()
				});

                var channelName = "CHANNEL_NAME";
				var channel = realtime.Channels.Get(channelName);

                channel.Attach((bool success, ErrorInfo error) =>
                {
                    Debug.WriteLine(error);
                });

				channel.Subscribe("update", (Message obj) =>
				{
                    Debug.WriteLine(obj.Data);
				});
            }
            catch (AblyException ex)
            {
                Debug.WriteLine(ex);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
            }
`

**Comment by marto83** [comment]
Hi @arash01,
Can you send me the code for FetchTokenRequest()?
The issue is most likely when the tokenrequest / tokendetails is de/reserialized and sent back to ably.

**Comment by arash01** [comment]
`async Task<TokenRequest> FetchTokenRequest()
        {
	var tokenRequestData = await GetAblyTokenRequestFromServer<Dictionary<string, object>>()

            var tokenRequest = new TokenRequest
			{
				Ttl = TimeSpan.FromMilliseconds(int.Parse(tokenRequestData["ttl"].ToString())),
				ClientId = tokenRequestData["clientId"] as string,
				Timestamp = DateTimeOffset.FromUnixTimeMilliseconds(long.Parse(tokenRequestData["timestamp"].ToString())),
				KeyName = tokenRequestData["keyName"] as string,
				Nonce = tokenRequestData["nonce"] as string,
				Mac = tokenRequestData["mac"] as string
			};

			var capabilityString = tokenRequestData["capability"].ToString();
			var capability = JsonConvert.DeserializeObject<Dictionary<string, List<string>>>(capabilityString);

			tokenRequest.Capability = new Capability
			{
				Resources = new List<CapabilityResource>
				{
					new CapabilityResource
					{
						Name = capability.Keys.First(),
						AllowedOperations = capability.Values.First()
					}
				}
			};

			return tokenRequest;
        }`

**Comment by arash01** [comment]
And when trying to json DeserializeObject directly to TokenRequest, it returns error:
Reason: Unexpected error :Error converting value 60000 to type 'System.Nullable`1[System.TimeSpan]'. Path 'ttl', line 2, position 17.; Code: 50000

That's why I need to create tokenRequest from scratch in Xamarin side.

**Comment by marto83** [comment]
@arash01. It's good the way you are doing it. I need to add a helper method because all the serialization utils are currently internal. 

Everything looks good. Can you just try to use the Capability constructor for parsing the capability string?
`tokenRequest.Capability = new Capability(tokenRequestData["capability"].ToString());`

**Comment by arash01** [comment]
It simplified the code but it didn't solve the problem :( My code now looks:

`async Task<TokenRequest> FetchTokenRequest()
        {
            var hub = Member.CurrentMember.Hub;
			var tokenRequestData = await new MemberService().GetAblyTokenRequestForHub(hub);

            var tokenRequest = new TokenRequest
			{
				Ttl = TimeSpan.FromMilliseconds(int.Parse(tokenRequestData["ttl"].ToString())),
				ClientId = tokenRequestData["clientId"].ToString(),
				Timestamp = DateTimeOffset.FromUnixTimeMilliseconds(long.Parse(tokenRequestData["timestamp"].ToString())),
				KeyName = tokenRequestData["keyName"].ToString(),
				Nonce = tokenRequestData["nonce"].ToString(),
				Mac = tokenRequestData["mac"].ToString(),
                Capability = new Capability(tokenRequestData["capability"].ToString())
			};

			return tokenRequest;
        }`

**Comment by marto83** [comment]
Can you do me a favour and paste the json you receive from the php lib into a support ticket and let me know the reference? I want to see what is the reason the generated json is different 🤔

**Comment by arash01** [comment]
Done, ref: 2113

**Comment by marto83** [comment]
thanks will let you know.

**Comment by mattheworiordan** [comment]
@arash01 FYI, I have tested the mac generation, and it is definitely valid (nothing in what is pasted below should be considered secret/private btw):

```
ably.auth.create_token_request(
[5] pry(main)*   ttl: 86400,
[5] pry(main)*   capability: "{\"hub:7:*\":[\"subscribe\",\"history\"]}",
[5] pry(main)*   client_id: 'customer-42',
[5] pry(main)*   timestamp: 1501580691.563,
[5] pry(main)*   nonce: '6dc6496f267e7ee54c9616c397092ba2'
[5] pry(main)* )
=> #<Ably::Models::TokenRequest:0x007fcf2122ca48
 @hash_object=
  #<Ably::Models::IdiomaticRubyWrapper:0x007fcf2122c9a8
   @attributes=
    {:keyName=>"5ZzbKQ.d2Zbcg",
     :timestamp=>1501580691563,
     :nonce=>"6dc6496f267e7ee54c9616c397092ba2",
     :clientId=>"customer-42",
     :ttl=>86400000,
     :capability=>"{\"hub:7:*\":[\"subscribe\",\"history\"]}",
     :mac=>"Nv1DGTR73g5/CSfEOPsQgyFyzMA3ISspm/AqFvBApyw="},
   @stop_at={}>>
```

**Comment by marto83** [comment]
@arash01 looking at the json the .net library adds spaces in the capability json string (to make it more readable :)) which is causing the issue 😞 

Here is a workaround that should fix the issue until I get this fix released:
```
    public class FixedCapability : Capability
    {
        public FixedCapability() : base()
        {
            
        }
        public FixedCapability(string capabilityString) : base(capabilityString)
        {
        }

        public new string ToJson()
        {
            var result = base.ToJson();
            return Regex.Replace(result, @"\s+", "", RegexOptions.Singleline);
        }
    }
...
var tokenRequest = new TokenRequest
            {
                Ttl = TimeSpan.FromMilliseconds(int.Parse(tokenRequestData["ttl"].ToString())),
                ClientId = tokenRequestData["clientId"].ToString(),
                Timestamp = long.Parse(tokenRequestData["timestamp"].ToString()).FromUnixTimeInMilliseconds(),
                KeyName = tokenRequestData["keyName"].ToString(),
                Nonce = tokenRequestData["nonce"].ToString(),
                Mac = tokenRequestData["mac"].ToString(),
                Capability = new FixedCapability(tokenRequestData["capability"].ToString())
            };
```
Can you try it and let me know?

**Comment by arash01** [comment]
It didn't help. Actually It doesn't hit the new ToJson() function.

**Comment by marto83** [comment]
You are right. I tested it with the Rest client and there it was correctly converting it. I will need to change it and release a new version. 

Which version are you using?

**Comment by arash01** [comment]
0.8.4.7

**Comment by marto83** [comment]
@arash01 I'll release a new version later today and will let you know.

**Comment by marto83** [comment]
@arash01 I updated the code and pushed a new version of 0.8.4
Can you please test it and let me know?

**Comment by arash01** [comment]
It's all good now :) Thank you so much

**Comment by mattheworiordan** [comment]
Good to hear @arash01.  Thanks @marto83
