### ISSUE TITLE
Realtime chat example not working; issue with Nito.AsyncEX dep?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-dotnet#119]
Customer reports that the Realtime Chat example in the examples/ dir is broken, with latest ably-dotnet github master: "Nito.AsyncEX version 4.0.1.0 could not load. I'm using Visual Studio 2017 and that dependency fails. Updating it fails also because the library has dependencies on old .Net frameworks."

**Comment by marto83** [comment]
I started trying to pull all the source (wasn't much in volume) from Nito.AsyncEx but it took me down a rabbit hole. I'll message the author of the library and ask him what I can do.

**Comment by marto83** [comment]
Simon, I reread the message. The examples are currently broken. I'll fix them next week.

**Comment by marto83** [comment]
@SimonWoolf I've fixed the Realtime chap sample in the `dotnet-standard` branch. 
It is not a very well polished sample. I mainly used it when testing the initial realtime integration.

**Comment by SimonWoolf** [comment]
Thanks @marto83
