### ISSUE TITLE
Realtime: Channels

### ISSUE THREAD

**Issue by yavor87** [ably/ably-dotnet#12]
* [x]   **RTS1** `Channels` is a collection of `Channel` objects accessible through `Realtime#channels`
* [x]   **RTS2** Methods should exist to check if a channel exists or iterate through the existing channels
* [x]   **RTS3** `Channels#get` function:
    * [x]   **RTS3a** Creates a new `Channel` object for the specified channel if none exists, or returns the existing channel. `ChannelOptions` can be specified when instancing a new `Channel`
    * [x]   **RTS3b** If options are provided, the options are set on the `Channel` when creaing a new `Channel`
    * [x]   **RTS3c** Accessing an existing `Channel` with options in the form `Channels#get(channel, options)` will update the options on the channel and then return the existing `Channel` object
* [x]   **RTS4** `Channels#release` function:
    * [x]   **RTS4a** Detaches the channel and then releases the channel resource i.e. it’s deleted and can then be garbage collected

**Comment by mattheworiordan** [comment]
@yavor87 can we close this if you have ticks for all?

**Comment by yavor87** [comment]
Let me fill in the tests in the google doc spec file.
