### ISSUE TITLE
Failed to install Ably into a PCL project

### ISSUE THREAD

**Issue by arash01** [ably/ably-dotnet#120]
I'm trying to add Ably into my PCL project but it fails:

Could not install package 'ably.io 0.8.4.8'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by marto83** [comment]
@arash01 the next version 0.8.5 is a .net standard library and is a portable library. It uses a new transport layer and has more fixes especially around channel timeouts. 

It is still in beta as there are a couple of issues around the new transport but we should have that cleared soon.
