### ISSUE TITLE
in maui, android, getting nullreference exception when creating ablyRest and AblyRealtime in Release

### ISSUE THREAD

**Issue by kjetil-gdm** [ably/ably-dotnet#1241]
Code:
`var options = new ClientOptions();`
`options.Key = "[apikey with Channel Metadata, History, Presence, Publish, Statistics, Subscribe]";  `
`options.AutomaticNetworkStateMonitoring = false;  `
`AblyRest ably_client_rest = new AblyRest(options); `

This works in debug mode (debugging on actual Android device).
When built for Release (and testing on actual device) it causes the following exception:
"Object reference not st to an instance of an object".
Tracke: at IO.Ably.IoC.get_MobileDevice())
at IO.Ably.AblyRest...ctor(ClientOptions)
...
Creating AblyRealtime causes the same issue.

ably.io version 1.2.11,
target .net runtime: 7.0
maui 

Am I missing a permission something, seeing how this works in debug but not release?

**Comment by sacOO7** [comment]
Hey, ideally it should work if it's working in debug mode. Can you post the full code snippet and full error log? 
If it's a small app, it would be great if you can upload it as a test repo, that would be really easy for us to recreate the problem.

**Comment by sacOO7** [comment]
For more information, you can take a look at this issue https://github.com/ably/ably-dotnet/issues/1205

**Comment by sacOO7** [comment]
I had a hunch but now it seems it might be clear why app doesn't work in release mode. It seems some level of assembly stripping must be happening in release mode. You can check this thread -> https://github.com/ably/ably-dotnet/issues/764#issuecomment-902628214.

You should disable assembly trimming for `IO.Ably.dll` using thse options -> https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options?pivots=dotnet-7-0

**Comment by kjetil-gdm** [comment]
Thanks sac007,
resolved the issue by adding the following in the .csproj file:
```
<ItemGroup>
  <TrimmerRootAssembly Include="IO.Ably" />
</ItemGroup>
```

**Comment by sacOO7** [comment]
@kjetil-gdm Great! Feel free to raise more issues if you face any problems in the future : )
