### ISSUE TITLE
Channel messages are missed or delayed

### ISSUE THREAD

**Issue by palashjhabak** [ably/ably-dotnet#1252]
I am seeing this strange issue where in some of the channel messages are missed and some of them are delayed by as high as 1 minute. 

I am seeing Ably debug logs to debug the messages right at the start before any processing

Other ably clients are receiving messages perfectly fine 

Can someone guide me to debug it further?

**Comment by sacOO7** [comment]
Hi @palashjhabak can you give me more details regarding this.
1. library version
2. which other clients are you using?
3. sample code
4. are you using sandbox env. or prod env. with ably key?

**Comment by palashjhabak** [comment]
ok, I am trying to debug the network issue. Have moved it to a new VM on AWS as well as trying to open a connection on my local machine. 

Will reply back with updates

**Comment by sacOO7** [comment]
That would be great! Thanks : )

**Comment by palashjhabak** [comment]
Also the library is designed to have multiple instances from the same client right? I mean in there is no reason it shouldn't support multiple instances, but just wanted to confirm

**Comment by sacOO7** [comment]
Yeah, ideally yes! But, if you can spot the bug ( like the case of shared logging ), it would be helpful to us. 
Btw, if the client was working for old versions, then it should also work for the new version.

**Comment by palashjhabak** [comment]
@sacOO7 I dont think version is anything to do here because I started facing the issue in the older version only and to eliminate that I upgraded to the latest version in fact.

**Comment by sacOO7** [comment]
> 

That means the old version was working just fine till some point, then issue is probably caused by external factors.

**Comment by sacOO7** [comment]
> @sacOO7 I dont think version is anything to do here because I started facing the issue in the older version only and to eliminate that I upgraded to the latest version in fact.

That means the old version was working just fine till some point, then issue is probably caused by external factors.
Can you also confirm size of the messages sent/received?
There's a known issue -> https://github.com/ably/ably-dotnet#increase-transport-send-and-receive-buffers

**Comment by palashjhabak** [comment]
> > @sacOO7 I dont think version is anything to do here because I started facing the issue in the older version only and to eliminate that I upgraded to the latest version in fact.
> 
> That means the old version was working just fine till some point, then issue is probably caused by external factors. Can you also confirm size of the messages sent/received? There's a known issue -> https://github.com/ably/ably-dotnet#increase-transport-send-and-receive-buffers

interesting let me have a look at this

**Comment by palashjhabak** [comment]
> > @sacOO7 I dont think version is anything to do here because I started facing the issue in the older version only and to eliminate that I upgraded to the latest version in fact.
> 
> That means the old version was working just fine till some point, then issue is probably caused by external factors. Can you also confirm size of the messages sent/received? There's a known issue -> https://github.com/ably/ably-dotnet#increase-transport-send-and-receive-buffers

Saw this documentation as well as the issue which first reported it, in their case I think the websocket connection itself failed but in by case connection is intact, channel state is Attached. Also that issue reports that the issue didn't exist any more in .NET core and I am on .NET core 6.0 so I don't think that's the issue but I can definitely debug in that direction

**Comment by sacOO7** [comment]
> Author
> ###

Yeah, that would be great 👍

**Comment by palashjhabak** [comment]
Hi,

so have update from my debugging. 

1. The issue is also happening when I am connecting using plain websocket in Python from my local machine or server alike
2. Issue still exist in AWS VM so network related issue is ruled out

Wanted to ask if any additional heartbeat is needed from client to ably server for ably to send message in a particular connection/channel? 

What's also interesting is that when I miss messages in a channel, next messages in that ably connection is in correct sequence. Like for example last message received had connection serial: x, and I messed a message so when I receive any next message, according to my understanding the connection serial should be: x+2 and not x+1 but I am receiving x+1, is it by design?

**Comment by sacOO7** [comment]
> Hi,
> 
> so have update from my debugging.
> 
> 1. The issue is also happening when I am connecting using plain websocket in Python from my local machine or server alike
> 2. Issue still exist in AWS VM so network related issue is ruled out
> 
> Wanted to ask if any additional heartbeat is needed from client to ably server for ably to send message in a particular connection/channel?
> 
> What's also interesting is that when I miss messages in a channel, the next messages in that ably connection is in the correct sequence. Like for example last message received had a connection serial: x, and I messed a message so when I receive any next message, according to my understanding the connection serial should be: x+2 and not x+1 but I am receiving x+1, is it by design?

Thanks for providing your findings.
About your first point, `ably-python` is still in beta, will you be able to reproduce the issue with another stable version of libraries? e.g. ably-java or ably-dotnet itself?

About your question `if any additional heartbeat is needed from the client to ably server for ably to send a message in a particular connection/channel`. **a BIG NO**. ably client libraries are designed in a way to handle all those types of issues, so no external configuration is needed.

It will be great if you can create a sample project either in `ably-dotnet` or `ably-java` or both as two separate clients which send/receives data from a dummy file and misses out on messages. It will be easy for us to look at the code and reproduce it from our side.

**Comment by palashjhabak** [comment]
just one point about python, I did not use ably client but plain websocket using websockets python library to rule out any ably client and specifically ably-dotnet related issue.

**Comment by sacOO7** [comment]
Also, some more questions 
1. Are some messages also being delivered late?
2. make sure messages are being published by checking for ack in the callback

**Comment by palashjhabak** [comment]
can you please check my obervation on connection serial numbers because that I think will eliminate issues at Ably realtime server's end and could be an issue at my server which somehow is not sending some messages to those channels where I am missing messages at.

**Comment by sacOO7** [comment]
> just one point about python, I did not use ably client but plain websocket using websockets python library to rule out any ably client and specifically ably-dotnet related issue.

Okay, I wouldn't recommend that. Because ably follow its own protocol spec to process messages ->
https://sdk.ably.com/builds/ably/specification/main/features/
It's recommended to use official libraries to process messages unless you are using a different protocol to process them.

**Comment by palashjhabak** [comment]
> Also, some more questions
> 
> 1. Are some messages also being delivered late?
> 2. make sure messages are being published by checking for ack in the callback

1. Yes I feel some messages are delivered late but need to have more data to be totally sure 
2. This I will check and let you know

**Comment by sacOO7** [comment]
Also, as I mentioned 
It will be great if you can create a sample project either in ably-dotnet or ably-java or both as two separate clients which send/receives data from a dummy file and misses out on messages. It will be easy for us to look at the code and reproduce it from our side. This would make things more clear : )

Let's forget about connection serials for now. For each message publishes ( with ack ), it should be received by client/clients at other side.

**Comment by palashjhabak** [comment]
@sacOO7 so I was able to debug further and it turns out most likely it wasn't an Ably issue at all but an issue at my server's end where I was somehow not sending messages to some channels correctly 

My bad totally. Closing the issue for now.

**Comment by sacOO7** [comment]
@palashjhabak great to hear that! Do star the repo if not already : )
