### ISSUE TITLE
JSON Encoding issues

### ISSUE THREAD

**Issue by fdmarc** [ably/ably-dotnet#1255]
I've had two problems encoding C# objects into JSON with the Ably SDK.

First, when trying to encode a `TokenRequest` from `IRestClient.Auth.CreateTokenRequestObjectAsync`, by calling JSON.net in my HTTP controller. The call to `JsonConvert.SerializeObject(tokenRequest)` was returning JSON with the original field names from the `TokenRequest` class, and ignoring the `JsonProperty` attributes. So the resulting JSON had field names `KeyName`, `Ttl` rather than `keyName`, `ttl`, etc.

The issue seemed to be that version of JSON.net in my app was not able to understand the `JsonProperty` attributes from your SDK.

I solved this problem by calling the (deprecated) `CreateTokenRequestAsync` function, which returned the correct JSON (I can only guess as to who this worked).

The second issue that I hit was converting the other way - I was trying to send domain objects from my app as the payload of Ably messages. This time _my_ `JsonProperty` attributes were being ignored. I solved this problem using this trick:

https://github.com/ably/ably-dotnet/issues/92#issuecomment-370090243

Do you have thoughts on how to address these problems?

If not, it would be nice to include [this code snippet](https://github.com/ably/ably-dotnet/issues/92#issuecomment-370090243) in the docs, since it's very powerful when you want to have fine-grained control over the JSON.

Thanks

**Comment by sacOO7** [comment]
@fdmarc sure we will most likely update the docs 👍 . Thanks for noticing :  )

**Comment by sacOO7** [comment]
@fdmarc as you can see, I have created a PR to update README -> https://github.com/ably/ably-dotnet/pull/1256. 
Let me know if any other README updates are needed, thanks :  )

**Comment by sacOO7** [comment]
@fdmarc got it 👍 .
 I think it's better to send serialized strings externally. We will merge updated README for the same 👍

**Comment by sacOO7** [comment]
Understood. Your requirement is publishing multiple messages on multiple channels at the same time, right? 
We will update `request method` to take `payload` as a string instead 👍 
Meanwhile, you need to iterate over each channel to publish messages.

**Comment by sacOO7** [comment]
For the time being, you can do
```
    static class AblyExtensions
    {
        public static Task<HttpPaginatedResponse> PublishAsync(this AblyRest ably, IEnumerable<string> channels, IEnumerable<Message> messages)
        {
           for (var channelName in channels) {
            var restChannel = ably.Channels.Get(channelName);
            await restChannel.PublishAsync(messages);
           }
        }
    }
```

**Comment by sacOO7** [comment]
I don't see it as a problem as long as the number of channels are limited ( ~10/12 channels).
If you have more channels ~100, you can use `Parallel.ForEachAsync Method` instead 
There's a blog for this -> https://medium.com/@nayanava.de01/controlling-degree-of-parallelism-with-task-whenall-in-c-1ef1e9ff2bc

**Comment by sacOO7** [comment]
However, this should be a small change to be made from our side to the `request` method. I will check and create the PR soon 👍

**Comment by sacOO7** [comment]
It's not a part of standard ably public API specification : (
Though I will check and try to make a change that suits the requirement.

**Comment by sacOO7** [comment]
@fdmarc I have created a PR to fix your issue https://github.com/ably/ably-dotnet/pull/1260. You can comment there if needed 👍

**Comment by sacOO7** [comment]
Closed via https://github.com/ably/ably-dotnet/pull/1260. 
@fdmarc you can open a new issue if there are JSON encoding issues in the future.

**Comment by sacOO7** [comment]
@fdmarc we have created a new release for this. Please use `1.2.14`, you will find all fixes available there.
