### ISSUE TITLE
Error getting value from "Id" on IO.Ably.Message, code 50000 (ios-net7 deployed, maui)

### ISSUE THREAD

**Issue by kjetil-gdm** [ably/ably-dotnet#1259]
For a deployed ios app, built with MAUI (dotnet-standard/7.0.10 dotnet-iOS) for both ably-dotnet/1.2.11 and 1.2.12 I am getting an eception while trying to .publish on a rest channel.

```

--
var options = new ClientOptions();
options.Key = "[key]";
options.AutomaticNetworkStateMonitoring = false;
AblyRest ably_client_rest = new AblyRest(options );

IRestChannel ably_channel_rest =  ably_client_rest.Channels.Get("1111");

string msg =  "[aGUIDnumber]~stringvalue~[3 digits]~[3 digits]~[4 digits]~[3 digits]";
ably_channel_rest.Publish("stringName", msg); //this throws exception
```
Exception:
"Error getting value from 'Id' on Io.Able.Message. See ably.io/error/500000.. at IO.Able.AblyRest.ExecuteRequest(AblyRequest request) at IO.Ably.AsyncHelper.RunSync/Func'1 func) at IO.Ably.RestChannel.Publish(string name, Object data, string clientId) et.c,et.c.

--
Any ideas?
I have confirmed with support that requests are received at the ably server-side (I don't know if it is only the connection)
--
I am now attempting to set the clientId specifically:
options.ClientId = "aGUID";
ably_channel_rest.Publish("stringName", msg,"sameGUID");
I'll report back if this helps.
--

**Comment by sacOO7** [comment]
Hi @kjetil-gdm is this working on local iOS app? Make sure you follow https://github.com/ably/ably-dotnet#maui-configuration

**Comment by sacOO7** [comment]
Also, i was curious if realtime publish and other related methods were working well

**Comment by kjetil-gdm** [comment]
Yes, it does work with a local ios device. I do have the trimming exclusion for ably.io in place. 
I've enabled default level logging for Ably and will build a version for testflight distribution. 
I need to query Status on Channels to get hold of Channels which are in use for my particualr use-case, so I am using the rest version as this is not an option in the RealTime client.

**Comment by sacOO7** [comment]
@kjetil-gdm thanks for the information. It will be great if you can send us detailed error log for rest publish. Also, were you able to figure out why it works on local but not on the deployed device?  Ideally it should work the same on both.
Also, you can check for encoding issues while sending newtonsoft objects as per updated README ->
https://github.com/ably/ably-dotnet/pull/1256/files

**Comment by sacOO7** [comment]
@kjetil-gdm do you have any update on this?

**Comment by kjetil-gdm** [comment]
Not yet. I am awaiting distribution of the new build with specificially set clientId and verbose logs.

**Comment by kjetil-gdm** [comment]
This test also failed. Please see verbose logs here: [image](https://www.gdm.no/gdmfiles/files/230918_214_ably_verbose.png)

**Comment by kjetil-gdm** [comment]
I have now tested with version 1.2.10 and I am seeing the same error.

**Comment by sacOO7** [comment]
Can you read this article https://faqs.ably.com/client-specified-message-id-restrictions-for-multiple-messages-published-atomically?
Also, it seems for rest publish, you need to include a unique id for each message

**Comment by sacOO7** [comment]
> This test also failed. Please see verbose logs here: [image](https://www.gdm.no/gdmfiles/files/230918_214_ably_verbose.png)

Can you get a verbose request/response for the failed published message with a payload? It would be easy for us to analyze what might be going wrong.

**Comment by kjetil-gdm** [comment]
I've switched to the AblyRealtime client for Publishing of messages, and back to Ably.io version 1.2.12.
Still getting an error. See log here: [ably_verbose_log](https://www.gdm.no/gdmfiles/files/230918_217_ably_verbose.png)
with the message I'm posting at the top.
I am sending similar seconds, as the data I am sending is from a heart rate monitor. 

 Do I need to set an Id of the individual messages somehow when publishing to a IRealtimeChannel from AblyRealtime?
I am using:
`await ably_channel_realtime.PublishAsync("personName", msg);`

**Comment by sacOO7** [comment]
@kjetil-gdm This is happening while publishing the data and not on the subscriber side right? Try setting Id while publishing the message by passing new `IO.Ably.Message` instance to publish method.
Or if both `ablyrest` and `ablyrealtime` is giving you issues, you can try publishing via https://github.com/ably/ably-dotnet#making-explicit-http-requests-to-ably-rest-endpoints--batch-publish.
I am still skeptical as to why it works on local but not on the device 🤔

**Comment by sacOO7** [comment]
Hi @kjetil-gdm seems it's related to this https://github.com/dotnet/maui/issues/8122. Can you try the solution mentioned there? It seems you have to add 
```
<UseInterpreter Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' And '$(Configuration)' == 'Release'">true</UseInterpreter>
```
to your .csproj file

**Comment by kjetil-gdm** [comment]
Hi @sacOO7, UseInterpreter did the trick! Thank you!
Include the UseInterpreter inside first PropertyGroup.. Excerpts from my csproj:
`<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-android33.0;net7.0-ios</TargetFrameworks>
    
    <UseInterpreter Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios' And '$(Configuration)' == 'Release'">true</UseInterpreter>

[...]
	</PropertyGroup>

 	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-ios|AnyCPU'">
	  <ApplicationTitle>Globeracer</ApplicationTitle>
	  <ApplicationId>no.gdm.globeracerstudio</ApplicationId>
	  <ApplicationDisplayVersion>1.0.19</ApplicationDisplayVersion>
	  <ApplicationVersion>19</ApplicationVersion>
	  <EnableAssemblyILStripping>False</EnableAssemblyILStripping>
	  <Optimize>True</Optimize>
	  <MtouchLink>SdkOnly</MtouchLink>
	  <BuildIpa>True</BuildIpa>
	  <MtouchNoSymbolStrip>True</MtouchNoSymbolStrip>
	  <DebugType>embedded</DebugType>
	</PropertyGroup>

<ItemGroup>
  <TrimmerRootAssembly Include="IO.Ably" />
</ItemGroup>

`

**Comment by sacOO7** [comment]
As always, happy to help you @kjetil-gdm . Please do star the repo :  )

**Comment by sacOO7** [comment]
> As always, happy to help you @kjetil-gdm . Please do star the repo : ) Also, feel free to raise more issues in the future!

@kjetil-gdm please let me know if there are more updates on this. I can mark it as resolved 👍

**Comment by sacOO7** [comment]
> As always, happy to help you @kjetil-gdm . Please do star the repo : ) Also, feel free to raise more issues in the future!

@kjetil-gdm marking this as resolved. You can open a new issue in the future if needed 👍
