### ISSUE TITLE
No `async` version of `IRestChannel.Status`

### ISSUE THREAD

**Issue by fdmarc** [ably/ably-dotnet#1263]
`IRestChannel.Status` is a blocking function, and there is no async equivalent in the API. This is in contrast to `.Publish` / `.PublishAsync` and `.History` / `.HistoryAsync`.

Indeed, the implementation is implemented in terms of StatusAsync:

```c#
        private async Task<ChannelDetails> StatusAsync()
        {
            AblyRequest request = _ablyRest.CreateGetRequest("/channels/" + Name);
            return await _ablyRest.ExecuteRequest<ChannelDetails>(request);
        }

        /// <inheritdoc/>
        public ChannelDetails Status()
        {
            return AsyncHelper.RunSync(StatusAsync);
        }
```

**Comment by sacOO7** [comment]
Fixed via https://github.com/ably/ably-dotnet/pull/1266
