### ISSUE TITLE
Ably dll and iOS app size increased

### ISSUE THREAD

**Issue by softsan** [ably/ably-dotnet#134]
We have noticed that after adding 8.5 rc-2, the size of dll is increase by almost double for iOS. This is holding back us as it effect the whole binary size crossing 100mb on app store.

Please see image where earlier we have ably dll in kbs and now its in Mbs. So is it possible to decrease/compress size of your assemblies?

Thanks

<img width="1365" alt="ably" src="https://user-images.githubusercontent.com/7391319/30288658-328214c4-9747-11e7-8c02-4eb389e36e26.png">

**Comment by withakay** [comment]
Hi,

Thanks for reporting this issue, I will see if what can be done about getting the size back down.

In the mean time, if getting the size of your app down is urgent there are some general points worth mentioning regarding iOS app sizes (my apologies if I am repeating things you are already aware of).

The current 100MB over the air update limit for iOS apps is actually per slice (i.e. per architecture) it is actually only the TEXT sections of the binary that count. When you submit to Apple the initial checks they do are quite crude so they will throw up a warning even if your individual slice size is much lower in size, so the warnings you see may not affect you. It is possible to check slice sizes using the `size` command line tool on OS X.
Optimising your build might yield much more significant reductions.  Enabling the linker for all code with have the most drastic effect, but there are caveats if you are using IoC or reflection, so test thoroughly. (see the docs for more information - https://developer.xamarin.com/guides/ios/advanced_topics/linker/).
Enabling the LLVM optimising compiler is worth trying out too.
Optimise your assets, in particular images. PNG optimisation is lossless, so is always worth shot. 

Again, apologies if this is all old news to you, but on the off chance I thought it worth mentioning.

**Comment by caseyniemann** [comment]
@withakay Yes we have done those items---linker presents challenges due to dependencies, but have checked others.  Standing by for your update

**Comment by caseyniemann** [comment]
@withakay Jack--Any updates on this request?

**Comment by caseyniemann** [comment]
@withakay when we built from source we see a bug that @marto83 had previously fixed.  Posting
caused.AggregateException(s)
IO.Ably.Realtime.Presence.PresenceMap.EndSync()<b468bc9bcf0d4d419953a5e0dbc4314b>:0
IO.Ably.Realtime.Presence.OnPresence(PresenceMessage[] messages, string syncChannelSerial)<b468bc9bcf0d4d419953a5e0dbc4314b>:0
IO.Ably.Realtime.ChannelMessageProcessor.MessageReceived(ProtocolMessage protocolMessage)<b468bc9bcf0d4d419953a5e0dbc4314b>:0
IO.Ably.Transport.ConnectionManager.<ProcessTransportMessage>d__73.MoveNext()<b468bc9bcf0d4d419953a5e0dbc4314b>:0
--- End of inner exception stack trace ---
IO.Ably.Transport.ConnectionManager.<ProcessTransportMessage>d__73.MoveNext()<b468bc9bcf0d4d419953a5e0dbc4314b>:0
IO.Ably.Transport.ConnectionManager.<OnTransportMessageReceived>d__71.MoveNext()<b468bc9bcf0d4d419953a5e0dbc4314b>:0
--- End of inner exception stack trace ---
---> (Inner Exception #0) IO.Ably.AblyException: Reason: Unexpected error :Object reference not set to an instance of an object; Code: 50000 ---> System.NullReferenceException: Object reference not set to an instance of an object
IO.Ably.Realtime.Presence.PresenceMap.EndSync()<b468bc9bcf0d4d419953a5e0dbc4314b>:0
IO.Ably.Realtime.Presence.OnPresence(PresenceMessage[] messages, string syncChannelSerial)<b468bc9bcf0d4d419953a5e0dbc4314b>:0
IO.Ably.Realtime.ChannelMessageProcessor.MessageReceived(ProtocolMessage protocolMessage)<b468bc9bcf0d4d419953a5e0dbc4314b>:0
IO.Ably.Transport.ConnectionManager.<ProcessTransportMessage>d__73.MoveNext()<b468bc9bcf0d4d419953a5e0dbc4314b>:0
--- End of inner exception stack trace ---
IO.Ably.Transport.ConnectionManager.<ProcessTransportMessage>d__73.MoveNext()<b468bc9bcf0d4d419953a5e0dbc4314b>:0
IO.Ably.Transport.ConnectionManager.<OnTransportMessageReceived>d__71.MoveNext()<b468bc9bcf0d4d419953a5e0dbc4314b>:0

**Comment by withakay** [comment]
@caseyniemann I don't have an answer just yet to reversing the size increase.
Removing some inlined dependencies would reduce the size, but that has knock on effects for other users.

**Comment by mattheworiordan** [comment]
@caseyniemann what's the status / current thinking on a version without MsgPack support?

**Comment by caseyniemann** [comment]
@mattheworiordan @withakay We don't have any direct dependencies on MSGPack that we are aware of.  Create a build and we will try it

**Comment by mattheworiordan** [comment]
@caseyniemann yup, that's the idea.  MsgPack is just an optimisation at a transport level, so by removing it it should have no impact on you and will hopefully give you an option to reduce the overall library size.  We're looking at this as I believe @marto83 previously did some work on this that @withakay will pick up.

**Comment by marto83** [comment]
Closing. For the time being MsgPack has been removed. 
Feel free to reopen if it's still an issue.
