### ISSUE TITLE
Add support for Nuget

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#14]
We need to ensure ably dotnet is distributable in Nuget

**Comment by yavor87** [comment]
Nuspec available here: https://github.com/ably/ably-dotnet/tree/realtimeClientTests/nuget . We only need the publishing key and we roll.

**Comment by mattheworiordan** [comment]
Is this actually published?

**Comment by yavor87** [comment]
No, the specification is done. Using that we can create an actual package and publish it on nuget.org.
