### ISSUE TITLE
Reinstitute MsgPack

### ISSUE THREAD

**Issue by withakay** [ably/ably-dotnet#156]
We should periodically check the status of MsgPack and when it is stable on the required platforms, re-enabled it. 

Specifically this has affected people targeting UWP (see [this issue](https://github.com/ably/ably-dotnet/issues/106)).
A secondary issue that MsgPack has quite a large binary which created some [issues on iOS](https://github.com/ably/ably-dotnet/issues/134)

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-114) by [Unito](https://www.unito.io)

**Comment by mrueedi** [comment]
UWP + locally cloned ably worked with MsgPack.Cli 0.9.2 (referenced via nuget) on my little test app. I am waiting for new release using MsgPack.

**Comment by mattheworiordan** [comment]
FYI, once we have a stable release of MsgPack, we need to ensure https://github.com/ably/ably-dotnet/issues/106 is addressed.

**Comment by QuintinWillison** [comment]
@marto83 says:

> needs to come back now the library is mature

**Comment by sacOO7** [comment]
Need to revert some of the changes from 
1. https://github.com/ably/ably-dotnet/pull/145
2. https://github.com/ably/ably-dotnet/pull/148

**Comment by sacOO7** [comment]
- @marto83 I think we could have implemented this change in a better way. 
- Could have kept protocol value to be **JSON** independent of **UseBinaryProtocol**.

**Comment by tomkirbygreen** [comment]
Closing this issue, it is now referenced by the new `MsgPack` [issue](https://github.com/ably/ably-dotnet/issues/590)
