### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#159]
A customer has asked about Proxy support in .NET.  Specifically:

> We are not using browsers in our application but we are  using the ably .net library in our windows application,  and yes the proxy does use authentication.
> we were wondering if there is any way having proxy setting for the ably realtime?

The official client lib spec sets out no requirements at present for proxy support, but [Java has partial support](https://github.com/ably/ably-java/issues/120), as does [Ruby](https://github.com/ably/ably-ruby/pull/84).

@withakay can you advise on what may be required to add proxy support for REST and WebSocket transports, should we wish to add it?  I assume you'll need to look at the underlying libraries we depend on for their support to answer this.

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-115) by [Unito](https://www.unito.io)

**Comment by withakay** [comment]
To directly roll proxy support in to the Ably Client is quite straight forward for REST and also for WebSocket transports using System.Net.WebSockets as these both take [System.Net.WebProxy](https://msdn.microsoft.com/en-us/library/system.net.webproxy(v=vs.110).aspx) as a parameter. 

For transports using websockets4net the answer is [less clear](https://github.com/kerryjiang/WebSocket4Net/issues/34), although it does appear to be possible.

It is worth noting that making WebSockets connections through a proxy is possible with the current release by creating a custom implementation of [IO.Ably.Transport.ITransportFactory](https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Transport/ITransport.cs) and passing that into [AblyRealtime](https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/AblyRealtime.cs) via the [ClientOptions](https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/ClientOptions.cs). An example ITransport implementation can be found [here](https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Transport/MsWebSocketTransport.cs). 
Not very user friendly, but doable. Unfortunately there is no such extensibility point for REST though.

**Comment by tomkirbygreen** [comment]
How much if any subsequent interest has there been in this? Would it be OK to consolidate and close this ticket please?

**Comment by tomkirbygreen** [comment]
Paddy addressed proxy support in the stand up this morning and we have no plans to support this at the current time. Closing.
