### ISSUE TITLE
System.Net.Http conflict

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#162]
From customer in support ticket 2499:

> I'm trialing a free account using .Net 4.6.

> I'm using IO.Ably;

> And calling the following:
> AblyRealtime realtime = new AblyRealtime("my api key");
>         var channel = realtime.Channels.Get("msgRefresh");
>         channel.Publish("MessageUpdate", "message data");

> BUT on the call to AblyRealtime realtime = new AblyRealtime("my api key");

> I get the following:
 
> An error occurred:Failed to send message, reason: Could not load file or assembly 'System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by withakay** [comment]
It is hard to say what the issues is with the current information. 

Is this is a green field project or if Ably was added to an existing project?
It is worth trying to install/update to the latest System.Net.Http via nuget and seeing if that has any effect.

**Comment by GrahamLock** [comment]
Hi,
I have updated the HTTP package as suggested and now works fine.

Many thanks.)

**Comment by mattheworiordan** [comment]
Good to know, thanks @GrahamLock. Can we close this issue then?
