### ISSUE TITLE
 customer getting an exception from MessageWebSocketMessageReceivedEventArgs.GetDataReader() in 0.8.6 beta 3

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-dotnet#164]
Copying from https://support.ably.io/helpdesk/tickets/2516

> Platform : Windows 10
Ably .Net library :  0.8.6 Beta 3
I am getting an unhandled exception in my Xamarin UWP app.
To reproduce this issue I simply start my app and all is working fine, I am able to send and receive messages.  But if I then disable the network (I use wi-fi) or switch to airplane mode I find after around 30 seconds the app abruptly closes I get an unhandled exception. 
"System.Exception: Exception from HRESULT: 0x80072EE2\r\n   at Windows.Networking.Sockets.MessageWebSocketMessageReceivedEventArgs.GetDataReader()\r\n   at System.Net.WebSockets.WinRTWebSocket.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)"

**Comment by withakay** [comment]
I will attempt to reproduce this and confirm the bug ASAP

**Comment by withakay** [comment]
I managed to repeat this (at last).
I believe this is a manifestation of this issue.
https://github.com/dotnet/corefx/issues/17317

Microsoft released a fix for this recently. 
In your UWP project add a reference via nuget to 'System.Net.WebSockets.Client' version 4.3.2 (or newer).

Note, this is only an issue if you are targeting Windows 10 versions before Windows 10 Fall Creators Update.

**Comment by DaTester** [comment]
Thanks @withakay , adding ' System.Net.WebSockets.Client' version 4.3.2 has fixed this issue.

**Comment by withakay** [comment]
@DaTester Great!
I will see about updating the nuspec file so UWP has a dependency on System.Net.WebSockets.Client 4.3.2, which should prevent new users from running into this.
