### ISSUE TITLE
"The WebSocket protocol is not supported on this platform." on Windows 7

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#165]
Some of our customers are still on Windows 7. And there is this error for the latest commit a8b5437492277f62c8e83549b01893ed6f9f0732  "The WebSocket protocol is not supported on this platform.; "
I've used the code below for previous Ably versions.
```
if (Environment.OSVersion.Version.Major == 6 && Environment.OSVersion.Version.Minor < 2 || Environment.OSVersion.Version.Major < 6)
              options.TransportFactory = new WebSocketTransport.WebSocketTransportFactory();
```
But as I understand you've removed support for the above. I'd appreciate if could you provide instructions how to change the Ably source code back or how to enable support for Windows 7.

**Comment by withakay** [comment]
Hello, thanks for reporting this issue and apologies for causing you unexpected problems. 

You will need to implement an ITransportFactory that uses WebSocket4Net in your project and pass that into the Ably client with ClientOptions.

I have prepared a sample project that should give you an idea of what is required.
https://github.com/withakay/ably-dotnet-alternative-transports

Let us know how you get on?

**Comment by lovetofail** [comment]
It's working great. Thank you.

**Comment by withakay** [comment]
I have updated the readme for the most recent release with a note for windows 7 users.
