### ISSUE TITLE
After upgrade to 0.8.6, System.Net.WebSockets.WebSocketException

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#166]
From customer, support ticket 2539:

We updated o the stable .86 net client library.  We now get:

```
Socket.EndSend(System.IAsyncResult asyncResult)
android.runtime.JavaProxyThrowable: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.Net.WebSockets.WebSocketException: The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to write data to the transport connection: Network subsystem is down. ---> System.Net.Sockets.SocketException: Network subsystem is down
d727e8e344a34a409aae05e74d97553d

caused.AggregateException(s)
System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
--- End of inner exception stack trace ---
Mono.Security.Protocol.Tls.SslStreamBase.EndWrite(IAsyncResult asyncResult)<39aea71bbd214018b69bee2e81017dce>:0
Mono.Net.Security.Private.LegacySslStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
Mono.Net.Security.Private.MonoSslStreamImpl.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.Security.SslStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Func<Stream, IAsyncResult, VoidTaskResult>.invoke_TResult_T1_T2(Stream, IAsyncResult)(wrapper delegate-invoke)
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncTrimPromise<TInstance>.Complete(TInstance thisRef, Func<T1, T2, TResult> endMethod, IAsyncResult asyncResult, bool requiresSynchronization)<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Net.WebSockets.ManagedWebSocket.<>c.<SendFrameLockAcquiredNonCancelableAsync>b__55_0(Task t, object s)<d727e8e344a34a409aae05e74d97553d>:0
--- End of inner exception stack trace ---
System.Net.WebSockets.ManagedWebSocket.<>c.<SendFrameLockAcquiredNonCancelableAsync>b__55_0(Task t, object s)<d727e8e344a34a409aae05e74d97553d>:0
System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Threading.Tasks.Task.Execute()<fd83fae689d54d8fb6b6804c6d1ec054>:0
--- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to write data to the transport connection: Network subsystem is down. ---> System.Net.Sockets.SocketException: Network subsystem is down
System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
--- End of inner exception stack trace ---
Mono.Security.Protocol.Tls.SslStreamBase.EndWrite(IAsyncResult asyncResult)<39aea71bbd214018b69bee2e81017dce>:0
Mono.Net.Security.Private.LegacySslStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
Mono.Net.Security.Private.MonoSslStreamImpl.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.Security.SslStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Func<Stream, IAsyncResult, VoidTaskResult>.invoke_TResult_T1_T2(Stream, IAsyncResult)(wrapper delegate-invoke)
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncTrimPromise<TInstance>.Complete(TInstance thisRef, Func<T1, T2, TResult> endMethod, IAsyncResult asyncResult, bool requiresSynchronization)<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Net.WebSockets.ManagedWebSocket.<>c.<SendFrameLockAcquiredNonCancelableAsync>b__55_0(Task t, object s)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.WebSockets.ManagedWebSocket.<>c.<SendFrameLockAcquiredNonCancelableAsync>b__55_0(Task t, object s)<d727e8e344a34a409aae05e74d97553d>:0
System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Threading.Tasks.Task.Execute()<fd83fae689d54d8fb6b6804c6d1ec054>:0
```

**Comment by withakay** [comment]
@mattheworiordan I am unable to repeat this, is there any more information available?

**Comment by caseyniemann** [comment]
Internal web socket error…when losing internet connection over ssl, isn’t handled correctly.

caused.AggregateException(s)
System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
--- End of inner exception stack trace ---
Mono.Security.Protocol.Tls.SslStreamBase.EndWrite(IAsyncResult asyncResult)<39aea71bbd214018b69bee2e81017dce>:0
Mono.Net.Security.Private.LegacySslStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
Mono.Net.Security.Private.MonoSslStreamImpl.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.Security.SslStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Func<Stream, IAsyncResult, VoidTaskResult>.invoke_TResult_T1_T2(Stream, IAsyncResult)(wrapper delegate-invoke)
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncTrimPromise<TInstance>.Complete(TInstance thisRef, Func<T1, T2, TResult> endMethod, IAsyncResult asyncResult, bool requiresSynchronization)<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Net.WebSockets.ManagedWebSocket.<>c.<SendFrameLockAcquiredNonCancelableAsync>b__55_0(Task t, object s)<d727e8e344a34a409aae05e74d97553d>:0
--- End of inner exception stack trace ---
System.Net.WebSockets.ManagedWebSocket.<>c.<SendFrameLockAcquiredNonCancelableAsync>b__55_0(Task t, object s)<d727e8e344a34a409aae05e74d97553d>:0
System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Threading.Tasks.Task.Execute()<fd83fae689d54d8fb6b6804c6d1ec054>:0
--- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.IO.IOException: Unable to write data to the transport connection: Network subsystem is down. ---> System.Net.Sockets.SocketException: Network subsystem is down
System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
--- End of inner exception stack trace ---
Mono.Security.Protocol.Tls.SslStreamBase.EndWrite(IAsyncResult asyncResult)<39aea71bbd214018b69bee2e81017dce>:0
Mono.Net.Security.Private.LegacySslStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
Mono.Net.Security.Private.MonoSslStreamImpl.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.Security.SslStream.EndWrite(IAsyncResult asyncResult)<d727e8e344a34a409aae05e74d97553d>:0
System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResult asyncResult)<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Func<Stream, IAsyncResult, VoidTaskResult>.invoke_TResult_T1_T2(Stream, IAsyncResult)(wrapper delegate-invoke)
System.Threading.Tasks.TaskFactory<TResult>.FromAsyncTrimPromise<TInstance>.Complete(TInstance thisRef, Func<T1, T2, TResult> endMethod, IAsyncResult asyncResult, bool requiresSynchronization)<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Net.WebSockets.ManagedWebSocket.<>c.<SendFrameLockAcquiredNonCancelableAsync>b__55_0(Task t, object s)<d727e8e344a34a409aae05e74d97553d>:0
System.Net.WebSockets.ManagedWebSocket.<>c.<SendFrameLockAcquiredNonCancelableAsync>b__55_0(Task t, object s)<d727e8e344a34a409aae05e74d97553d>:0
System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()<fd83fae689d54d8fb6b6804c6d1ec054>:0
System.Threading.Tasks.Task.Execute()<fd83fae689d54d8fb6b6804c6d1ec054>:0

**Comment by withakay** [comment]
@casseyniemann what version of Xamarin are you using?

**Comment by withakay** [comment]
I am unable to repeat this so I am going to close due to inactivity, please reopen this issue is affecting you.
