### ISSUE TITLE
Channel options consistently being overridden on realtime channels (v0.8.6)

### ISSUE THREAD

**Issue by Kwal** [ably/ably-dotnet#167]
This [commit](https://github.com/ably/ably-dotnet/commit/ac1c55805877fd101bcd4fd2145ecde278f12cf1) seems to have broken channel options. Whenever a channel is retrieved while sending a message, the options for the channel are overridden with the new options that are created [here](https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Realtime/RealtimeChannels.cs#L26).

This is especially problematic for encrypted channels since all options are being lost and messages are being published without any encryption.

**Comment by withakay** [comment]
I will look into this ASAP

**Comment by withakay** [comment]
@Kwal Are you able to provide the steps required to repeat this please?

**Comment by Kwal** [comment]
I forked and updated some of the code [here](https://github.com/Kwal/ably-dotnet/commit/57989d3838b3a42b661de1f3000c1992abeab3d6) - please let me know if you need more info.

**Comment by withakay** [comment]
@kwal That is awesome, I will review as soon as I am able. Thanks!

**Comment by withakay** [comment]
@Kwal Apologies for the delay in fixing this issue.
I have submitted a PR with a fix, so hopefully we will have a new release soon.

**Comment by withakay** [comment]
fixed in 0.8.7
