### ISSUE TITLE
Unity support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#169]
See feedback from user at https://twitter.com/maartenp/status/943115381874544640

I have asked for more details.

**Comment by maartenp** [comment]
Apologies for the delay in responding.

There are three issues I'm experiencing in Unity, two of which I've been able to work around.
 
1) Unity does not support TLS 1.2. Workaround is requesting token through Rest, and then disabling TLS on Realtime connection
2) Newtonsoft.Json uses dynamic keyword, which is not supported on iOS. Workaround is to link to Unity compatible version: https://www.assetstore.unity3d.com/en/#!/content/11347
3) Connection gets disconnected every 15 seconds.

I've packaged up an example Unity project at: https://github.com/maartenp/ably-unity-test. It runs on the latest Unity version (2017.3.0p1) which you can get here: https://unity3d.com/unity/qa/patch-releases

The demo prints connection status changes, so you can see that every 15 seconds, it gets disconnected.

**Comment by maartenp** [comment]
If it helps debugging, I've tried 0.8.7, 0.8.6 and 0.8.6-beta3 (to test whether it was related to System.Net.WebSockets), and all have the same issue.

**Comment by withakay** [comment]
@maartenp Thanks, I will take a look soon, I have a bunch of stuff to catch up on!

**Comment by maartenp** [comment]
Did some more digging with Wireshark and adding a Logger. The Log entry: "Recieving message with type: Close" is coinciding with the Websocket PING and Heartbeat / {"action": 0} message.

**Comment by maartenp** [comment]
One more piece of information. If I request a Heartbeat (using PingAsync), the connection does not close. Changing the "heartbeatInterval" in transportParams to 1 minute results in the connection dropping every 1 minute.

**Comment by mattheworiordan** [comment]
@maartenp sorry for the slow response on our end.  To be completely honest, our focus at present is to get the .Net lib test suite running across all platforms, which it hasn't done until now.  As such, when we make changes or introduce new features, we have found out about issues from customers as opposed to CI failures, which is clearly not good enough if the lib is being used in environments we support. So we are focussed on that right now and making good progress.  Hopefully, once that is done, we'll be in a much better position to have more robust wider platform support and support platforms like Unity with a stable release.

**Comment by ashikns** [comment]
@mattheworiordan Is Unity compatibility something you guys are aiming to implement? I recently setup a fork for a project which is compatible with Unity 2017 and newer (with .Net 4.6). It requires the classes to be rewritten to be compatible with C# 6, so there are a moderate amount of changes.

**Comment by withakay** [comment]
@ashikns Getting the library to 1.0 spec is the top priority at the moment, but Unity compatibility is something we would like to address down the line (but there is no specific timeline for that right now).

There are various problems with Unity support (see above) but c# 7+ syntax should not be one of them, If you look at @maartenp's [project](https://github.com/maartenp/ably-unity-test) above you can see that you don't need to convert to c# 6 syntax, just link to an assembly targeting the desired platform.

**Comment by ashikns** [comment]
That was the first path I went down. But then you get problems when calling functions that use HttpClient. I devised a work around for that, but it's not a very clean one.

**Comment by ashikns** [comment]
Just wanted to report that I found a work around for this. Workaround 1 mentioned in this [comment](https://github.com/ably/ably-dotnet/issues/169#issuecomment-354679578) is still necessary since Unity editor doesn't support TLS 1.2. I was able to solve the issue with connection dropping every 15 seconds by manually porting some parts of .Net core to Unity. In other words websocket implementation in Unity is broken, so you have to 

1. Manually port websocket implementation from netfx core
2. Modify the ably source to refer to that

Tested this with Unity Editor and UWP. If anyone needs this in the future, the ported HttpClient and WebSocket implementation is available at https://github.com/ashikns/UnityNetCore.

**Comment by withakay** [comment]
@ashikns Awesome, thanks for the update.

BTW, You should not need to modify the ably source to use an alternative websocket transport, see https://github.com/ably-forks/ably-dotnet-alternative-transports for example of injecting an ITransportFactory implemenation via the ClientOptions.

**Comment by ashikns** [comment]
Ah yes I saw that class and figured there must be some way to do it. In that case for folks who do not need to build for UWP just using that should be enough. Uwp has some specific problems that require me to bring in System.Net.Http manually as well though, so I'll have to continue with the present solution. But hey, it works and I'm happy. Thanks for the dotnet library :)

**Comment by ashikns** [comment]
@withakay I followed your suggestion to replace the websocket transport and that fixed half of the issues. Unity also has an issue with HttpClient, it's incomplete/broken/both of these. However thanks to the IAblyHttpClient interface I was able to replace the AblyHttpClient implementation with one based on UnityWebRequests. It took some work but now everything works :) Thanks for your suggestions

**Comment by maartenp** [comment]
@ashikns Would you mind sharing a demo project?

**Comment by withakay** [comment]
@ashikns That is great! If you are able it would be great if you could share your code so we can point others at it in the future, would that be possible?

**Comment by ashikns** [comment]
@withakay @maartenp I have a fork: https://github.com/ashikns/ably-dotnet/tree/httpclient-expose. That branch contains the commits to expose IAblyHttpClient so that an alternate implementation can be provided by outside code. The implementation of HttpClient based on UnityWebRequest is in a private project atm, I'll pull that into a separate public project and share it. Will post a link once I do.

**Comment by mattheworiordan** [comment]
@ashikns send your address details to matt at ably dot io, and we'll send you some swag as a thanks!  We really appreciate that :)

**Comment by ashikns** [comment]
It would be great if you guys can somehow make this part of the official repo - i.e. the ability to inject an implementation of IAblyHttpClient similar to how ITransport works. My repo works and doesn't break any existing stuff, but it's a bit heavy and I imagine there'd be a lot of coding style and other concerns from your perspective.

**Comment by mattheworiordan** [comment]
> It would be great if you guys can somehow make this part of the official repo

We will do, that is planned, but we're just flat out on v1.0 for now.  That will come soon though.

**Comment by ashikns** [comment]
@maartenp Added a sample project here: https://github.com/ashikns/AblyUnity. The editor client likely has some bugs. Our primary focus is on uwp so we can live with it. Uwp by the way needs some nuget packages and an upgraded .net core runtime, the sample project has a script to automatically include the necessary packages.

**Comment by mattheworiordan** [comment]
Thanks @ashikns, you're a star 👍

**Comment by LeviathanGames** [comment]
We'd be interested in this solution if we can get our hands on it for unity mobile. Its not clear how well your solution overlaps with that use case @maartenp

**Comment by ashikns** [comment]
@LeviathanGames  We don't target mobile so I really have no idea how that would turn out. I think Unity will be able to rewrite the core Ably plugin for mobile platform without any issues. You just have to find a websocket compatible with mobile and inject that as ITransport to Ably. 

For websocket there should be some already available options, for example - https://assetstore.unity.com/packages/tools/network/websocket-for-desktop-web-and-mobile-27658.

**Comment by LeviathanGames** [comment]
What was wrong with the normal .net websocket implementation? I thought we had used it before successfully. We are using unity 2017.

**Comment by LeviathanGames** [comment]
We’ve gotten most of the way towards a Unity<->Ably solution working. We used this websocket: https://github.com/sta/websocket-sharp and are using the latest 2017 unity with the “Experimental” .net 4.x support turned on. 

The test app is talking to Ably ok, but the current issue when a client receives a message on a channel they're listening to, this error is thrown from the .Net SDK "Unexpected error :This instance is a client.; Code: 50000". 
We don't get any errors when subscribing to a channel or publishing a message to a channel.

If someone else wants to try and help sort this out, please feel free.. here’s the project: https://www.dropbox.com/s/k8ud8awbq8pli15/AblyUnityTest.zip?dl=0 

You will need to enter your own keys, then hit run.

Cheers

**Comment by withakay** [comment]
@LeviathanGames 
You are seeing an error that originates from websocket-csharp (https://github.com/sta/websocket-sharp/blob/8a587772988f4df655ba4fe348d832fefdf22e1c/websocket-sharp/WebSocket.cs#L2530) 

I have not had a chance to run your Unity project but I had a quick look over the code and can see your `ITransport` implementation you are calling `_socket.Accept()`, should that not be `_socket.Connect()`?

```
public void Connect()
{
    if (_socket == null)
    {
        _socket = CreateSocket(WebSocketUri);
        AttachEvents();
    }
    _socket.Connect();
}
```

**Comment by LeviathanGames** [comment]
We got this working with a few minor fixes. Needs more testing.. 
Thanks!

**Comment by PixelRouter** [comment]
@LeviathanGames Your dropbox link is dead. Any chance you could upload it again, or even better yet, upload the working version? It'd be great to package this up a a unity package and post it here.. I may do that if you can let me see your solution.

**Comment by prichardsondev** [comment]
I was not able to get workarounds to run - I assume it was just the lack of time I had to investigate.  I needed a Unity IoT proof concept up and running so I did the following which works fine for anyone else trying.

node express api on Raspberry Pi server
UnityWebRequest class on client page

If you get a bulls-eye the light on our IoT house will toggle... -) I find it takes a bit in the beginning to connect so if you get a bulls-eye in the beginning but no light - try again -)

[https://www.screencast.com/t/bpB1ehqj](url)
[http://www.internetofcoolthings.net/webgltest/](url)
[ http://www.internetofcoolthings.net/ably](url)

**Comment by withakay** [comment]
We have Unity support now, albeit experimental. See the https://github.com/ably/ably-dotnet#unity
