### ISSUE TITLE
Switch arity of auth methods

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#17]
See https://github.com/ably/docs/commit/63ff7fa2d654641a9d7856bd8dc67beb937d3fef

The `AuthOptions` and `TokenParams` arguments are switched.

@yavor87 sorry for this change, but this is the last change in the 0.8 spec and we felt it makes a lot more sense to have `TokenParams` as the first argument as that is the most common argument and `AuthOptions` is optional.

**Comment by yavor87** [comment]
The RequestToken signature that we have currently seems correct. Take a look [here](https://github.com/ably/ably-dotnet/blob/master/src/Ably/AblyTokenAuth.cs#L34).

**Comment by mattheworiordan** [comment]
Well sort of.

The argument should be a `TokenParams` object, not a `TokenRequest` object, but at least the order is correct!

**Comment by mattheworiordan** [comment]
Also, `force` is a property of `AuthOptions` and does not need to be an argument of the `authorise` method, see https://github.com/ably/docs/commit/7e7dc0e19cbb3af98136d5ca39e217e00dfd25f2

**Comment by mattheworiordan** [comment]
@yavor87 any update on this?

**Comment by marto83** [comment]
Done! https://github.com/ably/ably-dotnet/blob/v0.8/src/IO.Ably.Shared/AblyAuth.cs#L263
