### ISSUE TITLE
Xamarin support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#18]
Apparently the .NET does work on Xamarin, even if compiled for Xamarin.

**Comment by paddybyers** [comment]
> Apparently the .NET does work on Xamarin

maybe "does not" ?

**Comment by mattheworiordan** [comment]
Oops, I meant does not

**Comment by mattheworiordan** [comment]
@yavor87 what is the status on thsi?

**Comment by yavor87** [comment]
In progress

**Comment by mattheworiordan** [comment]
Closed in favour of #32
