### ISSUE TITLE
Tagged version and changelog missing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#19]
Currently this repo has no version, we should release a `v0.8.x`, see Ruby's releases at https://github.com/ably/ably-ruby/releases for an example

Changelog is referenced from the README, but is missing and should contain the history of changes following the initial release, see https://github.com/ably/ably-ruby/blob/master/CHANGELOG.md

**Comment by mattheworiordan** [comment]
We should also release the tagged version to Nuget at the same time, and every time in future a new version is tagged, we should release

**Comment by marto83** [comment]
Changelog is now included in the repo and I tag each release.
