### ISSUE TITLE
Allow an IAblyHttpClient implementation to be injected via ClientOptions

### ISSUE THREAD

**Issue by withakay** [ably/ably-dotnet#192]
This would allow a custom HTTP Client in a similar way to the ways custom transports can be injected. Specifically this would be useful for customers using unity, see https://github.com/ably/ably-dotnet/issues/169 for more in the comments.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-116) by [Unito](https://www.unito.io)

**Comment by tomkirbygreen** [comment]
@withakay How much demand has there been for this over the preceding 3+ years? If it's  borderline zero I'd like to consider closing this issue with 'No plan to implement at this time' status. What do you think?

**Comment by withakay** [comment]
@tomkirbygreen I am not actively involved here these days, so couldn't really say for sure but I would hazard a guess that since Unity has had support for NETStandard2.0 for a while now, this is probably a non issue and can be closed.

**Comment by tomkirbygreen** [comment]
> @tomkirbygreen I am not actively involved here these days, so couldn't really say for sure but I would hazard a guess that since Unity has had support for NETStandard2.0 for a while now, this is probably a non issue and can be closed.

Thank you ever so much for your input :-) Much appreciated!
