### ISSUE TITLE
Create a demo project

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-dotnet#199]
Along the lines of other demo projects like https://github.com/ably/demo-mobile-ios

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-117) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
We're retiring Asana but related note from [the ticket there](https://app.asana.com/0/623496170845722/623496177079301):

> Need some very basic demos on how to use Ably in Xamarin, .NET Mono etc.
