### ISSUE TITLE
Consider exposing the iOS and Android native SDKs as a NuGet package

### ISSUE THREAD

**Issue by ndastur** [ably/ably-dotnet#202]
The .Net SDK has been behind in development terms and just reminded again about all the enhancements in the v1.0 SDKs (https://blog.ably.io/v1-0-client-libraries-released-8a375dca7a26)

Would it not easier to keep the .Net SDK up to date by binding to the native platform SDKs?

**Comment by funkyboy** [comment]
@ndastur binding to native platforms would be a good solution for iOS and Android, but with the .NET SDK we are aiming at a broader support that includes .NET framework, Core and UWP.
@withakay is [working to include all the features of v1.0](https://github.com/ably/ably-dotnet/pulls) and he's on the right track to have a new version soon.

If you like to get involved in this process let us know. We'll provide support and review your contributions.
