### ISSUE TITLE
Presence sync doesn't complete on the first chance

### ISSUE THREAD

**Issue by ashikns** [ably/ably-dotnet#204]
Presence WaitForSyncAsync has a bug where the internal PresenceMap completes initial sync, but this is not picked up by WaitForSyncAsync because the relevant event was fired InitialSyncComplete has been set to true. Currently sync will only be marked as complete after a subsequent Map.StartSync() and Map.EndSync() has been called. This causes a delay of few seconds in getting channel presence.

Exact details and a fix can be found at: https://github.com/ashikns/ably-dotnet/commit/d764550a3c01b10af53ef19830a081cac946f6f5

**Comment by paddybyers** [comment]
Hi, thanks for looking into this and for the contribution. The maintainer of this library is away until next week but we'll take a look as soon as we can.

**Comment by withakay** [comment]
@ashikns thanks for your work, would you like to make a pull request so we can look at getting this integrated?
