### ISSUE TITLE
Review PresenceMap implementation.

### ISSUE THREAD

**Issue by withakay** [ably/ably-dotnet#209]
Is the PresenceMap implementation more complex than is necessary?
See the comments of PR https://github.com/ably/ably-dotnet/pull/206, in particular this from @paddybyers:

> in all the other PresenceMap implementations there's just a single member that indicates that a sync is in progress (eg https://github.com/ably/ably-java/blob/develop/lib/src/main/java/io/ably/lib/realtime/Presence.java#L1013). Why in this case do we need two members (_isSyncInProgress, _initialSyncCompleted) ? I don't see why we can't replicate the functionality without having both.

**Comment by marto83** [comment]
The sync implementation has been updated.
