### ISSUE TITLE
TokenDetails serialisation

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#21]
@yavor87 a customer has today been using the .NET library and used it to generate a token that is sent to the client.  However, we have a serialisation issue and a clientId issue.

Here is a sample of the serialised TokenDetails object:

```
JsonConvert.SerializeObject(tokenDetails) => 
{"token":"REMOVED","keyName":"REMOVED","expires":1449148030,"issued":1449148026,"capability":"{ \"*\": [ \"*\" ] }","clientId":"undefined"}
```

So the obvious problem here is that the serialised expires & issued values should be in milliseconds not seconds since the epoch (unix time).

Also, "clientId" is "unidentified" because sending an empty string clientId failed.  I expect that is due to the fact that a clientId cannot contain an empty string, and must support null values, which when serialised should be omitted.

See https://github.com/ably/docs/commit/145a0f7abe845b43b1bb37d8af891ead39142102 and https://github.com/ably/docs/commit/1ca0fe7504e37590ac689a5b4311e36cf138bb09.

Actions needed ASAP;

- [x] Ensure a serialised TokenDetails and TokenRequest object has the correct timestamp value in milliseconds, plus test coverage
- [x] Ensure a serialised TokenDetails and TokenRequest object supports a null value clientId, which is the default value.  When the value is null, the key and value should be omitted from the serialised object i.e. `{ "token": "x", "expires": 999, "issued:" 999 }`, plus test coverage
- [x] Ensure a serialised TokenDetails and TokenRequest object supports a string value clientId, plus test coverage

**Comment by marto83** [comment]
Matt can you have a look at the pull request that should fix the json issues. 
Can you create a separate issue for MessagePack where all dates are serialised as seconds instead of milliseconds?

**Comment by mattheworiordan** [comment]
I can create a separate MessagePack issue, however can you confirm:

* Is MessagePack not the default?  If it is, surely this will still break if not addressed when requesting a token sending a TokenRequest object?
* What about the TokenRequest object?
