### ISSUE TITLE
Remove System.Net.Http nuget dependency from full .Net Framework build

### ISSUE THREAD

**Issue by akaviny** [ably/ably-dotnet#211]
Using System.Net.Http nuget package causes all sorts of problems when using in .Net 4.6. Microsoft are removing OOB package, preferring the GAC'd version.

See https://github.com/dotnet/corefx/issues/17522 for a post-mortem on the System.Net.Http problems

**Comment by marto83** [comment]
@akaviny Thank you flagging this issue. From version 1.1.15 I'll remove the nuget dependency to System.Net.Http for the .net 4.6.

**Comment by marto83** [comment]
This has been fixed in #381. The full release is coming soon as well.
