### ISSUE TITLE
Disable fallback hosts option - hot fix

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#216]
@withakay would it be possible to prioritise a hot fix for 0.8.* so that a customer of ours using a custom environment can disable fallbacks, or specify them alternatively. See [fallbackHosts attribute in our 1.0 spec](https://docs.ably.io/client-lib-development-guide/features/#TO3k6).

The customer is sending requests to non-EU datacenters now from .NET, which in turn always fails as their account is configured to route traffic only within EU.

Please implement whatever is easiest.  As we are not actively upgrading 0.8 now, we just want a quick and easy fix for this that works.

**Comment by marto83** [comment]
Closing as it has been fixed by this commit: https://github.com/ably/ably-dotnet/pull/217/commits
