### ISSUE TITLE
Add idempotent REST publishing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#237]
See spec at https://github.com/ably/docs/pull/473

Ruby implementation at https://github.com/ably/ably-ruby/pull/165

Whilst this is technically 1.1 functionality, we can add this now so long as idempotent publishing is disabled by default.

**Comment by mattheworiordan** [comment]
The spec is finalised so this is good to go as soon as we can get onto it.

**Comment by sacOO7** [comment]
Reference to respective java implementation - https://github.com/ably/ably-java/pull/435/files

**Comment by sacOO7** [comment]
@marto83 can you confirm if this issue was covered as a part of https://github.com/ably/ably-dotnet/pull/249
I feel some bold connecting dots here.

**Comment by sacOO7** [comment]
It seems it's already covered as a part of old PR https://github.com/ably/ably-dotnet/blob/83101cf093565113df59d5aaf752a1ac26c07a25/src/IO.Ably.Shared/Rest/Channel.cs#L74.
I will see if all test cases are covered. If not, I will try adding missing test scenarios.

**Comment by marto83** [comment]
@sacOO7 I think this is definitely covered and it got automatically enabled with version 1.2. All the test cases are flagged with spec items so it should be easy to see if anything is missing.

**Comment by sacOO7** [comment]
- I was going through the PR, it seems you have fixed some of the code ( changing default true logic to Protocol Version 1.2)
- Also, tests have been modified according to spec : )
