### ISSUE TITLE
Ensure request method accepts UPDATE, PATCH & DELETE verbs

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#246]
This will be hard to test sadly without mocking or sending requests to a non-realtime server, but we should do our best to confirm request support these verbs.

See https://github.com/ably/docs/pull/493

**Comment by withakay** [comment]
@mattheworiordan could echo.ably.io be made support the required verbs?

**Comment by mattheworiordan** [comment]
Yes, this is done now, just waiting for @paddybyers' approval on PR.

Note that you will still need to include a body querystring attribute for all echo requests to `/` using any verb, or request body to avoid getting a 400 missing body response.

**Comment by mattheworiordan** [comment]
@withakay deploying this now, should work in the next few minutes.

```
curl -XDELETE "https://echo.ably.io?body=foo"
curl -XPATCH "https://echo.ably.io?body=foo"
```

**Comment by marto83** [comment]
Tests for this are implemented here: https://github.com/ably/ably-dotnet/pull/238.
