### ISSUE TITLE
IO.Ably.Realtime.RealtimeChannel.PublishImpl

### ISSUE THREAD

**Issue by jsinh** [ably/ably-dotnet#251]
I am getting this exception

```
IO.Ably.AblyException

IO.Ably.Realtime.RealtimeChannel.PublishImpl

Unexpected error :Reason: 
Unable to publish in detached or failed state; 
Code: 40000; HttpStatusCode: (400)
BadRequest; Code: 50000 
Reason: Unable to publish in detached or failed state; 
Code: 40000; HttpStatusCode: (400)BadRequest
```

I am having these exceptions in ASP.NET MVC web project hosted in Azure WebApp

Using `ably.io 0.8.11` nuget package
ASP.NET MVC: `5.2.6`

Need help, thanks

**Comment by withakay** [comment]
@jsinh are you able to reproduce this error? If so can you post up some code / link to a repository to help us investigate?

**Comment by jsinh** [comment]
This is a private code cannot share repo or the entire codebase to reproduce but happens when I host on azure - when I run locally I was not able to see the same. This happens when I try to publish a signal 

Here is the method implementation to send signal which is throwing exception
```
public async Task SendAsync(string senderId, string channelId, object data)
        {
            try
            {
                if (string.IsNullOrEmpty(channelId))
                    return;

                if (null == data)
                    return;

                var tagData = DomainEvent.GetTypeKey(data.GetType());
                if (string.IsNullOrWhiteSpace(tagData))
                    return;

                var signalEntity = new SignalBase
                {
                    DataJson = JsonConvert.SerializeObject(data),
                    UserId = senderId,
                    Tag = tagData
                };

                var signalEntityJson = JsonConvert.SerializeObject(signalEntity);
                var interestedChannel = this.signalClient.Channels.Get(channelId);
                await interestedChannel.PublishAsync(new Message { Data  = signalEntityJson });
            }
            catch (Exception exception)
            {
                this.logger.TrackException(new ExceptionTelemetry { Message = "SignalManager > SendAsync", Exception = exception });
            }
        }
```


@withakay does that help?

**Comment by jsinh** [comment]
I think the three line that are relevant are these: 

```
var signalEntityJson = JsonConvert.SerializeObject(signalEntity);
var interestedChannel = this.signalClient.Channels.Get(channelId);
await interestedChannel.PublishAsync(new Message { Data  = signalEntityJson });

```

**Comment by withakay** [comment]
There is not really enough here to give a definite answer.
The basic problem is your channel is no longer attached, this is probably caused by a connection error that has not recovered. 

It would be good to log the actual channel state and also the connection state when the exception is thrown.

```
this.signalClient.Channels.Get(channelId).State
this.signalClient.Connection.State
```

To gain more insight you could subscribe to channel events and log those

```
// subscribe to connection events
this.signalClient.Connection.On(args =>
{
    Logger.Debug(args.Current.ToString());
    if (args.HasError)
    {
        Logger.Debug(args.Reason.ToString());
    }
});
```

```
// subscribe to channel events
this.signalClient.Channels.Get(channelId).On(args =>
{
    Logger.Debug(args.Current.ToString());
    if (args.Error != null)
    {
        Logger.Debug(args.Error.ToString());
    }
});
```

**Comment by jsinh** [comment]
Thanks,

I will try to capture states when exception happens using 
```
this.signalClient.Channels.Get(channelId).State
this.signalClient.Connection.State
```

and report back

**Comment by jsinh** [comment]
I went back to collect some observations last couple of days. Seems like in a web application if we keep the `signalClient` or `channel` open or initialized for long it goes into some inactive or passive state.

So now I am initializing this client and channel on each call to keep it fresh on the channel and/or client connection - I do not see the above errors anymore in our test environment.

On latest NuGet for Ably in this case `0.8.11`

Thanks for all the help

**Comment by jsinh** [comment]
Thanks for that suggestion, it works too!!
