### ISSUE TITLE
Error from authUrl should give some indication that it's from the authUrl

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-dotnet#252]
Customer [here](https://stackoverflow.com/questions/52259438/get-unknown-error-when-connecting-creating-a-connection-using-ably-io) getting an `Unknown error; Code: 500; HttpStatus Code: (404)NotFound` error, presumably from their authUrl.

It would be helpful if that error would indicate that it's a problem from the AuthUrl, so the dev knows where to look. Per https://docs.ably.io/client-lib-development-guide/features/#RSA4c , it should ideally be something like `{"message":"Client configured authentication provider request failed","code":80019,"statusCode":401,"cause":{"message":"XHR error occurred (event type: error)","code":40170,"statusCode":401}}`, but really anything that just mentions authUrl or 'client configured authentication provider' and the right code would be an improvement (eg if you haven't implemented `cause` yet don't worry about that bit)

**Comment by marto83** [comment]
@SimonWoolf This has been implemented in: https://github.com/ably/ably-dotnet/pull/212. Closing for now.
