### ISSUE TITLE
Should the AblyRest class be an injected singleton?

### ISSUE THREAD

**Issue by grahambunce** [ably/ably-dotnet#260]
Our Peak Connections much higher than expected. After a code review I identified that we were using the AblyRealTime class in our stateless server application to publish messages to our JavaScript based client.

From the Ably website it appears that this is incorrect (and probably a reason for our peak connections). We have changed our server code to use the AblyRest client.

What is still unclear from the Ably website documentation and the Github code if the AblyRest client should be used as an injected singleton; i.e. it appears to have it's own Ably HTTP Client class, which wraps a .NET HTTP Client. 

The .NET HTTP Client is designed to be an injected singleton.

Therefore should the AblyRest client also be an injected singleton or is creating an instance of this on each Publish call "safe" and make most efficient use of Ably connections?

**Comment by withakay** [comment]
Hi,

> is creating an instance of this on each Publish call "safe" and make most efficient use of Ably connections?

Each time you create a new instance of `AblyRest` (or indeed `AblyRealtime`, as internally that leverages `AblyRest`) a new instance of HttpClient is also instanced, so if you have concerns about creating too many instances of HttpClient those same concerns should also apply to `AblyRest` and `AblyRealtime`. Additionally, as `AblyRealtime` holds a stateful connection to the Ably service creating a new instance (and thus connection) for each publish is very much not recommended.

A you suggest, passing a static/singleton instance of `AblyRest` (or `AblyRealtime`) in to your class constructor is good option to reduce resource usage.

**Comment by grahambunce** [comment]
@withakay thanks for the update. So, just to be clear, if we use AblyRest then, ignoring any concerns about HttpClient, this class will not the the cause of any PeakConnection spikes whereas our use of AblyRealtime is a likely source if we are instantiating an instance on every publish call.

I.e as per the docs, AblyRest is the recommended class to use for high volume stateless applications (e.g) responding the back end message bus events.

**Comment by withakay** [comment]
@grahambunce 
From what you have said about your application `AblyRest` sounds like the better fit, but creating a new instance of `AblyRest` every time you handle a message from your service bus could cause you issues in the same way that creating an `HttpClient` each time might, this really comes down to the volume of messages you are dealing with, the most resource friendly option is to have a static `AblyRest` instance that you call upon somehow. If you are in a truly stateless environment (i.e. a serverless environment like AWS Lambda) that might not be possible.

[This blog post](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/) has some great information on the potential issues with creating a lot `HttpClient` instances that could similarly be applied to `AblyRest`

**Comment by grahambunce** [comment]
@withakay Thanks - that's what I thought. One last query; in our Ably Dev Console we see Connection Open / Connection Closed events, e.g. whenever the browser is refreshed or a user navigates away from the page that the JavaScript client is enabled that subscribes to channels.

Do you know if *each* of these connection events trigger a count towards the "peak connections" count? I'm struggling to understand exactly how that's calculated and it's the one thing we're hitting limits on for our current licence.

**Comment by grahambunce** [comment]
@withakay ok thanks, this is what I thought.
