### ISSUE TITLE
Idempotent publishing is not enabled in the upcoming 1.1 release

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#275]
See https://github.com/ably/docs/pull/568

We must ensure that that idempotent is not yet enabled by default and requires the user to explicitly enable.

Related to #237

**Comment by mattheworiordan** [comment]
@withakay is this done?

**Comment by withakay** [comment]
No, Idempotent publishing is enabled by default in 1.1+

https://github.com/ably/ably-dotnet/blob/8e696a3ced1ab69aac871f74a992c7b8bbbbe526/src/IO.Ably.Shared/ClientOptions.cs#L268

Should I release an update with that changed to 1.2?

**Comment by paddybyers** [comment]
It should be on by default only in 1.2+ so yes, I think we'd need to have a release to fix that :(

**Comment by withakay** [comment]
@paddybyers 

I will get a release out today, what are expected side effects of this being enabled?

**Comment by mattheworiordan** [comment]
> what are expected side effects of this being enabled?

Nothing really, but we wanted to give developers compatibility in the 1.* releases

**Comment by withakay** [comment]
Fixed by PR #327
