### ISSUE TITLE
Unnecessary disconnect/connect cycle on token authentication

### ISSUE THREAD

**Issue by akaviny** [ably/ably-dotnet#276]
I'm using token authentication, generating a TokenRequest for the AuthCallback property on ClientOptions with TTL of 2 hours. In my debug logs, I've noticed that the connection is dropped just prior to the token request call. 
On successful authentication, the connection is once again established, at which point I re-attach all open channels on the Connected event. This seems unnecessary to me; is it a bug, or is this by-design? Shouldn't there be a small period before token expiry, say 1 minute, when the token can be renewed whilst still being connected? If it then fails, run down the time and disconnect as usual.

I'm using Nuget v0.8.11.

**Comment by akaviny** [comment]
I think this disconnect/connect cycle causes intermittent problems; sometimes, on re-attaching the open channels, as recommended by the documentation, the attach fails.

_12:21:34.762 : [Debug] : Connection: Disconnected
12:21:34.763 : [Debug] : Connection: Connecting
12:21:34.784 : [Debug] : [019a854c-116b-4f6e-aeda-50e6ad826e0f] => 'https://xxxxxxxxxx.execute-api.eu-west-1.amazonaws.com/dev/notifications.getTokenRequest'
12:21:35.407 : [Debug] : [019a854c-116b-4f6e-aeda-50e6ad826e0f] <= OK
12:21:36.731 : [Debug] : Connection: Connected
12:21:36.732 : [Debug] : e885af72-e7ac-41e8-956f-a295e5312854:634b0f4c-46ad-4f0b-b348-90e8514e7c3c: ReopenAsync
12:21:36.733 : [Warning] : 11:21:36.733 **Force detaching all attached channels because the connection did not resume successfully!**
12:21:36.736 : [Debug] : e885af72-e7ac-41e8-956f-a295e5312854:634b0f4c-46ad-4f0b-b348-90e8514e7c3c: **Attached=>Detached Reason: Unable to recover connection (connection expired). (See https://help.ably.io/error/80008 for help.); Code: 80008; HttpStatusCode: (404)NotFound**
12:21:36.737 : [Debug] : e885af72-e7ac-41e8-956f-a295e5312854:634b0f4c-46ad-4f0b-b348-90e8514e7c3c: re-attaching
12:21:56.819 : [Debug] : e885af72-e7ac-41e8-956f-a295e5312854:634b0f4c-46ad-4f0b-b348-90e8514e7c3c: Attaching=>Attached 
12:21:56.820 : [Debug] : Client '2bf78160-1e45-4a00-9b17-9afc48845de0:msft [1C1Y5-mU-l]' on channel 'e885af72-e7ac-41e8-956f-a295e5312854:634b0f4c-46ad-4f0b-b348-90e8514e7c3c': Present
02:21:36.402 : [Debug] : Connection: Disconnected
02:21:36.403 : [Debug] : Connection: Connecting_

When the connection fails, I retry after 20 seconds (timestamps 12:21:36.737 and 12:21:56.819), which then recovers, but all this seems unnecessary, if disconnection didn't happen in the first place. 

I understand things can go wrong, and disconnection is warranted, but not for refreshing the access token.

Our account name is 'Thermo Fisher Scientific'.

**Comment by paddybyers** [comment]
This library is in the process of being upgraded to the 1.0/1.1 specification which does support inband token renewal.

We will update here when we have an ETA for that release.

cc @withakay

**Comment by withakay** [comment]
v1.1.1 released today
