### ISSUE TITLE
Add documentation to README about which platforms are supported 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#28]
Such as:
- Version of .NET
- Version of Xamarin
- Versions of Windows, Desktop, Store etc.
- Versions of Windows Phone, Silverlight, WinRT etc.
- Mono, Unit3D, IoT etc.

**Comment by mattheworiordan** [comment]
Have previously discussed:

> * .Net: 2.0, 3.5, 4.0, 4.5
> * Silverlight: 4, 5
> * Xamarin ios & android
> * Windows Store 8, 8.1, 10
> * Windows Phone (Silverlight)  8.0
> * Windows Phone (Windows Runtime) 8.1

**Comment by withakay** [comment]
Platform support is included in the readme, so I am closing this.
