### ISSUE TITLE
Class & namespace naming

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#29]
I believe the current naming is incorrect and inconsistent with the other client libraries.

The way the client libraries should be referenced should is:

```
Ably.Rest
Ably.Realtime
```

whereas it appears to be currently

```
Ably.RestClient
Ably.AblyRealtime
```

I could be wrong of course ;)

**Comment by paddybyers** [comment]
FWIW the java package/class names are

    io.ably.lib.rest.AblyRest
    io.ably.lib.realtime.AblyRealtime

**Comment by mattheworiordan** [comment]
> FWIW the java package/class names are
> 
> ```
> io.ably.lib.rest.AblyRest
> io.ably.lib.realtime.AblyRealtime
> ```

Mmm, not ideal really, why is that?  Could we not reduce the duplication of the type and have:

```
io.ably.lib.AblyRest
io.ably.lib.AblyRealtime
```

or perhaps even

```
io.ably.Rest
io.ably.Realtime
```

**Comment by paddybyers** [comment]
> why is that?

`lib` because it's a library.
`rest` and `realtime` are packages so that there is a clear separation between those parts of the library, and also so that we can have classes called `Channel` or `Presence` without having to disambiguate in the class name.

As packages are never referenced except in import statements, there is no merit in having shallower but ultimately inflexible package hierarchies.

**Comment by mattheworiordan** [comment]
> lib because it's a library.

Ok, fine, but arguably what else would it be?

> rest and realtime are packages so that there is a clear separation between those parts of the library, and also so that we can have classes called Channel or Presence without having to disambiguate in the class name.

Fine, but referencing `io.ably.lib.Rest` does not prevent if from using `io.ably.lib.rest.Channel` and `io.ably.lib.Realtime` from using `io.ably.lib.realtime.Channel` so I am not clear on why it's a problem.

> As packages are never referenced except in import statements, there is no merit in having shallower but ultimately inflexible package hierarchies.

Well consistency is nice between the client libraries as much as possible

**Comment by paddybyers** [comment]
> what else would it be?

An example app? `io.ably.examples.Chat` ?

> referencing io.ably.lib.Rest does not prevent if from using io.ably.lib.rest.Channel and io.ably.lib.Realtime from using io.ably.lib.realtime.Channel so I am not clear on why it's a problem.

If you're going to have a `rest` package to contain the REST API, it makes no sense to have all classes apart from the main one in that package; then you'd be forced to import that separately from the rest of the API and it's needlessly messy.

Typically someone will do

````
import io.ably.lib.rest.*;

AblyRest ably = new AblyRest(...);
````

> consistency is nice between the client libraries as much as possible

of course but things still need to be natural and idiomatic in the language in question.

**Comment by mattheworiordan** [comment]
Ok, fine, thanks for clarifying.

We will need to figure out what is idiomatic for .net then and simply ensure it's consistent where possible.

**Comment by mattheworiordan** [comment]
@Const-me what would you suggest here for .NET that is more idiomatic with .NET but as consistent as possible with Ably?

**Comment by Const-me** [comment]
Never heard of any naming conventions regulating assembly names.
However, here’s my opinion about that:
(1)	I have never seen any .NET library with “.Lib” anywhere in assembly name of namespace.
(2)	Assembly name doesn’t matter much. Average developer won’t see that once, he’ll right click on references, manage nuget packages, search, add.
(3)	The classes name inside the namespace are better to be reasonable unique. Average developer is lazy, he won’t type namespace names more then once, just type “using xx.yy.uu” at the beginning of the source file. If classes inside the namespace are named too generically, there will be a name conflict. I personally had problems with 3rd party developers, and even different teams at Microsoft, naming their stuff Point, Rectangle, Stream, List. IMO identifiers like Rest and Realtime could be too generic.

**Comment by mattheworiordan** [comment]
Thanks @Const-me 

So what about the following

```
using io.ably

function main() {
  var realtime = new AblyRealtime(opts)
  var rest = new AblyRest(opts)
}
```

OK?

**Comment by Const-me** [comment]
Yep, something like that.
I'd only make the namespace name IO.Ably, or better AblyIO

**Comment by mattheworiordan** [comment]
Lets go with `IO.Ably` please

**Comment by marto83** [comment]
The namespace is now IO.Ably. Closing this issue.
