### ISSUE TITLE
PaginatedResource API change 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#3]
@marto83 and @yavor87, please see https://github.com/ably/ably-js/issues/28.

We are trying to consolidate how we provide Pagination, and unfortunately this means we should change the .NET api.  It's not critical, and lower priority, but we should do it.

@marto83, Paddy says his previous API was more in-line with what we have proposed in https://github.com/ably/ably-js/issues/28, but he then followed what you did in the .NET lib. I personally prefer the new proposed solution and that is pretty much how it is implemented now in Ruby, however I'm interested to know why you preferred the .NET API.  Can you advise or contribute to that ticket?

@yavor87 if you have any feedback please shout.

**Comment by marto83** [comment]
There were a few things that bothered me with the previous implementation.
1. The result was trying to do two much - it was both holding the result from the server and at the same time it knew how to query the server for more. 
2. You were hiding calls to the server from within the result so an unsuspecting dev could be making hundreds of calls itterating through the returned values.
3. Stops you from being able to store the results in any kind of out of process cache as when you retrieve the object back it will no longer have a valid reference to the service. 

On the flip side for some libraries it does make sense to have an easy way to iterate. For example js in the browser. 

I think we should keep the library simple in that sense and let developers get to know the responses from the ably servers. At the same time you have a separate library with ably enhancements and that could be one of them. At least then developers will know what is basic lib provides and what is an enhancement.

**Comment by mattheworiordan** [comment]
@marto83 your point 3 is quite valid, but if we introduce `PaginatedResource#items` then we don't have to worry about that in reality because hopefully people would be smart enough to serialise that array instead.  Also, your point about the reference not working when you retrieve the object back, that applies whether you pass the URL to the history method or call it directly, either way it will not work.

I do think if our goal is API simplicity, the proposed approach in https://github.com/ably/ably-js/issues/28 is my preferred option.

Thanks @marto83 and congrats on your new baby!

**Comment by marto83** [comment]
Thanks @mattheworiordan. 

What you say does make sense. It does make using the api easier to use so you don't have to think about passing it back to the service. I guess it reminds me of active record and I've never liked it.

It shouldn't be a huge change.

**Comment by mattheworiordan** [comment]
@marto83 I wanted to see what was involved so implemented it in a feature branch, didn't take very long, see https://github.com/ably/ably-ruby/tree/new-paginated-resource.  I find the API is now a bit more verbose, but equally I think conceptually it's a lot clearer what developers are dealing with when accessing paged results.

**Comment by mattheworiordan** [comment]
I am closing this as this is covered in a new issue being created now
