### ISSUE TITLE
presence myMembers map implementation

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-dotnet#302]
Hi @withakay, noticed you're nearing 1.1 but the rtp17b line on the spreadsheet for ably-dotnet is empty. Just to make sure you know, the server assumes that any client library that sends `v=1.1` implements the local presence map up to the 1.1 spec, so that's a requirement for releasing 1.1. See https://github.com/ably/docs/pull/446 for more info. Thanks

**Comment by withakay** [comment]
I believe there is a test that covers this [here](https://github.com/ably/ably-dotnet/blob/c4a35caaebcc61121b190e31cbac6f937b1f76eb/src/IO.Ably.Tests.Shared/Realtime/PresenceSandboxSpecs.cs#L268), it is just incorrectly labelled

**Comment by withakay** [comment]
There is a PR for this issue here: https://github.com/ably/ably-dotnet/pull/310
