### ISSUE TITLE
JsonReader error on Xamarin

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#325]
Reported error from customer:

```
Unexpected error :Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 278.
```

I will ask for more details, but understand this was on iOS with Xamarin Forms, .NET lib 1.1.1

**Comment by santihcc** [comment]
We are trying to connect to ably by using a Token.
The token is issued by our own server at a given auth url.
The code to initialise and connect is the following:

            try
            {
                var options = new ClientOptions
                {
                    AuthHeaders = new Dictionary<string, string> { { "Authorization", bearer } },
                    AuthUrl = new Uri("https://<auth-url>/api/ably"),
                };

                _ablyRealtime = new AblyRealtime(options);

                _ablyRealtime.Connection.On(args =>
                {
                    var currentState = args.Current; //Current state the connection transitioned to
                    var previousState = args.Previous; // Previous state
                    AblyMessages.Insert(0, $"Connection State: {currentState}");

                    var error = args.Reason; // If the connection errored the Reason object will be populated.
                    if (error != null)
                        AblyMessages.Insert(0, $"Connection Error: {error.Message}");
                });

                _ablyRealtime.Connection.ConnectionStateChanged += (sender, e) =>
                {
                };
            }
            catch (Exception e)
            {

            }

The AblyRealtime is initialized. Then the connection object changes state to connecting.
Running on both iOS or Andorid is OK.

Then the connection object should try to change state to connected but
On iOS we've got the following error:
`Unexpected error :Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 278.`
On Android the application crashes straight away. No error is caught in the try-catch wrapping up the code either.

The connection with our auth server looks to be fine as well as data is returned back. We also tested the server by calling it from a different application and the data is returned as expected.

**Comment by mattheworiordan** [comment]
@santihcc I believe we may have a fix for this. We'll be in touch soon.

**Comment by withakay** [comment]
This issue was down to an incorrectly formatted TokenRequest string be return from an ASP.Net MVC Controller

```

**Comment by withakay** [comment]
@santihcc Could you let us know if this fix worked for you? Thanks

**Comment by withakay** [comment]
Assuming fixed as no response from OP. Please reopen if issue is still present.
