### ISSUE TITLE
Presence not entered on recovered connection

### ISSUE THREAD

**Issue by bchenhs** [ably/ably-dotnet#329]
OS: Windows 10 (running in VMWare Fusion)
.NET: 4.7.2
Context: C# Windows Application targeting .NET 4.6
Ably Client: 1.1.1

When using the Realtime client, we were able to maintain presence on a channel when a connection is lost and recovered. Are there certain practices or caveats on the client side (or server side) that we need to be aware of?

Reproduce steps:
- Instantiate AblyRealtime with the AuthCallback option
- On Connected, subscribe to channel and enter presence
- Put PC to sleep for a minute or longer, query presence through rest API and confirm it is no longer listed
- Wake PC and wait for connection to recover (either through automatic recovery, or by calling Connect again*)
- Query for presence, and there are no longer any presence on the recovered connection (even though the connection state is "Connected" and Channel state is "Attached")

Note* When calling Connect to manually to recover, we re-subscribe to the channel and enter presence on Connected event.

**Comment by mattheworiordan** [comment]
@withakay please see log at https://go.ably.io/yf23432erwfasd (requires login)

**Comment by withakay** [comment]
Update: We thought we had a fix for this in the shape of PR #350 (release 1.1.9-beta1) but the customer is still reporting the issue, so we need to keep investigating.

**Comment by marto83** [comment]
This will be fixed in 1.1.12 which will be released shortly
