### ISSUE TITLE
Per-instance loggers

### ISSUE THREAD

**Issue by Const-me** [ably/ably-dotnet#33]
It's desirable to be able to have different loggers for different ably instances.

See also (RSC4) A custom logger can be provided in the constructor

**Comment by marto83** [comment]
I think this is a minor nice to have and in most cases you won't have multiple instances running in the same environment. 
Closing for now. If requested we can reopen it later.

**Comment by mattheworiordan** [comment]
Ok, but can you set the log level in ClientOptions when instanced like all other client libraries?  If not, we need to raise an issue for that.

**Comment by withakay** [comment]
Whilst the OPs requests is now technically possible, the feature is not exposed publicly and based on internal discussions some time ago, it seems unlikely that this will happen, so I am going to close this for now. Feel free to re-open if you feel this is an important feature.
