### ISSUE TITLE
Detecting network availability changes

### ISSUE THREAD

**Issue by withakay** [ably/ably-dotnet#331]
Currently the dotnet library does not detect network changes in places where it could. There is an internal method `NotifyOperatingSystemNetworkState` on the `Connection` class that is only referenced by Unit Tests.

This method should be wired up to network change events where possible. 

There is a static event for this `System.Net.NetworkInformation.NetworkChange.NetworkAvailabilityChanged` that is supported in all our targets except UWP and .NET Standard 1.4. UWP there is a similar event that can be hooked into `NetworkInformation.NetworkStatusChanged`, for .NET Standard 1.4 there is no option built in. Since Xamarin and .Net Core 2 both support .NET Standard 2.0  the lack of an option for .NET Standard is a minor issue that I think we can ignore IMO.

For each platform version we target we have project that imports the shared code (IO.Ably.Shared) and additionally contains a `Platform.cs`, I propose that we add a static constructor to this class to wire up the Network Change events

```
static Platform()
{
    NetworkChange.NetworkAvailabilityChanged += (sender, eventArgs) =>
        Connection.NotifyOperatingSystemNetworkState(eventArgs.IsAvailable ? NetworkState.Online : NetworkState.Offline);
}
```

**Comment by marto83** [comment]
Closing as it has been implemented.
