### ISSUE TITLE
Resuming after Windows has been asleep (.Net Framework)

### ISSUE THREAD

**Issue by withakay** [ably/ably-dotnet#332]
A follow on to #331 and related to an issue a user is seeing.

In my testing when a program is running that is connected to a channel with presence entered, when windows is put to sleep for several minutes and then resumed the ably connection is not resumed, there is nothing logged the realtime library simply does nothing. The app is still running in the console and can respond to input 

There is no xplat way to detect sleep/resume or start/stop, but for .NET Framework (Windows) there is `SystemEvents.PowerModeChanged`. Wiring up the Suspend and Resume events to then tell ably the network off and on line causes the program to resume as one might expect.

```
switch (eventArgs.Mode)
{
    case PowerModes.Suspend:
        Connection.NotifyOperatingSystemNetworkState(NetworkState.Offline);
        break;
    case PowerModes.Resume:
        {
            if (NetworkInterface.GetIsNetworkAvailable())
            {
                Connection.NotifyOperatingSystemNetworkState(NetworkState.Online);
            }

            break;
        }
}
```

**Comment by akaviny** [comment]
This issue is a little more involved, unfortunately. 

On a Windows Service, `SystemEvents.PowerModeChanged` won't be raised, unless a message pump is available (hidden Window, or manually setting the **Allow service to interact with desktop** on the service log on tab).

The recommended way for services is via `ServiceBase.OnPowerEvent`. 

So, I'd suggest allowing clients to hook up their own handler, and exposing a way of notifying of network changes.

**Comment by withakay** [comment]
> So, I'd suggest allowing clients to hook up their own handler, and exposing a way of notifying of network changes.

This may be an option, but we are aim to have the library 'do the right thing' without needing to be specifically aware of the power status off the OS

**Comment by akaviny** [comment]
An option would be to expose a property on the connection, e.g., an interface, `IPowerEventSource`, with a default implementation, `DesktopPowerEventSource`, using the `SystemEvents.PowerModeChanged`.

This can then be replaced by a client running in a different environment, e.g., `WindowsServicePowerEventSource`. 

It would also give you the benefit of switching in a unit testable implementation.

**Comment by withakay** [comment]
I agree with your point, but the basic premise that the library needs to be aware of the power status I am not sure is necessarily correct, as far as the library is concerned if a system is in a paused power state then that can just be seen as a disconnection.

**Comment by tomczoink** [comment]
<div>Agent Tom Camp linked Freshdesk ticket <a href="https://ably.freshdesk.com/a/tickets/100723">100723 </a>for this issue</div>

**Comment by marto83** [comment]
@akaviny just to let you know we are going to look at exposing a way for clients to notify the library. There are too many different ways this can happen on different .net platforms. I've linked the ticket above and will close this one
