### ISSUE TITLE
Disconnect event not fired and will not connect after explicit disconnect

### ISSUE THREAD

**Issue by ndastur** [ably/ably-dotnet#360]
Calling  ```RealtimeObj.Close();``` does not result in a disconnect event being fired. And if I then call ```RealtimeObj.Connect();``` after the explicit disconnect a connection is never re-established. The connection state remains as "Closed"

**Comment by marto83** [comment]
Hi @ndastur. 
When you call `Close()` the connection state will transition to `Closing` and then `Closed`. The connections state will not become `Disconnected`. 

If you call `Connect` straight after you call `Close` the connection will still be in a `Connected` state so  nothing will happen. That's probably not what is happening in your situation. Could you share a small snippet reproducing the issue? 
What is the environment under which you are running the application?

**Comment by ndastur** [comment]
Hi @marto83 thanks for the info. Running on Xamain .Net

Calling ```Close()``` does not result in a connection state change being fired at all and the connection then seems to be stuck in the closed state. The channel state events are fired.

```
Hospify.AblyGateway: incoming ch state from: Detaching to: Detached
Hospify.AblyGateway: incoming ch state from: Attached to: Detaching
Hospify.AblyGateway: incoming chat channel state detached
Hospify.AblyGateway: current connection state: Closed
Hospify.AblyGateway: Connecting ...
```
Nothing happens here. You can see on the penultimate line the connection is in a closed state prior to trying to connect again. The connect and disconnect code is very simple.

```
public async Task Connect()
        {
            try
            {
                Debug.WriteLine($"{Tag}current connection state: {RealtimeObj.Connection.State.ToString()}");

                if (RealtimeObj.Connection.State != ConnectionState.Connected || RealtimeObj.Connection.State != ConnectionState.Connecting)
                {
                    Debug.WriteLine($"{Tag}Connecting ...");
                    RealtimeObj.Connect();
                }
                else
                {
                    Debug.WriteLine($"{Tag}already connected ...");
                }
                Debug.WriteLine($"{Tag}current connection state: {RealtimeObj.Connection.State.ToString()}");
            }
            catch (Exception e)
            {
                Logger.TrackException(e, Tag);
                Debug.WriteLine(Tag + "Connect failed. " + e.Message);
                throw;
            }
        }

        public void Disconnect()
        {
            try
            {
                if (_realtimeObj.IsValueCreated)
                {
                    _removeConnectionStateListeners();
                    RealtimeObj.Close();
                }
            }
            catch (Exception e)
            {
                Logger.TrackException(e, Tag);
            }
        }

private void _connection_ConnectionStateChanged(object sender, ConnectionStateChange e)
{
     Interlocked.CompareExchange(ref OnConnectionStateChange, null, null)?.Invoke(this, e);
}
```

**Comment by marto83** [comment]
@ndastur are you still experiencing this issue?
