### ISSUE TITLE
Improve CI testing process

### ISSUE THREAD

**Issue by marto83** [ably/ably-dotnet#362]
Ensure the test suite is run on the following platforms

* dotnet core
* NET Framework 4.7
* Xamarin iOS
* Xamarin Android

**Comment by paddybyers** [comment]
For iOS and Android we need to confirm what platform versions we are targeting.

In general, our platform support policy for consumer devices will provide support for reasonable backwards compatibility so we capture a large fraction of the existing device population, provided we can do so without making significant architecture compromises or generating an unreasonable amount of extra work. Very old versions that are barely used won't be supported in general.

For CI, then we ought routinely to test against:
- the "current" release - ie the latest platform release that has mainstream adoption;
- the oldest platform version we claim to maintain support for.

For Android, looking at https://developer.android.com/about/dashboards, I would say that the current release with mainstream adoption is now platform version 28 (Pie) and the oldest version with usage that merits support would be platform version 19 (KitKat). (That's getting on for 6 years old, which is scary.)

For server platforms, we can deprecate a lot more aggressively. We will look at usage stats from our own records to decide what we do and don't support.

@codemerx please capture in this issue any conclusions you make about the different variants of .NET platforms that we need to support.

**Comment by marto83** [comment]
This is partially done:
We have an automated test suite running for
* dotnet core
* NET Framework 4.7

We still need one running on a xamarin emulator at least.

**Comment by QuintinWillison** [comment]
I'm just collecting notes from Asana tasks before we retire that system.

From [this ticket](https://app.asana.com/0/623496170845722/623496173260592) it looks like we were talking about setting up CI on appveyor and that Jack had said to Matt on 30 Aug 2017:

> I think this will be more complicated than it might first appear because VS Mobile Center does not support xUnit.

This information is probably very out of date but recording here just in case it's relevant when we come to work on this issue.

**Comment by QuintinWillison** [comment]
Further detail (Asana notes collection) from [this ticket](https://app.asana.com/0/623496170845722/623496173041197) regarding **Portable test suite**:

> Refactor tests so that they can be run against .NET framework, core and Mono.  We'll defer Xamarin on-device testing until later.

> Tests should be able to run on core & Mono

> CI should build against all environments
