### ISSUE TITLE
Xamaring Android when full linking is enabled fails to request token

### ISSUE THREAD

**Issue by marto83** [ably/ably-dotnet#375]
We get an error Request mac not provided

![image](https://user-images.githubusercontent.com/150508/66142072-b86a3c00-e5fc-11e9-833b-781061bf79ac.png)

**Comment by ndastur** [comment]
Any update to this?

**Comment by marto83** [comment]
@ndastur I've tried to reproduce the same issue but without success. Do you still experience it?
The only thing that changed for me is that I upgrade my version of Visual Studio to 2019 and with that the Xamarin tools version updated as well. 
I don't see the issue on: V2019 16.3.2
Xamarin - 16.3.0.274
Xamarin.Android SKD 10.0.0.43

What is your setup?

**Comment by marto83** [comment]
The other option you have is to exclude the Ably dll from being fully linked. I did a test locally and the apk only grows by amour 400kb. 

By the way, which distribution of Ably do you use - Net Standard or the Android specific one?

**Comment by marto83** [comment]
@ndastur Did you try again running your app with full linking enabled. I'm going to close this issue but feel free to reopen it if the above didn't resolve the problem.
