### ISSUE TITLE
On unhandled exception should not put channel into failed state

### ISSUE THREAD

**Issue by marto83** [ably/ably-dotnet#378]
If there is an unhandled exception it should log an error message and leave the channel in its current state

**Comment by mattheworiordan** [comment]
@marto83 this is described in https://docs.ably.io/client-lib-development-guide/features/#RSC20 btw.  Do you know if the SDK claims to support RSC20?

**Comment by marto83** [comment]
This has been implemented for the presence case but I'll leave it open to make sure I add a test for RSC20.

**Comment by marto83** [comment]
Create a separate issue to implement RSC20 - #389
