### ISSUE TITLE
Minor Crypto spec updates

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#38]
The specification is now finalised for the Crypto changes.

Please see ably/docs#89

We need to ensure this library complies with the changes described in the PR

**Comment by marto83** [comment]
I think this can be closed. I'll try and find the commit.

**Comment by marto83** [comment]
I double checked and this is definitely implemented in https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Encryption/Crypto.cs
