### ISSUE TITLE
Could not load type of field IO.Ably.Transport.ConnectionManager

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#384]
Customer reported:

> When trying to install your NuGet package in a NET Standard class library which I'm linking from a Xamarin Android project... I'm getting the following exception when I try to instantiate an AblyRealtime. I've tried everything I can think of; nuked packages/bin/obj, uninstalled/reinstalled the package, etc... but I'm stuck. Any help would be appreciated! Thanks

> Could not load type of field 'IO.Ably.Transport.Connection
Manager:<PendingMessages>k__BackingField' (2) due to: Could not resolve type with token 010000a6 from typeref (expected class 'System.Collections.Generic.Queue`1' in assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') assembly:mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e type:System.Collections.Generic.Queue`1 member:(null)

The customer did resolve the issue though:

> Thanks for getting back to me. It seems like it was related to your NuGet package being built with Visual Studio 2019 and my app being built with Visual Studio 2017...
> Here's the SO post that pointed me in the right direction: https://stackoverflow.com/a/58064929/2012597

Internal conversation: https://app.intercom.io/a/apps/ua39m1ld/inbox/inbox/conversation/24499044632

**Comment by marto83** [comment]
I've updated the readme to alert people and let them know how to work around the issue. I have 2 options:
1. To remove references to Queue and replace them with a something that is not problematic.
2. Go back to building the library with the older MsBuild. I'll have to check if this is not going to create new issues.

**Comment by mattheworiordan** [comment]
Ok, thanks, keep me / this issue posted.
