### ISSUE TITLE
Send unhandled exceptions to Ably exception service - RSC20

### ISSUE THREAD

**Issue by marto83** [ably/ably-dotnet#389]
Implement the spec item for unhandled exceptions and forward them to the internal exception service as described in the spec: https://docs.ably.io/client-lib-development-guide/features/#RSC20

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-558) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
We deprecated [`RSC20`](https://sdk.ably.com/builds/ably/specification/main/features/#RSC20) as this functionality falls outside scope of concern for the SDK (whether or where exceptions are reported is an application concern).
