### ISSUE TITLE
Connection moves to Failed when there is no internet connection

### ISSUE THREAD

**Issue by marto83** [ably/ably-dotnet#402]
A customer reported the following:
> when i disconnect my computer from the internet, the ably library switches to Failed state with a BadeGateway exception, while giving me this link(https://support.ably.io/support/solutions/articles/3000092531). According to docs, or atleast that's how I understand it, Failed state should only occur on major errors, but a user loosing its internet connection is a totally valid scenario. 

After doing some manual tests, I managed to recreate the issue which happens when the socket connection is initialised.

**Comment by QuintinWillison** [comment]
[internal ticket](https://ably.freshdesk.com/a/tickets/105554)
