### ISSUE TITLE
Cumulative retry timeout of 10s was exceeded

### ISSUE THREAD

**Issue by marto83** [ably/ably-dotnet#404]
Customers have reported the following message appearing in the logs `Cumulative retry timeout of 10s was exceeded`. The problem with the error message is that it appears before any retries have happened. 

After some investigation it appears that as of 1.1.15 I have a wrong default value for httpRequestTimeout. I've set it to 15s instead of 10s. The issues with that is that it completely stops the internal retry mechanism.

**Comment by marto83** [comment]
A workaround for this issue is to set `HttpRequestTimeout` in the client options when initialising the library. This will insure that when a timeout happens it will be correctly retried.

**Comment by QuintinWillison** [comment]
[internal ticket](https://ably.freshdesk.com/a/tickets/105607)
