### ISSUE TITLE
Signed version of the .Net Standard 2.x assembly

### ISSUE THREAD

**Issue by akaviny** [ably/ably-dotnet#412]
The .Net Framework version of the assembly is signed, but not the .Net Standard 2.0 assembly

**Comment by akaviny** [comment]
Microsoft are still recommending signing of assemblies. [Strong Naming](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming).
It seems inconsistent to have signed and unsigned versions of the same library.

Here's Marc Gravell's take on signing:- [Strong Naming](https://twitter.com/marcgravell/status/1037071806002352128?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1037077132810366976&ref_url=https%3A%2F%2Fwww.pedrolamas.com%2F2018%2F09%2F11%2Fstart-strong-naming-your-assemblies%2F)

**Comment by marto83** [comment]
Thanks for spotting this issue @akaviny. I'll get a signed version of the .netstandard package release this week.

**Comment by marto83** [comment]
I've signed the net standard dll as well and released 1.1.20. It should be in nuget shortly.

**Comment by akaviny** [comment]
Great, thanks for the quick update
