### ISSUE TITLE
addRequestIds client option

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-dotnet#423]
Conforming to [RSC7c](https://docs.ably.io/client-lib-development-guide/features/#RSC7c) and [TO3p](https://docs.ably.io/client-lib-development-guide/features/#TO3p).

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-109) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Reference Java implementation - https://github.com/ably/ably-java/pull/576
