### ISSUE TITLE
Update documentation about using alternative websocket libraries

### ISSUE THREAD

**Issue by marto83** [ably/ably-dotnet#425]
The current readme points to a different repo with an implementation for websocket4net. The implementation no longer works due to changes to the ITransport interface.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-108) by [Unito](https://www.unito.io)

**Comment by marto83** [comment]
I've updated the code from the repo in this gist https://gist.github.com/marto83/0c4a04c136675bf4928557c120ec6162. I've tested it in a console app and it works as expected.

**Comment by tomkirbygreen** [comment]
Closing this since the underlying need for alternative web-socket library support was to run on Windows 7 which we no longer support.
