### ISSUE TITLE
Review need for third party manifest file in our source tree

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-dotnet#428]
I am working on [our plan](https://docs.google.com/document/d/1fhbQWQaoIe-urizplgNtT4WxPRgoUDchg-VIBnAEqA0/edit?usp=sharing) (internal link) to rename `master` branches to `main`, as well as to remove this terminology wherever possible.

Why is [this file](https://github.com/ably/ably-dotnet/blob/d099e36bb49b4d9baa439092986f57d47decb975/tools/psake/psake.psd1) in our repository? Can it be refactored or replaced in order to remove references to "master"?

**Comment by sacOO7** [comment]
Update - Psake is not being used anymore in build script, can be removed completely. 
Reference - https://ably-real-time.slack.com/archives/C0174D4AP4P/p1596014526009300
