### ISSUE TITLE
Review need for our own Result class

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-dotnet#429]
I was chasing [this broken link](https://github.com/ably/ably-dotnet/blob/5f6dd572fa2984601e868632b4b5d58f5ceeab46/src/IO.Ably.Shared/Result.cs#L65) to see if I could find a perma-link that didn't reference `master` and found that the origin repository doesn't have its own `Result` class at all. Presumably got rid of in favour of a .NET foundational class or interface?

I don't have time to dig in to this myself right now but I would like to see this addressed, please. For now I will remove the comment given the link is broken anyway - that change will appear in the PR I'm going to raise shortly.

Relates to #428 (see that issue for more context).

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-107) by [Unito](https://www.unito.io/learn-more)

**Comment by marto83** [comment]
Unfortunately there isn't a foundational Result class in c# :(. Let's remove the broken link is it doesn't exist any more. It seems the author of the original result class has moved on and build a more comprehensive framework which we don't need.

**Comment by sacOO7** [comment]
+1 @marto83 We don't have any foundational Result class in c# with the capabilities we are looking for.
Also, the broken link is already removed it seems. 
I believe we can close this issue.

**Comment by tomkirbygreen** [comment]
The concensus

**Comment by tomkirbygreen** [comment]
The consensus from Martin and Sachin is that this is effectively a non-issue so I'm closing it.
