### ISSUE TITLE
[CI] Fix build and tests

### ISSUE THREAD

**Issue by sacOO7** [ably/ably-dotnet#435]
- From https://github.com/ably/ably-dotnet/pull/431#issuecomment-672181808.
- Need to fix build on local and CI (Also make sure, it works across different platforms) 
- Make sure every test runs successfully even if run in isolation.

-  Failing tests - https://ably-real-time.slack.com/archives/C0174D4AP4P/p1596120980020500
-  CI - https://ably-real-time.slack.com/archives/C0174D4AP4P/p1596122321028600
-  CI - https://ably-real-time.slack.com/archives/C0174D4AP4P/p1596187625031700

**Comment by QuintinWillison** [comment]
Sorry for the noise, @owenpearson ... I accidentally assigned this to you for a moment there as my head was in JS space!
