### ISSUE TITLE
Defaults: Generate environment fallbacks

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-dotnet#438]
Per `RSC15g`, introduced in https://github.com/ably/docs/pull/965.

See https://github.com/ably/ably-js/pull/682 and https://github.com/ably/ably-ruby/pull/196 for reference implementations.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-106) by [Unito](https://www.unito.io/learn-more)

**Comment by sacOO7** [comment]
Also adding [Java PR](https://github.com/ably/ably-java/pull/618) as a reference implementation.

**Comment by kavalerov** [comment]
Reopening this as the PR is still open

**Comment by kavalerov** [comment]
@jamienewcomb is there a reason why this is not synced to Jira?

**Comment by kavalerov** [comment]
Ok, I just don't see Unito comment under the description of the issue.

**Comment by jamienewcomb** [comment]
> Ok, I just don't see Unito comment under the description of the issue.

We have only recently set up showing the link on github issues which is why it is not appearing. Now you have reopened, it should appear today
