### ISSUE TITLE
Deprecate history methods taking untilAttach parameter

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-dotnet#449]
Spawned from https://github.com/ably/docs/pull/980.

The deprecation warning needs to be pretty strong and should explain why this parameter is not useful. New method overloads may need to be added.

The `csharp` examples in docs ([see PR](https://github.com/ably/docs/pull/980/files)) will need updating once this change has been released.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-127) by [Unito](https://www.unito.io/learn-more)

**Comment by sacOO7** [comment]
Related to https://github.com/ably/ably-dotnet/issues/100
