### ISSUE TITLE
Meaning of "Token unrecognized" - reconnect working but resume failing

### ISSUE THREAD

**Issue by markcoxsmith** [ably/ably-dotnet#463]
**Client Comments**
I am seeing "token unrecognized" in the middle of a reconnection. I've attached a verbose Ably log (clipped down to the relevant section) - what seems to precipitate the event is a 503 type temporary disconnection but then when it tries to reconnect, it's saying it's an invalid token, seemingly, but then the connection appears to succeed. Could you please advise?

**Comments from Mark**
You've hit a bug in our system unfortunately. Your previous connection died because your token has expired and you then try to resume with a new token. The reconnect works but the resume fails because we compare permissions from the old and new tokens and have been cleared out the old token too promptly. This means that if there were any messages published between the old token expiry and the reconnect then these will have been missed. My suggestion is that you perform a history query on seeing this error if missing these messages is an issue.

**Comment by sacOO7** [comment]
@markcoxsmith can you also attach the verbose logs mentioned by the client. That will give more insight into the exact error. Also, the system bug you mentioned might hold true in the current case.

**Comment by markcoxsmith** [comment]
@sacOO7 , we don't have this in the ticket because these logs are available form our side. It might be referring to logs in the previous issues. Will check the slack channel and attach you

**Comment by deanna-lad** [comment]
Closing because it is stale.
