### ISSUE TITLE
Message Data objects strip properties containing null values

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-dotnet#491]
We've had a customer report ([via Slack](https://ably-real-time.slack.com/archives/CS9TP956F/p1608553869071000)) that if they publish a `Message` where one of the properties of the `Data` object has a `null` value, then subscribers don't see that property.

Looking at the code, I think it is [this line](https://github.com/ably/ably-dotnet/blob/31df773a2380588fb3636f3e90e0e7b271fa90c4/src/IO.Ably.Shared/JsonHelper.cs#L29) at fault - where we are explicitly overriding the Newtonsoft library default configuration in order to make it ignore `null` values rather than include then.

While [TM2d](https://docs.ably.io/client-lib-development-guide/features/#TM2d) does not go into much detail about what "-encodable" means, the [JSON specification](https://www.json.org/json-en.html) clearly permits `null` as a valid `value` in an `object`.

Internal discussion is [here](https://ably-real-time.slack.com/archives/C0174D4AP4P/p1608562173053700).

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-514) by [Unito](https://www.unito.io)

**Comment by marto83** [comment]
@QuintinWillison. This has been raised before. If the customer requires full control over the sent json then they can look at this sample: https://github.com/ably/ably-dotnet/issues/92#issuecomment-370090243. 

We should probably include an easier way for this to be achieved.

**Comment by sacOO7** [comment]
I think the above solution assumed that there is an implicit understanding between clients for sending, receiving, and handling missing attributes in the messages across different systems.
Also, one of the reasons to get rid of keys with null values must be to reduce the unnecessary payload size (Correct me if I am wrong @marto83 ).
Also, if you already have model available

**Comment by marto83** [comment]
The main reason we have the current settings is because of the json requirements for the ably wrapper message. 😉 

Don't try and fix the internal settings for the json serializer. Best provide an overload or an extension method where people can choose how their object is serialized.

**Comment by sacOO7** [comment]
Ofc, there is no reason to change current settings. You can always write custom serializer or set some other value 😬

**Comment by QuintinWillison** [comment]
The default behaviour, when it comes to processing customer `Data`, should be to do what is most logical and what is the least surprising.

It's an implementation detail that the same serialisation options are used for internal data structures like the Ably wrapper message, as well as for arbitrary customer-supplied `Data`. So, please fix the implementation so that customer data is treated transparently with with least surprises. That means that if a key is present then it is sent.

We cannot make assumptions around customer intentions. As I've already said, JSON - out-of-the-box - supports `null` values and I would expect any JSON-carrying implementation (especially schema-less) to carry them over... as discrete from "key not present".

**Comment by sacOO7** [comment]
https://stackoverflow.com/questions/38960844/json-net-not-including-null-properties-with-emitdefaultvalue-false/38961409#38961409

**Comment by sacOO7** [comment]
@marto83 what do you think about @QuintinWillison opinion? I don't see much impact if we remove the ```null``` ignore check.
It will affect, only in cases where the model strictly adheres to message with non-null values. WDYT?

**Comment by marto83** [comment]
The current behaviour is default even though it is not ideal. If we change that behaviour we will be breaking current client that depend on skipping null values. We need a way to set the serialization settings for the message data that override the default. I don't know what will be the best way to do it. 
In my mind for the long term I would like to remove the dependency of newtonsoft.json and let users choose what serialization library they want for the payload. 
I still suggest we have an extension method that lets you specify the serialization settings.

**Comment by sacOO7** [comment]
> https://stackoverflow.com/questions/38960844/json-net-not-including-null-properties-with-emitdefaultvalue-false/38961409#38961409

This article defines a way to ignore default serialization settings. Maybe we can use it.

**Comment by sacOO7** [comment]
I will do a quick fix for this by using a custom JsonConverter for Message ```Data``` attribute. We will keep default behaviour same for the rest of the stuff.

**Comment by marto83** [comment]
I had a look at the fix that Sachin did. It's a good way of dealing with it, we need to make sure the same is done for the Data inside PresenceMessages. 

My concern about this being a breaking change to the current behaviour is still valid. We will be fixing it for new people but we will be breaking it for everybody using the library at the moment. We need to have a switch where this behaviour is explicit and we can slowly deprecate the old way.

**Comment by sacOO7** [comment]
+1 @marto83 , yeah this can be a breaking change for clients expecting an old behaviour, where `null` values keys are ignored. We should add this change explicitly using some SDK config. setting.
