### ISSUE TITLE
Implement RSC7d (Ably-Agent header)

### ISSUE THREAD

**Issue by owenpearson** [ably/ably-dotnet#498]
see [PR](https://github.com/ably/docs/pull/1034) and [spec point](https://ably-docs.herokuapp.com/client-lib-development-guide/features/#RSC7d) for context.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-683) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
This was not implemented, so I'm not sure why this was closed. I am reopening this issue as we still need to work on this issue.

**Comment by sacOO7** [comment]
I was looking into this last week. I found some of the cross-platform libraries that will provide os/system details.

https://github.com/Aragas/SystemInfoLibrary and 
https://github.com/jamesmontemagno/DeviceInfoPlugin

One of the main issues is, these libraries were last updated 3 years back. So, it will be difficult to guess how stable versioning they will provide for the given system. There is a probability of these libraries raising exceptions for tracking information for new/unknown systems.

**Comment by sacOO7** [comment]
As per discussion with @QuintinWillison, for now we will be focusing on supporting basic agent headers instead of going for advanced system-specific information.
