### ISSUE TITLE
Consistent README

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#5]
See https://github.com/ably/ably-ruby/blob/master/README.md for an example of a common format used for the client library README.  The README must include examples of using the most common features.  

We must also include:

* Installation instructions including how to install from a package manager i.e. similar to NPM or RubyGems
* License info

**Comment by yavor87** [comment]
I updated the README in this commit: https://github.com/ably/ably-dotnet/blob/385a3c9056f58052fa358eda515c18715e30add8/README.md

**Comment by mattheworiordan** [comment]
Thanks, that's an improvement, although we are missing more thorough examples like the other READMEs have.  Perhaps look at that once the spec is complete?

**Comment by mattheworiordan** [comment]
@yavor87 we really need a more complete set of examples, see https://github.com/ably/ably-ruby for an example. Without this, it is quite hard for a dev to know where to start, and for our own documentation purposes, this is necessary

I have addressed the license issues.
