### ISSUE TITLE
Heartbeat support for detecting dropped connections

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-dotnet#507]
Implementation of [RTN23a](https://docs.ably.io/client-lib-development-guide/features/#RTN23a) for this client library is now deemed necessary.

See [this internal Slack comment](https://ably-real-time.slack.com/archives/CURL4U2FP/p1620762328187400) for context in terms of why it's deemed necessary.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-828) by [Unito](https://www.unito.io)

**Comment by tomkirbygreen** [comment]
I've been doing some analysis for this over the weekend. Will discuss my observations with Martin on Monday (tomorrow).
