### ISSUE TITLE
Unable to load IO.Ably.dll in Unity

### ISSUE THREAD

**Issue by Drazail** [ably/ably-dotnet#522]
When importing ably-dotnet as a custom package I get the following error:
```
Assembly 'Assets/UnityPackages/Ably/IO.Ably.dll' will not be loaded due to errors:
Unable to resolve reference 'System.Threading.Channels'. Is the assembly missing or incompatible with the current platform?

Unable to resolve reference 'System.Threading.Tasks.Extensions'. Is the assembly missing or incompatible with the current platform?
```
#### specs

- Unity Versions: 2021.1.5 / 2020.2.5
- Api Compatibility Level: .NET4.x
- Scripting Backend: Mono
- Platform: PC, Mac & Linux Standalone

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-936) by [Unito](https://www.unito.io)

**Comment by tomkirbygreen** [comment]
Thank you for raising this. We'll take a look and get back to you.

**Comment by marto83** [comment]
Sorry @Drazail. I didn't include the dependencies you mentioned into the 1.2.4 Unity package. I've updated the unitypackage in the 1.2.4 release (https://github.com/ably/ably-dotnet/releases/tag/1.2.4). Please download it again.

**Comment by Drazail** [comment]
@marto83 

seems to resolve the import issue, however now a `EntryPointNotFoundException` is thrown on object initialization. ill make a new issue regarding that.

thanks again for your fast response.
