### ISSUE TITLE
UseBinaryProtocol causes presence data to become null

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#54]
Hello.
I'm using branch Async-Refactor-On-Master. With UseBinaryProtocol = true and Presence.EnterClient, associated clients data becomes null. Seems like an issue with MsgPack.
On a screenshot first connection UseBinaryProtocol = true, and second is UseBinaryProtocol = false
![capture](https://cloud.githubusercontent.com/assets/4531542/14784524/c3f9757c-0afe-11e6-87ba-63ff5d4957e9.PNG)

```C#
  var ablyRealtime = new AblyRealtime(new ClientOptions()            {
                Key = "APIKEY",
                UseBinaryProtocol = true});

            var channel = ablyRealtime.Channels.Get("mychannel");
            channel.Attach();
            await channel.Presence.EnterClient("clientid1", "mydata");
```
Thanks for your work. Impressive. Can't wait for the release.

**Comment by mattheworiordan** [comment]
Hi @lovetofail, we're on it, we'll take a look to see if we an figure out what the problem is.  @marto83 mind taking a look?

**Comment by marto83** [comment]
@lovetofail I can reproduce it. As you suspected the data is not serialised at all when using msgpack. I'll get it fixed and let you know.

**Comment by marto83** [comment]
@lovetofail thanks for spotting those. Currently the Rest and Realtime clients use slightly different serializers. I'm working over the next couple of weeks to get this sorted. For the time being I patched how the Presence message is serialized so it should work now.
