### ISSUE TITLE
Presence timestamp init issue

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#56]
Timestamp is wrong on channel.Presence.EnterClient
Video http://screencast.com/t/qJlIuMe8yyc
If I set a breakpoint in Presence_MessageReceived2 the date is correct though.
```c#
var ablyRealtime = new AblyRealtime(new ClientOptions()
            {
                Key = "APIKEY",
                UseBinaryProtocol = true
            });

            var channel = ablyRealtime.Channels.Get("mychannel");
            channel.Attach();
            channel.Presence.MessageReceived += Presence_MessageReceived2;
            await channel.Presence.EnterClient("clientid1", "mydata");
            return;
private void Presence_MessageReceived2(PresenceMessage[] obj)
        {
            Console.WriteLine(string.Join("\n", obj.Select(m => m.connectionId + "\t" + m.timestamp)));
        }
```

**Comment by marto83** [comment]
@lovetofail good spot. The Realtime Client is a bit unstanble at the moment. I'm reworking a lot of the internals now and will take me about a week or so to push a more stable version. I'll keep this bug open and will let you know once I push the new version. 

Thanks you so much for going through it and finding these issues.

**Comment by lovetofail** [comment]
Ok. I know that this is in development. Can I post here issues I find? Or should I create separate Issue everytime? If they aren't relevant just ignore them.

```
UseBinaryProtocol=true;
await channelPresence.Presence.Enter(new string[] { "data1", "data2" });
```
I'm getting System.String[]. Same happens if I use my custom class. It's fine with UseBinaryProtocol=false though;
```
Client ID	Connection ID
DESKTOP-F1TP9Q4	m4mW8SPiTk
data: "System.String[]", updatedAt: 15:17:32.533
```

**Comment by marto83** [comment]
I think it will be better to post separate issue. It will be a good test for me once I've finished the spec to go through the issues and make sure it will work as expected for you :)

**Comment by marto83** [comment]
@lovetofail Just to let you know I'm getting on with Presence now. 
If you are trying things out I fixed a lot of issues with channels in the spec/realtime-channels. 
By the way I fixed the MsgPack serialisers so the above issue might be fixed. Haven't tested it yet!

Also if you are testing the library can you let me know whether you experience any threading and concurrency issues.

**Comment by mattheworiordan** [comment]
@marto83 what is the status on this one?

**Comment by marto83** [comment]
@mattheworiordan this is still an issue with Presence message containing custom data and the binary serializer. I'll look into as a priority as it has been some time.

**Comment by marto83** [comment]
@lovetofail there was a presenceMessage serialization issue and I also fixed the missing timestamp. Let me know if you still get it.

**Comment by lovetofail** [comment]
Thank you. useBinaryProtocol=true serialization seems to work as well as timestamp. Please, feel free to close issues. I just don't know when to do it.

**Comment by marto83** [comment]
Great to hear. I'll close the issue.
