### ISSUE TITLE
MessageExtras is incorrectly described as being not supported

### ISSUE THREAD

**Issue by markcoxsmith** [ably/ably-dotnet#593]
The following part of the readme describes MessagesExtras as not being supported by the .NET library under [Known Limitations](https://github.com/ably/ably-dotnet#known-limitations) when we do as per the following [search](https://github.com/ably/ably-dotnet/search?q=MessageExtras) in our codebase

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1013) by [Unito](https://www.unito.io)

**Comment by tbedford** [comment]
@tomkirbygreen - are you able to confirm? Thanks.

**Comment by tomkirbygreen** [comment]
It is supported apparently. Sachin Shinde worked on refactoring it in August of last year.

**Comment by tbedford** [comment]
@tomkirbygreen - do you want docs team to update, or are you happy to do it?

**Comment by tomkirbygreen** [comment]
I'll create a PR to update the reader.md in a mo Tony.

**Comment by tbedford** [comment]
OK thanks

**Comment by tbedford** [comment]
See https://github.com/ably/ably-dotnet/pull/594

@marklewin - can you keep an eye on this please and ensure the PR gets reviewed and merged. Thanks!

**Comment by tomkirbygreen** [comment]
I'm waiting for the release PR to be approved before any other PRs go in. I'll ask @QuintinWillison  if he can take a look at it today.

https://github.com/ably/ably-dotnet/pull/591

**Comment by tomkirbygreen** [comment]
The PR to update the root `readme.md` has been landed.
