### ISSUE TITLE
Take control of our Assembly Version

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-dotnet#617]
Currently the `ably-dotnet` `AssemblyVersion` is tied to the `Ably Protocol` version. This restriction is now holding us back since it does not allow us for example to clearly indicate a major step revision in the library. This plays havoc with how .NET natively wants to do versioning, particularly when it comes package management tech like `nuget`.

For example, if we wanted to clearly indicate a `2.0.0.0` or `3.0.0.0` library evolution it is impossible. If we had control of our `AssemblyVersion` we could allow customers to try new evolutions and or fallback to older iterations, including the current `1.2.x` protocol-esc versioned ones.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1042) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Related: [ADR34 (internal)](https://ably.atlassian.net/wiki/spaces/ENG/pages/1505886246/ADR34%3A+SDK+versioning+policy).

**Comment by tomkirbygreen** [comment]
Closing this since the basic idea of SDKs leading their own lives, version-wise, has been accepted. 

There are however details... The first version to break away from `1.2.*` will go straight to `2.0.*`, there will be no `1.3.*` or `1.4.*` etc. In order to qualify for the `2.0.0` change the SDK needs to contain significant new customer value and / or required breaking changes.

So for now we will continue to shoehorn fixes and minor enhancements into the [SemVer](https://semver.org/) `patch` field leading to `1.2.9`, `1.2.10`, `1.2.11` etc.
