### ISSUE TITLE
Collection was modified exception

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#64]
I'm rarely getting this error. Using latest commit.
After _queue.Remove(message); there is an exception saying Collection was modified for "messagesToRemove"
Also, is BinaryProtocol and Encryption implemented?

```
public void FailChannelMessages(string name, ErrorInfo error)
        {
            lock (_syncObject)
            {
                var messagesToRemove = _queue.Where(x => x.Message.channel == name);
                foreach (var message in messagesToRemove)
                {
                    message.SafeExecute(false, error);
                    _queue.Remove(message);
                }
            }
        }
```

**Comment by marto83** [comment]
@lovetofail Sorry about the above. I'll get this fixed this evening. 

Both the BinaryProtocol and Encryption are implemented. When creating a channel pass in ChannelOptions with either `encrypted = true`. This will generate a random key and encrypt all messages with it. However if you are using 2 different clients make sure you pass a static key. 

Have a look at the GenerateKey function from the CipherEncoderTests Class: https://github.com/ably/ably-dotnet/blob/568036e69ad327c3eb8058d70d5ca27510ce10cd/src/Ably.Tests/MessageEncodes/CipherEncoderTests.cs#L23-L43
