### ISSUE TITLE
Expired token not renewed second time.

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#65]
When token expires, it is renewed one time. But second time it isn't. Connection becomes Failed.
http://screencast.com/t/WMoxVyMGrQ

Looks like this method is not used anywhere.
```
public void Reset()
        {
            lock (_syncLock)
            {
                Attempts.Clear();
                TriedToRenewToken = false;
            }
        }
```

**Comment by marto83** [comment]
Thanks. Looking into it

**Comment by marto83** [comment]
@lovetofail I found the reason behind the issue. I just need to confirm and half fixed the issue. I just need to confirm the message I should expect after the connection has been resumed. I'll get it sorted in the morning.
