### ISSUE TITLE
useBinaryProtocol=true memory leak?

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#66]
Second window on screenshots useBinaryProtocol=false
http://screencast.com/t/JXnX0mJnP
http://screencast.com/t/rolIHeptPGto
http://screencast.com/t/lrpooQDLuK

```
               var client = Realtime.Test();
                client.Connect();
                var channel = client.Get("ubfi:presence");
                channel.Attach();
                channel.Presence.Subscribe(Presence_MessageReceived2);
                while (true)
                {              
                    channel.Publish(new Random().Next(1000000000, 1000000000).ToString(), new Random().Next(1000000000, 1000000000).ToString());                   
                    Thread.Sleep(1000);
                }
```

**Comment by marto83** [comment]
I have an idea what could be causing this. I recreate the serialisers every time they are needed. I'll try and create them once per library instance and see if it helps.

**Comment by marto83** [comment]
That should be fixed now. I was initializing the context far too many times.
