### ISSUE TITLE
Possible minor issues

### ISSUE THREAD

**Issue by lovetofail** [ably/ably-dotnet#68]
I'm using PVS Studio addon for Visual Studio. It found some issues. Wondering if they are relevant
Always true http://screencast.com/t/XJc52lO3Zj
![2016-06-14_1727](https://cloud.githubusercontent.com/assets/4531542/16046603/b73d06d6-3255-11e6-82ac-774644e7b56c.png)

**Comment by marto83** [comment]
Good catch. I'll get that fixed it needs to be && instead of ||

**Comment by lovetofail** [comment]
Thanks. On the screenshot above you'll see other possible issues as well.
