### ISSUE TITLE
authCallback does not support TokenRequest or token string

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#75]
See http://docs.ably.io/client-lib-development-guide/features/#RSA8d, then see https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/AuthOptions.cs#L18

It appears that `authCallback` does not allow a TokenRequest or token string to be passed in.  

Also, can you advise how we should recommend users retrieve a JSON object via HTTP and then convert that to a `TokenDetails` or `TokenRequest` object.  Ideally we'd even allow a JSON object to be passed in.

**Comment by mattheworiordan** [comment]
@marto83 have you misread the issue perhaps?  We are talking here about `authCallback`, not `authUrl`, so there is no content type

**Comment by marto83** [comment]
oh yes. You are right. AuthCallback only allows TokenDetails. I'll update it to access an object back and then try to figure out what it is. 
So we should support: `string` for token', 'TokenDetails` and `TokenRequest`. Correct?

**Comment by mattheworiordan** [comment]
Correct
On Wed, 29 Jun 2016 at 09:15, Martin Georgiev <notifications@github.com>
wrote:

> oh yes. You are right. AuthCallback only allows TokenDetails. I'll update
> it to access an object back and then try to figure out what it is.
> So we should support: string for token', 'TokenDetailsandTokenRequest`.
> Correct?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ably/ably-dotnet/issues/75#issuecomment-229287691>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AACrDab-PHerEQkr5HMREhJEnbim1fMyks5qQimPgaJpZM4JAmyS>
> .
>
-- 
Matthew O'Riordan
CEO
Ably - simply better realtime messaging <https://www.ably.io>

**Comment by marto83** [comment]
Fixed in 0.8.5-beta14
