### ISSUE TITLE
Unity: System.Runtime.CompilerServices.Unsafe is missing from the package

### ISSUE THREAD

**Issue by eAi** [ably/ably-dotnet#752]
With Unity 2020.3.14, importing the package into an empty project produces an error:

ArgumentException: The Assembly System.Runtime.CompilerServices.Unsafe is referenced by System.Threading.Tasks.Extensions ('Assets/UnityPackages/Ably/System.Threading.Tasks.Extensions.dll'). But the dll is not allowed to be included or could not be found.

Turning on 'Allow unsafe code' in the Player settings doesn't fix this.

Copying System.Runtime.CompilerServices.Unsafe.dll from elsewhere into the Ably folder fixes this error - but I'm not sure if the DLL version I'm using is correct.

Is unsafe code actually required?

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1142) by [Unito](https://www.unito.io)

**Comment by marto83** [comment]
There is no unsafe code in the library. I'll make sure it's included in the unity package.

**Comment by sacOO7** [comment]
This has been fixed long back! Please follow [Ably Unity Section](https://github.com/ably/ably-dotnet#unity) for more information.
