### ISSUE TITLE
Unity on iOS: Error 80019

### ISSUE THREAD

**Issue by eAi** [ably/ably-dotnet#762]
I've put a ticket in with support for this error that we're seeing in Unity on device only - the same code works in the editor. In trying to track it down, I notice that the inner exception ('ex') isn't put into the ErrorInfo constructor so it isn't available via the AblyRealitime.Connection.ErrorReason object which it makes it difficult to see it, as instructed! Is this a mistake?

https://github.com/ably/ably-dotnet/blob/b9ec2dc4e093df06cd54beb65f9cddeb6f5ace7f/src/IO.Ably.Shared/AblyAuth.cs#L291-L303

These exceptions do put it into the ErrorInfo constructor:

https://github.com/ably/ably-dotnet/blob/b9ec2dc4e093df06cd54beb65f9cddeb6f5ace7f/src/IO.Ably.Shared/AblyAuth.cs#L338-L344
https://github.com/ably/ably-dotnet/blob/b9ec2dc4e093df06cd54beb65f9cddeb6f5ace7f/src/IO.Ably.Shared/AblyAuth.cs#L357-L363

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1147) by [Unito](https://www.unito.io)

**Comment by marto83** [comment]
Hi @eAi. It looks like we have missed this one. I'm going to push a PR to fix it so it can be included in the next release.
