### ISSUE TITLE
Xamarin multiple platform target support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#79]
We have had this reported from a customer:

> Could not install package 'WebSocket4Net 0.14.1'. You are trying to install this package into a project that targets 'portable-net45+win+MonoTouch10+MonoAndroid10+xamarinmac20+xamarintvos10+xamarinwatchos10+xamarinios10'

Given it appears that only the WS library is causing this issue, is it worth considering swapping it out with https://github.com/NVentimiglia/Websockets.PCL?

**Comment by marto83** [comment]
I'm closing this as we have the .net standard library.
