### ISSUE TITLE
Sync REST methods

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#80]
Instead of expecting customers to use `OperationAsync.GetAwaiter().GetResult()` for all Async options in the REST API when they cannot use `await` we should offer a REST API as well

**Comment by marto83** [comment]
Added Sync Extension methods with this commit. 41ac58b41d9685777b065afb228db7c3e6a6961d

Users will need to add an extra namespace to use them. I'd for people to use the async methods if possible and have the sync ones for when they are needed.

Still need to update the readme file.

**Comment by marto83** [comment]
UPDATE:
Add the sync methods to the Rest interfaces and not the Realtime ones.

**Comment by marto83** [comment]
I've moved the sync methods from extensions to members of the actual rest interfaces.

**Comment by mattheworiordan** [comment]
Should we not update the documentation somewhere to reflect this?  Perhaps we should keep a separate issue to track documentation updates so we can do in one batch?  BTW. We also have tutorials now, see https://www.ably.io/tutorials.  Would be nice to have one for Xamarin at least and perhaps one for server-side .NET.  Will see if we can get someone on our end to do that.
