### ISSUE TITLE
Various inconsistencies following review of documentation

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#81]
@marto83 please see the .NET docs you worked on and the commits I added on top at https://github.com/ably/docs/pull/138.  I have merged that in now and am about to deploy to the main website.

Whilst working through the docs, I wrote down various notes in regards to inconsistencies in the .NET lib from the spec / other libraries.
- [x] Having the public methods capitalised in C# and not in any other languages is a pain, but I don't suggest we change it.  It's more idiomatic this way, and we'll likely encounter this in other langs down the line anyway.
- [x] I noticed in a few cases such as `Presence.get` you opted for method arguments as opposed to an object or Hash params. The problem with this is it makes it hard to introduce a new argument that is frequently used unless C# supports named arguments.  For example, if the def is `get(foo1, foo2, foo3)` and later we want to add `foo4` which is a frequently specified arg, I believe you'd have to call it as `get(null, null, null, 'foo4val')`.  If we used an object type instead, then `get(new GetOptions { foo4 = 'foo4val' })` works better I think.  Do you know why we veered from this standard in some areas?
- [x] connection state change type, why is this named differently from the spec?
- [x] StatsDataRequest and DataRequest should be named `StatsQueryParams` and `HistoryQueryParams` to be more consistent with the other libs and also to make more sense.  That class is not a request, it's params for a request
- [x] We use upper case for all public methods / attributes, yet we don't for: https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Types/ErrorInfo.cs. https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Types/Message.cs  and https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/Types/PresenceMessage.cs.  We should fix that.
- [x] Paginated result, `IsLast()` missing
- [x] `Capability` class has only been defined in CSharp, yet there is no documentation for it.  I need you to provide some simple examples on how to use it and I can write some docs for usage.
- [x] Why does a `TokenRequest` have a string `Ttl` property instead of an `Integer` or `TimeSpan`?  Same issue applies to `Timestamp`, it's a `string`?  I understand the need for a `TokenDetails` capability to be a `string`, but the other fields don't make sense as `string`s
- [x] `StatsINtervalGranularity` should be renamed to `StatsIntervalGranularity`
- [x] Can you confirm, is `PaginatedResult.HasNext` an attribute or a method, looks like a method to me.  Same question for `Presence.SyncComplete`, documented as an attribute but I think it's a lambda method?
- [x] `https://github.com/ably/ably-dotnet/blob/master/src/IO.Ably.Shared/DataRequestQuery.cs` - `By` should be `Unit` for specifying stats interval
- [x] `ConnectionState` `event` args should be called `state` for consistency with all other lib implementations
- [x] Why does `Unsubscribe` return a bool for action or event specific calls and then not for Unsubscribe for all on channels?  Unless there is a good reason to return a bool, we should make it consistent and return nothing
- [x] Why does `Attach` & `Detach` have a timespan in the lambda expression callback?
- [x] `Enter`/`Leave`/`Update`\* methods need to be overloaded so that the data argument can be omitted
- [x] Why does `GetAsync(bool waitForSync = true, string clientId = "", string connectionId = "")` default to "" instead of Null.  I see a few examples in the code like this
- [x] The history attribute is `untilAttach`, not `untilAttached`

**Comment by marto83** [comment]
I've added IsLast property to PaginatedResult

**Comment by marto83** [comment]
Regarding Capability examples. Have a look at https://github.com/ably/ably-dotnet/blob/b9e4c355ac487e187a6e49879f0c7760677edc1b/src/IO.Ably.Tests/CapabilityTests.cs 
I did the class about a couple of years ago. We should go over it to make sure it supports the full capability spec.

**Comment by marto83** [comment]
`TokenRequest` is not a class that the user creates manually. That's why I left everything raw so it is easier to pass it back and forth. Having said that if you prefer I can change the types.

**Comment by marto83** [comment]
I renamed StatsIntervalGranularity -> StatsGranularity. Should I keep it like that or change it back.

**Comment by mattheworiordan** [comment]
> Regarding Capability examples. Have a look at https://github.com/ably/ably-dotnet/blob/b9e4c355ac487e187a6e49879f0c7760677edc1b/src/IO.Ably.Tests/CapabilityTests.cs> I did the class about a couple of years ago. We should go over it to make sure it supports the full capability spec.

It looks right so long as you can confirm users can:
* Assign Publish, Subscribe, History, Presence, Statistics as privileges
* Can choose to provide a JSON string instead of a Capability object for consistency with other libraries.

> TokenRequest is not a class that the user creates manually. 

But they access that `TokenRequest` when calling `CreateTokenRequest`, and then the types are not valid, so I don't see any good reason to use the wrong types here.

> I renamed StatsIntervalGranularity -> StatsGranularity. Should I keep it like that or change it back.

According to the [IDL](http://docs.ably.io/client-lib-development-guide/features/#idl) it's `StatsIntervalGranularity` so please change to `StatsIntervalGranularity`

**Comment by marto83** [comment]
`HasNext` and `SyncComplete` are both properties. They just use the c# shortcut syntax https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#expression-bodies-on-property-like-function-members

**Comment by mattheworiordan** [comment]
> HasNext and SyncComplete are both properties. They just use the c# shortcut syntax https://github.com/dotnet/roslyn/wiki/New-Language-Features-in-C%23-6#expression-bodies-on-property-like-function-members

Ok, thanks for clarifying, not seen that before.  I'm an old school C# dev :)

**Comment by marto83** [comment]
I can't figure out why I would have changed the TokenRequest properties to strings. I've changed them back. Need to check the msgpack serialisation to make sure it still works ok. 
I'm moving on to making all properties uppercase. I remember Kosta made the lower case for serialisation reasons but it's not difficult to change them back.
