### ISSUE TITLE
Include version info in requests

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#82]
See https://github.com/ably/ably-java/pull/144 and https://github.com/ably/ably-java/pull/143, which is part of the 0.9 spec, but is key for us to keep track of who is using older versions.

We should add this into this 0.8 branch of the .NET lib

**Comment by marto83** [comment]
@mattheworiordan is that only for the Rest library.

**Comment by marto83** [comment]
Also what format do you want to have for these. I've set it to `IO.Ably-0.8.3.0`. Let me know if you would like it changed :)

**Comment by mattheworiordan** [comment]
See http://docs.ably.io/client-lib-development-guide/features/#RSC7b for more info on version format.

Your version unfortunately has no mention of the client library itself, so it should be something like `dotnet-0.8.3`.  Also, you have appended an additional version number in your example above, our versions are always three pairs i.e. `0.8.3`.

Thanks
