### ISSUE TITLE
Skipped Test: PresenceSandboxSpecs.PresenceMapBehaviour_ShouldConformToSpec

### ISSUE THREAD

**Issue by tomkirbygreen** [ably/ably-dotnet#837]
Re-enable the `PresenceSandboxSpecs.PresenceMapBehaviour_ShouldConformToSpec` test.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1191) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Link to internal discussion - https://ably-real-time.slack.com/archives/C0174D4AP4P/p1641993990001800
