### ISSUE TITLE
Universal Windows Platform support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#90]
@marto83 creating this issue to track your progress with UWP support.

Please post updates following your spike here and I will tell customers to track this issue.

**Comment by mattheworiordan** [comment]
@marto83 any update on this?  A few customers still asking about it I am afraid.

**Comment by crm76** [comment]
Would love to see this happen. I have two product development cycles in a holding pattern as Ably would be our vendor of choice.

**Comment by marto83** [comment]
@crm76 I've been trying to get a .Net Standard library which can be used for all platforms. However I need to change the underlying web socket library as I'm having problems with WebSocket4Net. 
What I can do is produce a package just for UWP for you to test rather than go for a universal package. It will use the current code base and dependencies so I'm confident in its reliability. 
I can do than for middle of next week. I'll post an update here.

**Comment by marto83** [comment]
Not so good news here. I thought WebSocket4Net supported UWP but it doesn't so the only way to add support is to update the Socket transport. I'm going to base everything on the Microsoft websocket implementation to make sure it is cross platform. I will need to build some infrastructure code around it to make sure it fits in well with Ably. 
It will be a few weeks before I can get something ready for testing.

**Comment by mrueedi** [comment]
I want to second @crm76. The requirement to use a cloud pub/sub solution in my project is only one week old. But my project requires a PCL for UWP. Ably is so convincing overall, that I am determined to integrate it once this enhancement is ready. So keep up the good work and thanks from my side...

**Comment by marto83** [comment]
@crm76  and @mrueedi. I've got a version ready with support for UWP. I replaced the Websocket transport with one that's based on Microsoft's implementation. Please use version `0.8.5-beta5` from nuget. I'm going to keep the beta label as I want to do some more testing. None of the interfaces will change so you should be good to start using it.

**Comment by mrueedi** [comment]
Thanks a lot, Martin!
I noticed 0.8.3-beta3 already, installed it and got it successfully working (some rather basic use cases, but nevertheless). Will try beta5 now....

**Comment by marto83** [comment]
@mrueedi I'm going to close this issue for now. Feel free to reopen it or create a new one if you have any issues with UWP. 
We are up to beta7 which is stable and I've will soon look to remove the beta flag.
