### ISSUE TITLE
Possible NewtonSoft incompatibility

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-dotnet#91]
This from a customer:

> I've had some issues with a new version of Ably on .net when trying to use it other tools. This seems to do with Newtonsoft maybe not backward compatible. Please see attached. Do you have older versions for .net still available for download or available?

> My supplier wrote:-
> "There is a problem with the [COMPANY REDACTED] working with 9.x versions of the Json.Net, possibly a non-backwards compatibility
> in the Json.Net releases but we don’t have much information telling us what is might have caused the issue from the available documentation.

> Our plan is to always incorporate the latest version of (9.x) of Json.Net with the next release but it won’t be available in the short term."

From the attachment sent:

![image](https://cloud.githubusercontent.com/assets/43789/22434039/62c40006-e712-11e6-87c7-00717bbb5baf.png)

![image](https://cloud.githubusercontent.com/assets/43789/22434058/759897be-e712-11e6-84e7-2e279b9ffeaf.png)

![voila_capture 2017-01-30_05-35-31_pm](https://cloud.githubusercontent.com/assets/43789/22434102/a393d8a4-e712-11e6-96f7-2bdfc63c9fef.png)

![voila_capture 2017-01-30_05-36-39_pm](https://cloud.githubusercontent.com/assets/43789/22434139/ce52096c-e712-11e6-8de6-408762618f70.png)

**Comment by mattheworiordan** [comment]
This again from the customer following an update to resolve the issue:

![image](https://cloud.githubusercontent.com/assets/43789/22645842/08f51548-ec61-11e6-87b6-e63886ad80c2.png)

**Comment by marto83** [comment]
.net 4.5 assemblies are compatible with 4.6.2 so I don't think that should the issue. I tried to reproduce the error and can successfully compile the following code using the provided dll. 

      
      var options = new ClientOptions("") { UseBinaryProtocol = false};
      var ably = new AblyRealtime(options);
      ably.Connect();

       var token = ably.Auth.RequestToken();

       Console.WriteLine("Token: " + token.Token);

While doing further testing I found there is an issue with MsgPack initialisation so make sure for now you have `UseBinaryProtocol = true`.

**Comment by marto83** [comment]
I've published a beta package on nuget that has only 1 external dependency `MsgPack` and everything else has been merged in to make sure there are no conflicts. 
It can be installed using - `Install-Package ably.io -Pre`

Let me know if the same issue persists.

**Comment by mattheworiordan** [comment]
@marto83 the customer who had this issue has confirmed this resolved the problem.  Should we close this issue once that change is published on Nuget and on master?

**Comment by marto83** [comment]
Pulled the merged branch into master and published the latest nuget package with 3 the Newtonsoft dependency merged into the IO.Ably dll.
