### ISSUE TITLE
Ability to set the JsonSerializerSettings

### ISSUE THREAD

**Issue by drachele** [ably/ably-dotnet#92]
Hi,

Would it be possible to add a setting or property to the Ably client to allow customization of the Json serializer settings?

For example, we would like to be able to use a different **ContractResolver** in order to set the property names of our model objects automatically using the **CamelCasePropertyNamesContractResolver** when they are processed by Ably.

Thanks,

Dan.

**Comment by mattheworiordan** [comment]
Dan, we've discussed this type of thing in other statically typed libraries as well in fact.  It's a bit tricky because the interface we need to expose needs to be generic, so we have to be careful about implementing features that are specific to a particular trend or need by a user.

Can you explain what the problem is by not having this feature?  I'd like to have a think about the problem domain and how best we can solve it rather than evaluate a single feature request.

**Comment by drachele** [comment]
Hi Matt,

We are in the process of switching to Ably from another provider. We have an existing codebase with a complex domain model that contains a _LOT_ of model classes with a _LOT_ of properties. The front-end code has been written to use JSON objects with camel-case property names. Previously, we defined which JSON resolver we wanted to use and pushed the objects to the API. This took care of the camel-casing for us when serializing and pushing to clients.

In order for it to work with Ably, we would have to iterate over our entire domain model and add the `[JsonProperty("camelCaseName")]` attribute to all of our properties, which would be extremely time-consuming. That, or we would need to rewrite the front-end code to handle the JSON without camel-casing. Again, not ideal.

If there was a way to instruct the Ably API to use camel-casing (or another naming convention) by default when serializing the data, that would be great.

Hope that helps.

Cheers,
Dan.

**Comment by mattheworiordan** [comment]
Ok, thanks for the explanation Dan.

I will get the others to have a look at this, but if the front end client (which I assume is Javascript) relies on camelCase for the data payloads, and your .NET code currently uses another format, why not simply have a middleware encoder / decoder that handles receiving data from Ably and publishing data to Ably, and it itself uses a `CamelCasePropertyNamesContractResolver`.  i.e. pseudo code would be:

```javascript
class DataPortability {
   constructor(data: any) {
     this.data = data
   }
  
   forFrontend() => JsonObject {
     return this.data.changeCase('lowerCamelCase').toJson()
   }

   forBackend() => JsonObject {
     return this.data.changeCase('CamelCase').toJson()
   }
}

func publish(object) {
  channel.publish('event', DataPortability.new(object).forFrontend())
}
```

Am I missing something intrinsic in the marshalling process that prevents this from happening?

**Comment by drachele** [comment]
Not that I know of, we just wanted to make minimal changes to both the frontend and backend code.

FYI, a certain mutual acquaintance of ours has provided a solution on the .NET backend which seems to work without having to make any changes to the frontend JavaScript code...

**Comment by waynebrantley** [comment]
@drachele Care to share?

**Comment by drachele** [comment]
Here's a code snippet for you @waynebrantley:

```csharp
var serializedMessage = JsonConvert.SerializeObject(message,
    new JsonSerializerSettings
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver()
    });

var ablyMessage = new Message(channel, serializedMessage) {Encoding = "json"};

var restChannel = _restClient.Channels.Get("ablyChannel");
restChannel.Publish(ablyMessage);
```
