### ISSUE TITLE
ASP.NET Core support

### ISSUE THREAD

**Issue by siberianguy** [ably/ably-dotnet#93]
Tried to use Ably .NET library in netcoreapp1.1 application, but it seems to be incompatible with .NET Core. What's the status of .NET Core support?

**Comment by mattheworiordan** [comment]
We started working on adding .NET Core support about 1.5 weeks ago.  Unfortunately we hit an issue with the WebSocket lib, so we're now looking to swap that out with another lib.  We're hoping we'll be adding support quite soon.

**Comment by alexidsa** [comment]
Thanks for the information. Looking forward to it. By the way, great library guys. And great product overall (you just got it right, brilliant). Migrating from Pubnub, feels so good.

**Comment by marto83** [comment]
Hi @siberianguy, the library is now available (as 0.8.5-beta5) for .net core. I replaced the websocket library with one based on Microsofts websocket implementation.

If you are going to use the rest client I'm confident it works as expected. I still want to do a bit more testing for the realtime client to make sure the new websocket transport behaves as expected. Once that's done I'll push it as 0.8.5.

Let me know if you have any questions.
